/* =========================================================
   pol-ua 500 — exam #2 data
   CARDS (31) · ESSAYS (10)
   ========================================================= */

const CARDS = [
  { term:"Sincere Voting", cat:"Voting & Participation", def:"Casting your ballot for your true first-choice candidate, without considering who else is likely to win.", hint:"Opposite of strategic voting — no 'lesser evil' calculation." },
  { term:"Median Voter Theorem", cat:"Voting & Participation", def:"In a two-candidate majority-rule election with voters ranked on a single policy dimension, both candidates have an incentive to move their platform toward the voter in the exact middle of the distribution.", hint:"Both parties converge to the center — explains why platforms often look alike." },
  { term:"Strategic Voting", cat:"Voting & Participation", def:"Switching from your genuinely preferred candidate/party to vote instead for one that has a realistic chance of winning (or for a different party in order to moderate policy). In races with district magnitude = 1, this produces convergence around the top two candidates.", hint:"Strongest in majoritarian/FPTP systems; weak under proportional representation." },
  { term:"Vote Buying", cat:"Voting & Participation", def:"Exchanging material goods, money, or favors for votes; a form of electoral clientelism.", hint:"Undermines electoral integrity; studied via turnout anomalies." },
  { term:"Credible Exit Option", cat:"Voting & Participation", def:"The ability to genuinely leave a political relationship, giving citizens real leverage over the state.", hint:"Exit is credible only if leaving is actually feasible." },
  { term:"Voice (Hirschman)", cat:"Voting & Participation", def:"Using speech, protest, or political action to change an organization from within. Most forms of political participation — voting, signing petitions, calling representatives, boycotts, donations, demonstrations, attending council meetings — are forms of exerting voice.", hint:"Hirschman originally wrote about consumers facing declining product quality. Voice is chosen when exit is too costly or loyalty is high." },
  { term:"Loyalty (Hirschman)", cat:"Voting & Participation", def:"Staying attached to an organization or state despite dissatisfaction, usually out of emotional ties or hope things will improve.", hint:"Loyalty suppresses both exit and voice." },
  { term:"Collective Action Problem", cat:"Voting & Participation", def:"Individually rational behavior (free-riding) leads to a collectively suboptimal outcome — e.g., no one votes because each vote seems not to matter. Arises in participation (protests, petitions, donations, lobbying, voting) because the resulting good is typically a public good claimed from the state.", hint:"Public goods are non-excludable — you get them whether you participated or not, which invites free-riding." },
  { term:"Selective Incentives", cat:"Voting & Participation", def:"Private benefits given only to those who participate, used to overcome the collective action problem.", hint:"Olson's solution: make participation individually worthwhile." },
  { term:"Public Good", cat:"Voting & Participation", def:"A non-excludable and non-rival benefit — everyone benefits regardless of contribution.", hint:"Public goods create free-rider problems → collective action dilemma." },
  { term:"Ethnicity (Chandra 2006)", cat:"Ethnicity & Identity", def:"\"A subset of social identity categories for which eligibility is associated with (or believed to be associated with) descent.\" Examples (context-dependent): language, tribe, race, region, religion. Excludes identities siblings would not be expected to share (e.g., gender, sexual orientation).", hint:"Key: descent-based (or believed to be). Not freely chosen. Distinct from other social identities." },
  { term:"Ethnic Fractionalization", cat:"Ethnicity & Identity", def:"The probability that two randomly chosen people from a population belong to different ethnic groups. Scores range from near 0 (homogeneous) to near 1 (many small groups).", hint:"Does NOT capture inequality between groups — distinct from polarization." },
  { term:"Primordialism", cat:"Ethnicity & Identity", def:"The view that ethnic identities are ancient, fixed, and emotionally deep-rooted — treated as natural or inherited traits.", hint:"Criticized: ignores how identities shift historically." },
  { term:"Instrumentalism", cat:"Ethnicity & Identity", def:"View that ethnic identities are tools — elites manipulate them to mobilize voters and gain power.", hint:"Ethnicity as strategy, not essence." },
  { term:"Constructivism", cat:"Ethnicity & Identity", def:"View that ethnic identities are socially constructed and historically contingent — real but malleable.", hint:"Dominant modern view: identities are built, not given, but powerful once built." },
  { term:"Party Identification", cat:"Parties & Systems", def:"A voter's subjective alignment of themselves with a particular political party. Measured on surveys by questions like: \"Generally speaking, do you usually think of yourself as a Republican, a Democrat, an Independent, or what?\" with follow-ups on strength of attachment or which party an independent leans toward.", hint:"Distinct from 'who you voted for'. Scholars disagree: rational running tally (Fiorina) vs. group/social identity (Green et al.)." },
  { term:"Running Tally (Fiorina)", cat:"Parties & Systems", def:"Fiorina's view: party attachment is an ongoing retrospective summary of how each party has performed over time. Voters update it based on outcomes, so it is rational and revisable.", hint:"Partisanship is rational — you update based on what parties actually do." },
  { term:"Partisan Identity (Green, Palmquist & Schickler)", cat:"Parties & Systems", def:"The view that attachment to a party works like a team or group membership — emotional and stable, resistant even when the party changes its positions.", hint:"Explains why people don't switch parties even when their party underperforms." },
  { term:"Political Party", cat:"Parties & Systems", def:"An organization that competes in elections with the goal of placing its candidates in government office.", hint:"Distinguished from interest groups, which don't run candidates." },
  { term:"Nonpartisan System", cat:"Parties & Systems", def:"A political system (often a democracy) with no official political parties. Candidates run as individuals rather than under a party label.", hint:"Rare at the national level; more common at local/municipal level or in some small states." },
  { term:"One-Party System", cat:"Parties & Systems", def:"A system in which only one political party is legally allowed to hold power. Opposition parties are banned.", hint:"E.g., China (CCP), Soviet-era USSR, North Korea." },
  { term:"Single-Party Dominant System", cat:"Parties & Systems", def:"A system in which multiple parties may legally compete, but only one particular party has a realistic chance of gaining power across electoral cycles.", hint:"E.g., Japan (LDP), South Africa (ANC), Mexico (PRI historically), Sweden (Social Democrats historically)." },
  { term:"Two-Party System", cat:"Parties & Systems", def:"A system in which only two major political parties have a realistic chance of holding power.", hint:"E.g., USA. Often a product of FPTP electoral rules + Duverger's Law." },
  { term:"Multi-Party System", cat:"Parties & Systems", def:"A system in which more than two parties have a realistic chance of holding power.", hint:"E.g., Germany, Netherlands, Israel. Common under proportional representation." },
  { term:"Effective Number of Parties (ENP)", cat:"Parties & Systems", def:"A measure that captures both the number AND the support of parties in a country, weighting larger parties more heavily than smaller ones. Formula: 1 ÷ Σ(each party's vote share²).", hint:"10 tiny parties ≠ 10-party system. A country with two 50% parties has ENP = 2; a country with one 80% and one 20% party has ENP ≈ 1.47." },
  { term:"Reinforcing Cleavages", cat:"Parties & Systems", def:"Multiple social divisions (class, religion, ethnicity) line up — the same people are on the same side on every issue.", hint:"Creates strong, stable, polarized parties — but more conflict." },
  { term:"Cross-Cutting Cleavages", cat:"Parties & Systems", def:"Social divisions cut across each other — a person may be working-class AND religiously conservative AND an ethnic minority.", hint:"Moderate political conflict; people have cross-pressured loyalties." },
  { term:"Duverger's Law", cat:"Parties & Systems", def:"FPTP / majoritarian systems (district magnitude = 1) tend to produce two-party systems; proportional representation tends to allow multi-party systems. Majoritarian systems favor larger, geographically concentrated parties; PR allows smaller, geographically diffuse parties.", hint:"Mechanism: strategic voting + party entry decisions under FPTP squeeze out third parties." },
  { term:"Party System Institutionalization", cat:"Parties & Systems", def:"The degree to which a party system is stable, rooted in society, and follows predictable rules of competition.", hint:"Mainwaring & Scully: 4 dimensions — volatility, societal roots, legitimacy, organization." },
  { term:"Electoral Volatility", cat:"Parties & Systems", def:"The aggregate shift in vote shares between parties across elections. High volatility = unstable party system.", hint:"Pedersen Index = sum of absolute vote share changes ÷ 2." },
  { term:"Electoral Integrity", cat:"Parties & Systems", def:"The extent to which elections conform to international norms: free, fair, transparent, competitive, free from fraud/violence.", hint:"Measured via expert surveys, forensic stats, observed anomalies." },
];

const ESSAYS = [
  { q:"Under what conditions might a citizen use Voice vs. Exit vs. Loyalty?", hint:"Voice: when exit is costly, loyalty is moderate, voice feels effective.\nExit: when alternatives exist, cost of leaving is low, voice seems futile.\nLoyalty: when attachment is high, exit isn't feasible, hope remains.\nKey driver: credibility of the exit option." },
  { q:"What is the collective action dilemma? Why does it predict low individual participation?", hint:"Each individual's contribution is too small to matter alone → rational to free-ride.\nBut if everyone free-rides → collective good (political change) is not provided.\nSolution: selective incentives, social pressure, expressive benefits." },
  { q:"Why do people bother to vote at all?", hint:"1. Civic duty / expressive voting\n2. Social pressure / norms\n3. Selective incentives (party mobilization)\n4. Close elections raise perceived impact\n5. Low cost of voting (habits, proximity)\n6. Partisan identity drives turnout" },
  { q:"Why is SES often positively correlated with political participation?", hint:"Higher SES → more resources (time, money, civic skills), more political information, more policy stakes, more party mobilization." },
  { q:"Under what conditions might SES NOT be positively correlated with participation?", hint:"Authoritarian contexts: poor mobilized by clientelism or fear.\nStrong ethnic/communal mobilization: identity overrides class.\nExtreme grievance: high-intensity movements mobilize low-SES groups.\nInverse: wealthy exit (private solutions) rather than engage politically." },
  { q:"What does ethnic diversity suggest for democratic politics?", hint:"Not deterministic. Problems arise IF: reinforcing cleavages, ethnicity is politicized, weak institutions.\nLess damaging when: cross-cutting cleavages, constructivist fluidity, strong party systems.\nEthnic fractionalization alone doesn't predict democratic breakdown." },
  { q:"What evidence suggests partisanship is a social identity rather than a rational running tally?", hint:"Stability across dramatic party policy shifts.\nAffective polarization beyond policy disagreement.\nParty preference precedes policy views (not the reverse).\nIntermarriage preferences, social sorting by party." },
  { q:"Why do some countries have more parties than others?", hint:"1. Electoral system: PR → more parties (Duverger's Law)\n2. Social cleavages: more distinct groups → more parties\n3. Low legal thresholds\n4. Federalism: regional parties viable\n5. Historical path dependence" },
  { q:"How would you assess whether a country has high party system institutionalization?", hint:"1. Low electoral volatility (stable vote shares)\n2. Parties have roots in society (not just leader vehicles)\n3. Parties seen as legitimate actors\n4. Parties have strong internal organizations\n(Mainwaring & Scully's 4 dimensions)" },
  { q:"Why is electoral fraud difficult to measure?", hint:"It's hidden by definition. Methods: expert surveys (PEI), digit-based forensics (Benford's Law), turnout anomalies, precinct-level outliers, satellite imagery, observer reports.\nLimitation: forensic stats produce false positives; surveys are subjective." },
];

/* ---------------------------------------------------------
   ESSAY_MC — one multiple-choice question per essay prompt.
   Each tests the key argument of that essay. Use for Learn
   "essay concepts" mode and for Hard quiz difficulty.
   --------------------------------------------------------- */
const ESSAY_MC = [
  { topic:"Voice / Exit / Loyalty",
    q:"A citizen living under a regime with closed borders and rigged elections, but who is deeply attached to the nation, is most likely (per Hirschman) to:",
    opts:["Exit — emigrate quietly","Use voice — protest and organize from within","Stay loyal and politically disengage","Engage in strategic voting"],
    correct:1,
    explain:"When exit is blocked and loyalty is high, voice becomes the primary channel for dissent — the credibility of the exit option is the key driver." },
  { topic:"Collective action dilemma",
    q:"Olson's collective action model predicts individual voter turnout should be near zero because:",
    opts:["Voting is usually illegal","Each individual vote rarely decides the election, so rational actors free-ride","Polling places are inaccessible","Citizens cannot tell candidates apart"],
    correct:1,
    explain:"Rational-choice logic: one vote almost never flips an election, so contributing is individually irrational even if everyone benefits from political outcomes." },
  { topic:"Why people vote anyway",
    q:"Which of the following is NOT a standard resolution of the paradox of voting?",
    opts:["Civic duty and expressive voting","Selective incentives from party mobilization","Partisan identity making voting feel intrinsic","Rational calculation that one's own vote will decide the outcome"],
    correct:3,
    explain:"The decisive-vote calculation predicts turnout near zero; the other three (duty, mobilization, identity) are the accepted work-arounds." },
  { topic:"SES and participation",
    q:"The standard positive correlation between socioeconomic status and political participation is usually explained by:",
    opts:["Legal requirements that target wealthy citizens","Higher-SES citizens having more time, civic skills, information, and mobilization contact","Parties banning low-income voters","Mandatory voting in wealthy neighborhoods"],
    correct:1,
    explain:"SES bundles together resources (time, money), civic skills, political information, and exposure to mobilization — all of which raise the likelihood of participation." },
  { topic:"When SES breaks down",
    q:"In which context is the usual positive SES–participation correlation most likely to break down?",
    opts:["A consolidated democracy with high literacy","A clientelistic regime where poor voters are mobilized by patronage","A two-party FPTP system","A proportional-representation system with low thresholds"],
    correct:1,
    explain:"Clientelism mobilizes low-SES voters directly through patronage/vote-buying, often producing equal or higher turnout among the poor." },
  { topic:"Ethnic diversity & democracy",
    q:"Ethnic diversity is most likely to threaten democratic stability when:",
    opts:["Cleavages cross-cut each other","Identities are fluid and constructivist","Cleavages reinforce AND elites politicize ethnicity","Ethnic fractionalization is very low"],
    correct:2,
    explain:"The danger comes from reinforcing cleavages (same groups on the same side of every issue) combined with elite mobilization along ethnic lines — diversity alone isn't destabilizing." },
  { topic:"Partisanship as identity",
    q:"The strongest evidence that partisanship is a social identity (Green/Palmquist/Schickler) rather than a rational running tally (Fiorina) is:",
    opts:["Voters carefully re-weight their party ID each election","Party ID remains stable even when parties make dramatic policy shifts","Voters only identify with whichever party holds power","Partisanship vanishes in polarized environments"],
    correct:1,
    explain:"A rational tally would swing with policy shifts; its stickiness despite major shifts points to identity — like team loyalty." },
  { topic:"Duverger's Law",
    q:"Duverger's Law predicts that:",
    opts:["All democracies converge on two parties","FPTP rules tend toward two parties; PR tends toward multiparty systems","PR always yields a single dominant party","Electoral rules have no effect on party systems"],
    correct:1,
    explain:"FPTP squeezes out third parties via strategic voting and entry costs; PR lets small parties win seats, producing multiparty systems." },
  { topic:"Party system institutionalization",
    q:"Which is NOT one of Mainwaring & Scully's four dimensions of party-system institutionalization?",
    opts:["Low electoral volatility","Parties rooted in society","Parties seen as legitimate actors","Parties funded primarily by the state"],
    correct:3,
    explain:"The four dimensions are: low volatility, societal roots, legitimacy, and strong party organizations — not source of funding." },
  { topic:"Measuring electoral fraud",
    q:"Why is electoral fraud hard to measure directly?",
    opts:["Fraud is fully transparent and easily quantified","Fraud is hidden by nature, so analysts rely on indirect forensic methods and expert surveys","International observers always catch every fraudulent vote","Governments publish detailed fraud reports routinely"],
    correct:1,
    explain:"Because fraud is hidden, researchers triangulate: expert surveys (PEI), Benford's-Law digit forensics, turnout anomalies, precinct-level outliers, observer reports — each with error bars." },
];
