/* =========================================================
   1Z0-1080-25 — Oracle Planning 2025 Implementation Professional
   v2 expanded: CARDS (106) · ESSAYS (19) · ESSAY_MC (34) · EXAM_Q (36)
   CARDS (33) · ESSAYS (10) · ESSAY_MC (10) · EXAM_Q (8)
   Categories:
     "Application Setup"   — Planning overview, dims, metadata/data, security
     "Content & Rules"     — Forms/dashboards/navflows, rules, reports
     "Modules"             — Financials, Workforce, Capital, Projects, Strategic Modeling
     "Operations"          — Maintenance, IPM, Approvals
   ========================================================= */

const CARDS = [
  /* ---------------- Application Setup (8) ---------------- */
  { term:"Planning Application",
    cat:"Application Setup",
    def:"An Oracle Cloud EPM application built on Essbase cubes that supports budgeting, forecasting, and what-if analysis across standard business processes or Custom modules.",
    hint:"Created from Planning or FreeForm; stored in EPM Cloud." },
  { term:"FreeForm Application",
    cat:"Application Setup",
    def:"A flexible Planning application type that lets you define your own cubes and dimensions without enabling the pre-built modules (Financials, Workforce, etc.).",
    hint:"Pick this when you don't want the module content; you design dims yourself." },
  { term:"Required Dimension",
    cat:"Application Setup",
    def:"A dimension that every Planning application must contain: Account, Period, Year, Scenario, Version, and Entity (plus Currency when multicurrency is enabled).",
    hint:"Six required dims; Currency is added automatically when multicurrency is on." },
  { term:"User-Defined Dimension",
    cat:"Application Setup",
    def:"A custom dimension you add to model business-specific analysis (Product, Market, Department, etc.). Up to the Essbase cube's dimension limits.",
    hint:"Added after required dims; drives custom analysis in BSO/ASO cubes." },
  { term:"Dimension Hierarchy",
    cat:"Application Setup",
    def:"The parent-child tree structure of a dimension that controls aggregation. Base members hold data; upper-level members roll up via consolidation operators (+, -, ~, ^).",
    hint:"Tilde (~) = don't consolidate; caret (^) = never consolidate." },
  { term:"Valid Intersection",
    cat:"Application Setup",
    def:"A rule that restricts which cell combinations across dimensions can accept or display data, enforcing that only meaningful intersections are visible.",
    hint:"Example: Capex accounts only valid for Capital entities." },
  { term:"Cell-Level Security",
    cat:"Application Setup",
    def:"Security applied at specific dimension intersections to hide or restrict data, in addition to artifact-level access, using member combinations.",
    hint:"Finer-grained than Read/Write on a form — targets cells, not artifacts." },
  { term:"Data Map",
    cat:"Application Setup",
    def:"An EPM Cloud feature that pushes data from one cube or application to another by mapping source and target dimensions, including smart pushes from forms.",
    hint:"Used to move data between Plan Types or apps; supports Smart Push on save." },
  { term:"Data Integration",
    cat:"Application Setup",
    def:"The EPM Cloud tool (formerly Data Management) that imports/exports data with mapping rules, dimension mapping, drill-through, and scheduled jobs.",
    hint:"Replaces legacy Data Management; supports file, direct, and connected integrations." },

  /* ---------------- Application Setup cont. — Security (2) ---------------- */
  { term:"Security Provisioning",
    cat:"Application Setup",
    def:"Assigning predefined roles (Service Administrator, Power User, User, Viewer) to users or groups at the application level to control what features they can use.",
    hint:"Roles are hierarchical: Service Administrator > Power User > User > Viewer." },
  { term:"Access Permissions",
    cat:"Application Setup",
    def:"Read / Write / None / Deny permissions assigned to members, forms, rules, and other artifacts, granted to users or groups and evaluated with None overriding Write.",
    hint:"Union of group rights, but Deny (None) always wins over Write." },

  /* ---------------- Content & Rules (8) ---------------- */
  { term:"Data Form",
    cat:"Content & Rules",
    def:"A grid-based input and analysis surface where planners enter, view, and analyze data. Point-of-view and page dimensions define context; rows/columns show members.",
    hint:"Simple forms = single layout; composite forms embed multiple forms together." },
  { term:"Composite Form",
    cat:"Content & Rules",
    def:"A form that combines multiple simple forms into one layout so users can see and update related data side-by-side with shared POVs where applicable.",
    hint:"Useful for master-detail entry; saves navigation between forms." },
  { term:"Dashboard",
    cat:"Content & Rules",
    def:"A visual layout that combines charts, grids, forms, and commentary to summarize planning data. Supports drill-down, interactive filters, and global POVs.",
    hint:"Dashboard 2.0 is the modern engine with richer charts and layout control." },
  { term:"Navigation Flow",
    cat:"Content & Rules",
    def:"A configurable UI path with cluster cards, tabs, and sub-tabs that customizes the user experience per role or group, hiding artifacts not relevant to them.",
    hint:"Role-scoped flows simplify the interface for end users." },
  { term:"Validation Rule (Data Validation)",
    cat:"Content & Rules",
    def:"A conditional rule on a form cell or row that turns cells red / green or enforces approval when values fail a business condition (variance > threshold, negative, etc.).",
    hint:"Drives visual alerts and can block promotion in the approval cycle." },
  { term:"Business Rule",
    cat:"Content & Rules",
    def:"A scripted Essbase calculation that allocates, aggregates, or derives data. Built in Calculation Manager with prompts, variables, and template support.",
    hint:"Two languages: Calc Script (classic) and Groovy (modern, data-aware)." },
  { term:"Groovy Rule",
    cat:"Content & Rules",
    def:"A Java-based scripting rule type that can inspect the edited form cells, call REST APIs, loop, and run targeted calcs — far more flexible than Calc Script.",
    hint:"Data-aware: only operates on changed cells → big performance win." },
  { term:"Ruleset",
    cat:"Content & Rules",
    def:"An ordered collection of business rules that execute sequentially, optionally sharing prompts so the user enters them only once for the whole set.",
    hint:"Merge prompts flag consolidates identical runtime prompts." },

  /* ---------------- Reports (1) ---------------- */
  { term:"Reports (Narrative Reporting)",
    cat:"Content & Rules",
    def:"The modern cloud reporting tool for Planning that replaces Financial Reporting. Supports pixel-perfect books, bursting, and embedded grids from Planning or other EPM sources.",
    hint:"Replaces classic 'Financial Reports'; bursting sends per-entity PDFs." },

  /* ---------------- Modules (8) ---------------- */
  { term:"Financials Module",
    cat:"Modules",
    def:"A pre-built Planning framework for income statement, balance sheet, and cash flow planning, with templates for direct or indirect method and driver-based revenue/expense planning.",
    hint:"Enable at creation; configure features granularly (Revenue, Expense, BS, CF)." },
  { term:"Workforce Module",
    cat:"Modules",
    def:"A pre-built module for headcount, salary, compensation, and benefits planning. Supports employee-only, job-only, or combined employee+job planning.",
    hint:"Assumptions drive benefits/taxes/merit; you can update many employees at once." },
  { term:"Capital Module",
    cat:"Modules",
    def:"A pre-built module for planning capital assets — tangible assets, intangibles, and leases — including depreciation/amortization, transfers, retirements, and funding.",
    hint:"Tracks asset lifecycle and feeds balance sheet and cash flow in Financials." },
  { term:"Projects Module",
    cat:"Modules",
    def:"A pre-built module for contract, indirect, and capital projects planning — revenue, expense, milestones, resources, and rollup to the enterprise plan.",
    hint:"Supports Contract, Capital, and Indirect project types." },
  { term:"Strategic Modeling",
    cat:"Modules",
    def:"A long-range financial modeling module (separate from the Planning cube) for what-if scenarios, M&A analysis, and multi-year forecasts. Built on the Strategic Model engine.",
    hint:"Not an Essbase cube; uses its own model structure and simulation engine." },
  { term:"Module Integration",
    cat:"Modules",
    def:"Pre-configured data pushes between modules (e.g., Workforce salary → Financials P&L, Capital depreciation → Financials) so changes in one module flow automatically.",
    hint:"Set up via configurable integrations on each module's configure card." },
  { term:"Configure Task",
    cat:"Modules",
    def:"The per-module card in the Application > Configure page where administrators enable features, set defaults, import mappings, and drive dimension configuration.",
    hint:"One Configure card per enabled module; run in a recommended order." },
  { term:"Best Practice — Enable Only What You Need",
    cat:"Modules",
    def:"Oracle's guidance to enable module features incrementally so unused artifacts and dimensions don't bloat the app or confuse users; features can be added later.",
    hint:"Disabled features can still be enabled later — start minimal." },

  /* ---------------- Operations (3) ---------------- */
  { term:"EPM Automate",
    cat:"Operations",
    def:"A command-line utility for scripting EPM Cloud administration — backups, data/metadata loads, rules, user provisioning, and daily maintenance window tasks.",
    hint:"Used for scheduled jobs, CI/CD, and migrations between pods." },
  { term:"Daily Maintenance Window",
    cat:"Operations",
    def:"A nightly service-initiated window in which Oracle backs up the service and applies patches. Admins can shift the start time; it's required and cannot be skipped.",
    hint:"You pick the start hour; backups live in the Inbox/Outbox for 60 days." },
  { term:"Intelligent Performance Management (IPM)",
    cat:"Operations",
    def:"An EPM Cloud feature set combining Predictive Planning, IPM Insights, and auto-predict that surfaces anomalies and forecasts using built-in ML on Planning data.",
    hint:"ML-driven: detects bias, variance patterns, and suggests forecast values." },
  { term:"Approval Unit",
    cat:"Operations",
    def:"The basic object in the approval process — typically an intersection of Entity, Scenario, and Version (and sometimes a user-defined dim) that flows through a review cycle.",
    hint:"Hierarchy + Scenario + Version = one approval unit path." },
  { term:"Approval Unit Hierarchy",
    cat:"Operations",
    def:"The approval path defined over a primary dimension (usually Entity) that determines which users own, review, and approve each node, with optional bottom-up or distribute start.",
    hint:"Two start modes: Bottom-up (promote) and Distribute (delegate down)." },

  /* ---------------- Application Setup — expansion (10) ---------------- */
  { term:"BSO (Block Storage Option)",
    cat:"Application Setup",
    def:"An Essbase cube type used as the Input cube in Planning. Planners enter data here, and business rules / calc scripts execute against it.",
    hint:"Write-back + rule execution happens in BSO, not ASO." },
  { term:"ASO (Aggregate Storage Option)",
    cat:"Application Setup",
    def:"An Essbase cube type used as the Reporting cube. Built for huge volumes and fast queries; does not run calc scripts and planners do not input here.",
    hint:"Read-heavy reporting; no business rules; used for bursting and large reports." },
  { term:"Essbase",
    cat:"Application Setup",
    def:"The multi-dimensional OLAP database engine underlying Planning. Both BSO (input) and ASO (reporting) cubes are Essbase cube types.",
    hint:"Think 'the database under the hood' — Planning sits on top of Essbase." },
  { term:"Hybrid Essbase",
    cat:"Application Setup",
    def:"An Essbase mode that blends BSO and ASO behavior — BSO block structure with on-the-fly aggregation like ASO. Default for EPM Standard / Enterprise and required for 13-period calendars and Budget Revisions.",
    hint:"Required for: 13-period calendars and Budget Revisions." },
  { term:"Module Artifact Prefix",
    cat:"Application Setup",
    def:"The two-or-three-letter prefix on predefined artifact names that identifies the owning module. Custom artifact names are NOT allowed to use these prefixes.",
    hint:"OEP_ = common · OFS_ = Financials · OWP_ = Workforce · OPF_ = Projects · OCX_ = Capital." },
  { term:"Refresh Database",
    cat:"Application Setup",
    def:"The action that pushes outline changes (added/removed members, renamed dims, updated properties) from the Planning metadata into the Essbase cube. Must be run after any metadata change.",
    hint:"Actions menu → Refresh Database. Forgetting this is a classic 'why is my member missing' bug." },
  { term:"User Variable",
    cat:"Application Setup",
    def:"A per-planner saved selection for a dimension (e.g., their Entity, Scenario, Version, Years, Reporting Currency) set in Tools → User Preferences. Forms reference user variables to auto-scope the POV.",
    hint:"Every planner must set these before entering data — otherwise forms are empty or broken." },
  { term:"Getting Started Checklist",
    cat:"Application Setup",
    def:"The exam-tested ordered sequence for standing up a Planning Modules app: create app → add currencies → review integrations → enable features → configure + run rules → refresh DB → set user variables → import data → provision users → set rule security → design reports → publish to planners → define approvals → map data between modules.",
    hint:"Order matters — enable features is locked once done; refresh DB comes after every metadata change." },
  { term:"Enable Features",
    cat:"Application Setup",
    def:"The per-module step where the Service Administrator turns on specific module capabilities (e.g., Workforce granularity, Financials revenue/expense/BS/CF). Puts the app into maintenance mode and, once enabled, features can only be added, not removed.",
    hint:"Start minimal — you can add later, but you can't turn features off." },
  { term:"Alias Table",
    cat:"Application Setup",
    def:"A Planning mechanism for giving each dimension member alternate display names (e.g., per language). Up to 32 total; one is used internally, leaving 31 usable.",
    hint:"32 max · 1 internal · 31 usable." },

  /* ---------------- Content & Rules — expansion (4) ---------------- */
  { term:"Smart Push",
    cat:"Content & Rules",
    def:"A Data Map triggered by saving a form — pushes the affected slice to a target cube automatically. Same mechanism as Data Map, different activation.",
    hint:"'Data Map + form save = Smart Push.' Fastest way to keep a target cube in sync while users plan." },
  { term:"Calculation Manager",
    cat:"Content & Rules",
    def:"The graphical authoring tool for business rules, rulesets, templates, and Groovy rules. Lets admins build flow-chart style calculations with components, prompts, variables, and error handling.",
    hint:"Home → Rules → Create/Edit opens Calculation Manager." },
  { term:"Calc Script (Classic Rule)",
    cat:"Content & Rules",
    def:"The traditional Essbase scripting language used for business rules — declarative FIX/ENDFIX blocks, formulas, and calc functions. Runs across every cell in its FIX scope, not just edited cells.",
    hint:"Calc Script recalculates every cell in scope — use Groovy when you only want edited cells." },
  { term:"Substitution Variable",
    cat:"Content & Rules",
    def:"A named placeholder (e.g., &CurrMonth, &CurrYear) maintained at the application level and referenced inside forms, rules, and jobs. Lets you move 'the current period' forward in one place without editing every artifact.",
    hint:"Update once → every artifact using it shifts. Common for rolling forecasts." },

  /* ---------------- Modules — expansion (13) ---------------- */
  { term:"Workforce Granularity",
    cat:"Modules",
    def:"The level at which Workforce plans compensation. Pick exactly one when first enabling the module: Employee only, Job only, or Employee + Job. Choice is locked after first enable.",
    hint:"Employee+Job = per-employee comp with job linkage. Pick before your first Enable Features." },
  { term:"Benefits and Taxes Wizard",
    cat:"Modules",
    def:"The Workforce wizard that configures each Component through Details → Rates → Review screens. Prerequisite: you MUST import members into the Component dimension (and configure Options and Tiers) on the Configure page before launching.",
    hint:"Import Component members FIRST — this prerequisite is on every exam." },
  { term:"Component Dimension (Workforce)",
    cat:"Modules",
    def:"The Workforce dimension that holds individual Additional Earnings, Benefits, and Taxes members. Max 30 members total across these three categories.",
    hint:"Import members here before launching the Benefits and Taxes Wizard." },
  { term:"Merit-Based Planning",
    cat:"Modules",
    def:"A Workforce option that applies a merit-rate increase to salary. Requires Employee or Employee + Job granularity. Assumptions set Global or Per-Entity; include Merit Month, Cut-off Date, and a Default Merit Rate for new hires.",
    hint:"Run Process Loaded Data after updating merit assumptions to sync at employee level." },
  { term:"Flexible Account Mapping",
    cat:"Modules",
    def:"A Workforce feature that lets you map Salary and Merit to any Financials account (not just OFS_Salaries). Mapping can be Global or per-Entity; drivers are Grade or Defaults.",
    hint:"Enable when a client wants Workforce comp to land in their own chart of accounts." },
  { term:"Split-Funded FTE",
    cat:"Modules",
    def:"A Workforce feature that splits an FTE's cost across multiple sparse dimensions (cost center, entity, project). Requires Employee or Employee+Job granularity and a Master FTE Value entered on Employee Master Data form (stored in OEP_Home Entity).",
    hint:"If Master FTE changes, run Synchronize Definition to recalculate." },
  { term:"Project Types",
    cat:"Modules",
    def:"The three project categories in the Projects module: Contract (external, revenue-bearing), Indirect (internal, no revenue), and Capital (projects that produce a capitalized asset).",
    hint:"Contract · Indirect · Capital. Project Benefits only apply to Indirect and Capital." },
  { term:"Resource Classes",
    cat:"Modules",
    def:"The three revenue/expense assumption types in Projects: Labor (FTEs, hours, rates — can pull from Workforce), Equipment (units, rates — can pull from Capital), and Material (unit costs × quantity).",
    hint:"Labor · Equipment · Material. NOT overhead, funding, or milestones." },
  { term:"Project Benefits",
    cat:"Modules",
    def:"Projects feature (Indirect and Capital only) for tracking financial benefits ($), non-financial benefits (CSAT, user growth), and qualitative benefits used to justify the project.",
    hint:"Not available on Contract projects — those are already revenue-bearing." },
  { term:"Project Management Cloud Integration",
    cat:"Modules",
    def:"Bidirectional integration between EPM Planning Projects and Oracle Project Management (ERP). Supports Indirect and Capital projects only. Requires Hybrid Essbase; uses a 12-period calendar (monthly, 4-4-5, 5-4-4, or 4-5-4 — NOT 4-4-4) and MM/DD/YY date format. Only actual costs transfer; budget validation by total amount only.",
    hint:"Indirect + Capital only. Three jobs: Export Projects & Budgets · Import Project Actuals · Import Projects & Budgets (one-time)." },
  { term:"Custom Depreciation Methods",
    cat:"Modules",
    def:"Capital module capability to define depreciation or amortization methods beyond the built-in straight-line, declining balance, etc. Configured post-enable on the Capital Configure page.",
    hint:"Built-in methods cover most cases; use Custom for non-standard schedules." },
  { term:"Budget Revisions",
    cat:"Modules",
    def:"A specialized Financials feature that integrates with Oracle ERP Cloud Budgetary Control. Requires Hybrid Essbase, single currency, and your own chart of accounts. Adds Scenario OEP_Adopted Budget (and optional OEP_Consumed). Max 30 active revisions.",
    hint:"Control Budget Source Type in ERP Cloud must be 'EPM Financials module' — NOT 'Hyperion Planning'." },
  { term:"Chart of Accounts Choice (Financials)",
    cat:"Modules",
    def:"When enabling Financials, the admin picks between using Oracle's provided chart of accounts (enables driver-based planning + full predefined dashboards) or 'Use your own COA' (direct + trend planning; to reuse provided dashboards, add accounts as shared members under OFS_Total Revenue / Cost of Sales / OpEx / Cash).",
    hint:"Provided COA = fastest path; Own COA = more work but matches your real GL." },

  /* ---------------- Operations — expansion (8) ---------------- */
  { term:"Predictive Planning",
    cat:"Operations",
    def:"An IPM component that fits time-series forecast models (ETS, ARIMA, seasonal variants) to historical Planning data and writes predicted values to a target scenario/version. Available with EPM Enterprise.",
    hint:"Pick historical range → model auto-selected → predictions written to a target Scenario/Version." },
  { term:"AutoPredict",
    cat:"Operations",
    def:"IPM feature that schedules Predictive Planning jobs so forecasts auto-refresh when historical data loads. Available with EPM Enterprise AND with Planning in EPM Standard — the one IPM feature in Standard.",
    hint:"Only IPM feature included in EPM Standard. Everything else in IPM needs Enterprise." },
  { term:"IPM Insights",
    cat:"Operations",
    def:"An IPM component that scans Planning data for anomalies, forecast bias, and variance patterns, then surfaces them as cards for admins and planners to review.",
    hint:"ML-driven anomaly detection over Planning data — shows up in the Insights panel." },
  { term:"Bring Your Own ML (PMML Import)",
    cat:"Operations",
    def:"An IPM workflow where a data scientist trains a model externally (scikit-learn, R, Oracle Data Science) and exports it as a PMML file. An EPM admin imports the PMML, maps its input fields to Planning dimensions, and deploys it — Planning auto-generates the Groovy rules to call it.",
    hint:"Data scientist exports a .pmml → admin imports → maps inputs → deploy. PMML file must exist BEFORE the admin imports." },
  { term:"Permission Priority (Deny > None > Write > Read)",
    cat:"Operations",
    def:"The rule for evaluating conflicting access across groups, inheritance, and artifacts: Deny always wins, then None, then Write, then Read. The classic exam trap is 'Write + None = None'.",
    hint:"Closest member overrides parent; Deny always wins; None beats Write." },
  { term:"Clone Snapshot",
    cat:"Operations",
    def:"A service-admin feature that produces an exact copy of an application in a target environment — it exports the source snapshot, deletes the target's current app and data, and imports the snapshot in one end-to-end run.",
    hint:"Different from Migration Export (artifacts only) and Migration Backup (recovery file only)." },
  { term:"Scheduled Job",
    cat:"Operations",
    def:"A job configured under Home → Application → Jobs. Job types include Refresh Database, Clear Cube, Run Business Rule / Ruleset, Import / Export Data / Metadata, Run Data Rule, Smart Push, Data Map. Supports substitution variables and daily/weekly/monthly/on-demand schedules.",
    hint:"Get email on completion. Running jobs can't be deleted until they finish." },
  { term:"EPM Automate Top Commands",
    cat:"Operations",
    def:"The CLI commands most tested on the exam: runBusinessRule, importMetadata, importData / exportData, runDataRule, uploadFile / downloadFile, runDailyMaintenance, downloadSnapshot, login / logout.",
    hint:"Nightly backup pattern: login → runDailyMaintenance → downloadSnapshot → logout." },

  /* ---------------- v2 expansion — Application Setup / Dimensions (7) ---------------- */
  { term:"Consolidation Operators (+ − ~ ^)",
    cat:"Application Setup",
    def:"The four operators that control how a child rolls up to its parent in a dimension tree: + add (default), − subtract, ~ ignore in consolidation (data stored but not rolled up), ^ never consolidate (excluded from all aggregations).",
    hint:"~ stores but doesn't roll up · ^ never rolls up anywhere." },
  { term:"Attribute Dimension",
    cat:"Application Setup",
    def:"A non-aggregating dimension that tags members of a base dimension with extra properties (e.g., Employee gender, Asset color, Account currency). Used for filtering and analysis, not aggregation.",
    hint:"Tags, don't aggregate. Do NOT count the same way as base/custom dims for 'Does Projects support this' type questions." },
  { term:"Smart List",
    cat:"Application Setup",
    def:"A drop-down of text values applied to a cell (not a full dimension). Examples: Pay Type, Project Template, Control Budget Name. Lightweight way to constrain input without spinning up a dim.",
    hint:"Drop-downs on cells — e.g., Pay Type, Control Budget Name." },
  { term:"Fiscal Year Start Date (FY Anchor)",
    cat:"Application Setup",
    def:"The setting that determines whether FY<N> starts in calendar year <N> or the previous calendar year. 'Same Calendar Year' → FY25 = Jul-2025 to Jun-2026. 'Previous Calendar Year' → FY25 = Jul-2024 to Jun-2025. Only shown when First Month ≠ January.",
    hint:"Same CY → FY starts in that CY · Previous CY → FY starts in the CY before." },
  { term:"Dimension Limits (32 · 32 · 3 or 5)",
    cat:"Application Setup",
    def:"Planning Modules limits: max 32 total dimensions (base + custom + attribute), max 32 alias tables (1 internal → 31 usable), max 3 custom dimensions per module (Financials allows up to 5).",
    hint:"32 dims · 31 usable aliases · 3 custom (Fin: 5)." },
  { term:"Things Locked at Creation",
    cat:"Application Setup",
    def:"Settings that CANNOT be changed after app creation: Input cube name, Reporting cube name, 12-month vs 13-period calendar, Weeks-to-months mapping (4-4-5 / 4-5-4 / 5-4-4), First Month of Fiscal Year (mostly), Multicurrency once enabled, Features (can add, cannot disable), Workforce Employee Demographics (must pick on first enable), 53-Week Planning once enabled, Workforce granularity mapping dims, Task Flow type.",
    hint:"Cube names, calendar shape, weeks-to-months, multicurrency, 53-week, Employee Demographics — all locked." },
  { term:"Never Share Storage (Account / Period)",
    cat:"Application Setup",
    def:"A validation rule that fires when 'Enable Features' is clicked: the Account and Period dimensions' data storage property MUST be set to Never Share, and the Year dimension must NOT be Dynamic Calc. Violations block enablement.",
    hint:"Account + Period = Never Share · Years ≠ Dynamic Calc." },

  /* ---------------- v2 expansion — Financials (6) ---------------- */
  { term:"Plan Element Dimension (Financials)",
    cat:"Modules",
    def:"A Financials-only dimension that classifies what kind of value a cell holds: Total: Calculated (driver aggregates), Total Adjust (planner overrides), Load (imported actuals), Direct Entry (manual plan), Cash Flow Impact, Cash Flow Calculated (payment-term spreads like 50/40/10), Cash Flow Reporting (Direct method only).",
    hint:"Tells you HOW the number got there — calc, override, load, direct, or cash-flow spread." },
  { term:"Rolling Forecast Scenario",
    cat:"Modules",
    def:"A Financials-only feature that adds the OEP_Rolling Forecast scenario and auto-advances the forecast window as the current period moves. Adds KPI scenarios OEP_TTM (Trailing 12 Months) and Projected 12. Weekly currency conversion is BSO-only.",
    hint:"Keeps 'the next N months' always in view — forms auto-add/drop periods." },
  { term:"Cash Flow Methods (Direct vs Indirect)",
    cat:"Modules",
    def:"Direct Cash Flow derives cash from sources/uses and requires Revenue and/or Expense enabled. Indirect Cash Flow derives cash from Operating/Investing/Financing activities and requires Income Statement + Balance Sheet enabled. Only two options — no third method.",
    hint:"Direct needs Rev/Exp · Indirect needs IS + BS. That's it, 2 methods." },
  { term:"53-Week Planning",
    cat:"Modules",
    def:"A Financials feature for 12-month apps with weekly distribution that handles the extra 53rd week that shows up every ~4–5 years. Cannot be disabled once enabled.",
    hint:"Once on, it stays on. Plan for it." },
  { term:"Weekly Planning Mechanics",
    cat:"Modules",
    def:"When Weekly Planning is enabled in Financials, the weeks-to-months mapping (4-4-5 / 4-5-4 / 5-4-4) is LOCKED. Monthly exchange rates auto-spread to weeks per that mapping — Financials (OEP_FS) cube only, BSO only. Run Convert Weekly Data to Monthly (or the reverse) BEFORE Prepare Plan / Forecast / Rolling Forecast.",
    hint:"Mapping is locked at enable. BSO-only weekly currency conversion. Convert BEFORE prep rules." },
  { term:"Funds Check vs Funds Reserve",
    cat:"Modules",
    def:"Budget Revisions rules that call ERP Cloud Budgetary Control. Funds Check validates a proposed revision against the Control Budget (read-only check). Funds Reserve commits: it reserves the delta in Budgetary Control, pushes delta to Adopted Budget Working, and CLEARS the revision so the slot can be reused.",
    hint:"Funds Check = validate · Funds Reserve = commit + clear revision." },

  /* ---------------- v2 expansion — Workforce (7) ---------------- */
  { term:"Workforce Component Types",
    cat:"Modules",
    def:"The four Component shape options in the B&T Wizard: Simple (one rate, no options/tiers), Rate Table (multiple rate options, no thresholds), Rate Table and Threshold (multiple options + thresholds — all tiers applied for taxes via Threshold Amount max), Custom (your own calc on OWP_Custom Expense).",
    hint:"Simple · Rate Table · Rate Table + Threshold · Custom. Tiered FICA = Rate Table + Threshold." },
  { term:"Workforce Value Types",
    cat:"Modules",
    def:"How a component's amount is expressed: Flat Amount, % of Salary, % of Overall Earnings (Benefits + Taxes), % of Taxable Earnings (Taxes only), Flat Amount FTE Ratio (Split-Funded FTE), Threshold Amount (Taxes max only — tiered), Threshold Amount FTE Ratio. % Taxable Earnings requires the source component's Taxable Component = Yes.",
    hint:"Flat / %Salary / %Overall / %Taxable / FTE Ratio / Threshold. Match carefully — exam tests valid combinations." },
  { term:"Payment Terms + One-Time Pay",
    cat:"Modules",
    def:"Payment Terms sets frequency: Monthly, Quarterly (Cal/Fiscal), Semiannually (Cal/Fiscal), Annually (Cal/Fiscal). One-Time Pay option pins a component to specific period(s). Example: Semiannually (Cal) + One-Time Pay + Second Month → pays in Feb AND Aug. For 13-period apps, use Monthly — the 13 periods become payment periods.",
    hint:"Frequency + One-Time Pay + which Month anchors the payout window." },
  { term:"Threshold Amount (FICA pattern)",
    cat:"Modules",
    def:"A Max Value Type available ONLY for Taxes. Applies ALL configured tiers regardless of which one is assigned as the default. Classic use: US FICA-style tiered payroll taxes.",
    hint:"Tiered taxes like FICA = Threshold Amount (max value type, Taxes only)." },
  { term:"Workforce Rules 2.0 (24.12+)",
    cat:"Modules",
    def:"The modern auto-FIXPARALLEL rule set replacing the pre-24.12 names: Synchronize Defaults 2.0 (push entity defaults → employee-job), Synchronize Definition 2.0 (push updated component definitions like rate/frequency/grade), Calculate Compensation for All 2.0, Copy Rates Across Entities. Pre-24.12 apps still use Synchronize Defaults, Synchronize Component Definition, Calculate Compensation, Process Loaded Data.",
    hint:"Defaults 2.0 = push entity defaults · Definition 2.0 = push updated component details." },
  { term:"OWP_Custom Template",
    cat:"Modules",
    def:"A blank-script-block Groovy template for Workforce customizations that supports OWP_Change Job, OWP_Transfer, OWP_Transfer In, OWP_Transfer Out. Put your custom logic HERE (not inside the main templates) so Oracle updates don't overwrite it. Common use: carrying custom employee properties (like Hire Date) across transfers and job changes.",
    hint:"Never customize the main OWP_ templates. Always put your code in OWP_Custom Template." },
  { term:"Workforce Default Pairs (by granularity)",
    cat:"Modules",
    def:"The required default dimensions locked at first enable based on granularity: Employee → (Pay Type, Employee Type); Job → (Pay Type, Skill Set); Employee + Job → (Job, Union Code). Choice is permanent for the app.",
    hint:"Employee = Pay Type + Employee Type · Job = Pay Type + Skill Set · Both = Job + Union Code." },

  /* ---------------- v2 expansion — Capital & Projects (5) ---------------- */
  { term:"Capital Asset Types",
    cat:"Modules",
    def:"The three asset categories Capital supports: Tangible (vehicles, IT hardware, buildings, furniture), Intangible (patents, trademarks, copyrights, goodwill — amortized), Leased (IFRS 16 lease accounting).",
    hint:"Tangible · Intangible · Leased. Leased = IFRS 16." },
  { term:"Capital Depreciation Methods",
    cat:"Modules",
    def:"Out-of-the-box methods: Straight Line (SL), Declining Balance Year (DB Year), Declining Balance Period (DB Period), Sum of Years Digits (SOY), and Custom (defined on the Capital Configure page). For DB Year / DB Period, salvage value should be ≥ 1% of basic cost or results may be incorrect.",
    hint:"SL · DB Year · DB Period · SOY · Custom. DB methods want salvage ≥ 1% of cost." },
  { term:"Capital Synchronize Rule",
    cat:"Modules",
    def:"Capital Configure → Actions → Synchronize. Must run: (1) every time a new asset is added, (2) when Capital↔Financials integration mapping changes, (3) when planningyearRange is increased (e.g., FY14:FY15 → FY15:FY24), (4) after transferring assets between departments.",
    hint:"New asset · mapping change · year range extension · transfer → Synchronize." },
  { term:"Capital → Projects Flow",
    cat:"Modules",
    def:"To capitalize project work into assets: enable Projects Capital type (requires Capital module + 'Project' custom dim in Capital) → create a capitalizable project → map project expenses to expense accounts + asset classes (partial/full allocation) → push data to Capital (creates rows in CIP Assets) → set planned in-service date (drives depreciation start).",
    hint:"Capital module first, then add 'Project' dim in Capital, then enable Projects Capital type." },
  { term:"Driver Based vs Direct Input (Projects)",
    cat:"Modules",
    def:"The two Projects planning methods. Direct Input: users type values, no predefined calcs. Driver Based: predefined formulas using standard rates and drivers (e.g., billable FTE × hourly rate). Driver Based is the right pick when revenue/expense depends on rates × quantities.",
    hint:"Direct = manual · Driver Based = formula. Billable resource × rate = Driver Based." },

  /* ---------------- v2 expansion — IPM & Operations (5) ---------------- */
  { term:"IPM Insight Types",
    cat:"Operations",
    def:"Three insight categories IPM surfaces: Forecast Variance & Bias (historical Forecast vs Actuals — reveals systematic over/under-forecasting), Prediction (planner Forecast vs machine Prediction for the future), Anomaly (outliers in historical data — spikes, volatility, missing values).",
    hint:"Variance/Bias = past bias · Prediction = future disagreement · Anomaly = weird history." },
  { term:"PMML File Format",
    cat:"Operations",
    def:"Predictive Model Markup Language — XML-based standard for exchanging trained ML models across tools. Contains model type, input schema, trained parameters, and pre/post-processing — but NOT the training data. Python → sklearn2pmml · R → pmml package. IPM Bring Your Own ML imports .pmml.",
    hint:"XML model exchange format. Portable; doesn't expose training data." },
  { term:"runIntegration (replaces runDataRule)",
    cat:"Operations",
    def:"The current EPM Automate command for Data Integration jobs; runDataRule is deprecated. Supports importMode options (Append, Replace, Map and Validate, No Import, Direct) and exportMode options (Merge, Replace, Accumulate, Subtract, No Export, Check).",
    hint:"runDataRule → runIntegration. Modes let you validate without loading, or accumulate on export." },
  { term:"Snapshot Commands (copySnapshotFromInstance)",
    cat:"Operations",
    def:"EPM Automate snapshot suite: exportSnapshot (create full app backup), importSnapshot (restore), copySnapshotFromInstance (pull a snapshot from another environment — e.g., prod → test), restoreBackup (from automated backups), listBackups.",
    hint:"copySnapshotFromInstance = the cross-env mover. Automates dev/test/prod snapshot promotion." },
  { term:"Service Operations (recreate vs resetService)",
    cat:"Operations",
    def:"Maintenance-level EPM Automate commands: runDailyMaintenance (trigger the window manually), resetService (restart the service, non-destructive), recreate (DESTRUCTIVE — delete and recreate the service), replay (load-test replay), setSubstVars / getSubstVar, setPeriodStatus, userAuditReport, provisionReport.",
    hint:"Reset = restart · Recreate = nuke + rebuild (destructive). Don't confuse them." },

  /* ---------------- v2 expansion — Approvals (4) ---------------- */
  { term:"Approval Templates (Bottom Up · Distribute · Free Form)",
    cat:"Operations",
    def:"Bottom Up: input at leaves, consolidates up; ownership starts at leaf; action = Promote. Distribute: ownership starts at top, distributed down, submitted back up; action = Submit. Free Form: data entered at selected levels; no fixed promotion path; flexible ownership.",
    hint:"Bottom Up → Promote · Distribute → Submit · Free Form → flexible." },
  { term:"Promote vs Submit (exam key)",
    cat:"Operations",
    def:"In the Bottom Up template the action to pass ownership up the hierarchy is PROMOTE (not Submit). In the Distribute template the action to pass it back up is SUBMIT (not Promote). Oracle tests this distinction heavily.",
    hint:"Bottom Up = Promote · Distribute = Submit. Memorize this — it flips in different templates." },
  { term:"Approval Unit States",
    cat:"Operations",
    def:"Not Started (initial — admin runs Start), 1st Pass (Free Form only — open to anyone with write), Under Review (Bottom Up first in path / Distribute last in path), Approved, Rejected (sent back), Signed Off (final, locked), Frozen (data read-only, ownership unchanged).",
    hint:"Not Started → (1st Pass / Under Review) → Approved/Rejected → Signed Off. Frozen = read-only side-state." },
  { term:"Approval Actions (Freeze, Take Ownership, Delegate)",
    cat:"Operations",
    def:"Beyond Promote/Submit/Approve/Reject: Delegate (Bottom Up — pass to a user NOT on the promo path who promotes back), Take Ownership (seize the AU + level-0 descendants from the current owner), Freeze/Unfreeze (lock descendant data read-only without changing ownership), Sign Off (terminal state without transferring), Submit to Top (skip path → top user), Reopen (reopen an approved AU).",
    hint:"Freeze = lock data only · Take Ownership = grab the AU · Delegate = off-path helper." },

  /* ---------------- v2 expansion — Oracle ecosystem & integrations (4) ---------------- */
  { term:"Oracle Four Pillars (ERP · EPM · HCM · CX)",
    cat:"Application Setup",
    def:"Oracle's cloud app families. ERP = run the money (GL/AP/AR/Procurement/Budgetary Control — transactions). EPM = plan the money (budgets, forecasts, what-ifs — aggregated). HCM = manage people. CX = customer-facing (Sales/Service/Marketing).",
    hint:"ERP runs the business. EPM plans it. HCM = people. CX = customers." },
  { term:"ERP → EPM vs EPM → ERP",
    cat:"Application Setup",
    def:"ERP → EPM: actuals flow in (monthly GL transactions via Data Integration with out-of-box ERP Cloud adapter) so planners can do Budget vs Actual. EPM → ERP: approved budgets flow back to ERP's Budgetary Control so ERP can block over-budget transactions — this is exactly what Budget Revisions does.",
    hint:"ERP → EPM = actuals · EPM → ERP = approved budgets (via Budget Revisions)." },
  { term:"HCM → Workforce Integration",
    cat:"Application Setup",
    def:"Data Integration has predefined HCM → Workforce dimension mappings. Typical flow: HR onboards an employee in HCM → overnight sync → the employee appears in Workforce with actual salary, replacing the prior 'New Hire' forecast entry. Workforce → HCM is NOT typical (EPM plans don't create real employees).",
    hint:"HCM is the source of truth; Workforce receives. Out-of-box mappings exist." },
  { term:"Budget Revisions Date Format",
    cat:"Modules",
    def:"When Budget Revisions is enabled, every user's Date Format for Display (Tools → User Preferences → Display) MUST be yyyy-MM-dd. Any other format throws errors on Budget Revisions forms.",
    hint:"BR forms need yyyy-MM-dd. Any other format breaks them." },
];

const ESSAYS = [
  { q:"A client wants to plan revenue, OpEx, capex, and headcount in one application. How would you choose between a Planning app with Modules and a FreeForm app, and what trade-offs matter?",
    hint:"Modules: fastest implementation, pre-built artifacts, standard integrations — but you adopt Oracle's schema.\nFreeForm: total flexibility over dims/cubes — but you build everything from scratch.\nChoose modules for standard processes; FreeForm for niche or highly-custom models.\nHybrid possible: enable some modules + add user-defined dims + Custom module for unique processes." },
  { q:"Explain valid intersections vs cell-level security. When would you use one over the other, and how do they interact with form and member access?",
    hint:"Valid intersections: business-logic filtering (what combinations make sense).\nCell-level security: permission-based filtering (who can see/edit a cell).\nUse valid intersections first to simplify the data model; layer cell security for sensitive intersections (HR comp).\nOrder: member access → artifact access → valid intersections → cell security. Deny wins." },
  { q:"Compare Data Maps and Data Integrations. Which is better for cross-application data movement and why?",
    hint:"Data Map: fast push within same EPM Cloud environment, limited transformation, supports Smart Push.\nData Integration: richer transformations, cross-source imports (ERP Cloud, file, etc.), drill-through, mapping rules, scheduling.\nChoose Data Map for intra-app cube pushes, Data Integration for external sources or complex transforms." },
  { q:"A planner complains their business rule is slow on a form with thousands of cells. How does Groovy change this, and what other optimizations should you consider?",
    hint:"Groovy is data-aware: reads only the edited cells (getEditedCells), so calc scope is tiny.\nOther levers: Fix() narrowing, FIXPARALLEL, dense/sparse tuning, aggregation strategy, ASO vs BSO, Smart Push filters.\nGroovy also lets you short-circuit if no relevant edits occurred." },
  { q:"How would you design a navigation flow for three roles (executive, cost-center planner, HR analyst)?",
    hint:"One flow per role (or group-scoped flows).\nExecutive: dashboards + reports + KPI card; hide rules and detailed forms.\nCost-center planner: forecast/actual forms + workforce inputs + approvals card.\nHR analyst: workforce forms + employee lifecycle + compensation reports.\nUse clusters for topic grouping; tabs for sub-areas; artifact hides for clarity." },
  { q:"Walk through the steps to enable Workforce for a client planning headcount and compensation for 2,000 employees across 40 entities.",
    hint:"1. Create Planning app (or enable Workforce module on existing one).\n2. Choose granularity: employee, job, or employee+job.\n3. Configure currency, performance settings, and custom dimensions.\n4. Import employees and jobs via Data Integration or bulk load templates.\n5. Set compensation assumptions (merit, taxes, benefits, FTE rules).\n6. Build Workforce-specific forms and dashboards; load beginning headcount.\n7. Connect to Financials via module integration to push comp expense to P&L." },
  { q:"What is Intelligent Performance Management, and how would you set up a forecast model for monthly revenue?",
    hint:"IPM = Predictive Planning + IPM Insights + auto-predict + ML models.\nSteps: prepare historical data (enough periods), choose member scope, set seasonality, let ML pick a model (ARIMA, ETS) or train a custom one, deploy to a Scenario/Version, review bias/variance, publish to a target form.\nMonitor IPM Insights for anomalies after each actuals load." },
  { q:"Describe the Planning approval process end-to-end. What's the difference between bottom-up and distribute starts?",
    hint:"1. Define approval unit hierarchy on Entity (primary dim) + Scenario + Version.\n2. Assign owners/reviewers/validators per node.\n3. Attach data validations to enforce thresholds.\n4. Start the process: Bottom-up = leaf owners Promote upward; Distribute = top owner pushes budgets down, then leaves return them.\n5. States flow: Not Started → Under Review → Approved / Rejected.\n6. Use Process Status dashboard and notifications; audit via approval history." },
  { q:"A client wants to automate nightly Planning backups and a monthly refresh from ERP Cloud. What tools and pattern would you use?",
    hint:"Backups: EPM Automate scripts (login → runDailyMaintenance → downloadSnapshot → logout) on a scheduler (Windows Task/cron).\nERP refresh: Data Integration job connected to ERP Cloud, scheduled, with mapping rules and drill-through. Can be triggered via EPM Automate too.\nConsider error notifications, retry logic, and a rotating snapshot archive off-pod." },
  { q:"A report author needs to produce 200 per-entity P&L PDFs each month. Which reporting tool would you use and how do you design it?",
    hint:"Use Reports (Narrative Reporting engine) with bursting.\nDesign: one pixel-perfect report with Entity as the bursting dimension, populated from a Planning grid.\nBursting definition: iterate over Entity members, one PDF per member, delivered via email or saved to a library folder.\nFallback: scheduled job + EPM Automate for distribution." },
  { q:"Walk through the full Getting Started checklist for a new Planning Modules app. Which steps are order-sensitive and which can slide?",
    hint:"Order-sensitive: (1) Create app → (2) Add currencies → (3) Review integrations → (4) Enable features (locks after) → (5) Configure + run rules → (6) Refresh database → (7) Set user variables.\nThen flexible-but-sequenced: (8) Import data → (9) Provision users → (10) Rule security → (11) Reports → (12) Publish to planners → (13) Approvals → (14) Data maps between modules.\nRefresh database must run after every metadata change." },
  { q:"What are the five layers of Planning security, and how does Deny > None > Write > Read play out when a user is in two groups?",
    hint:"Layers: 1) Role (SA > Power User > User > Viewer) 2) Artifact permissions (can they open it?) 3) Member access (R/W/None/Deny) 4) Valid intersections 5) Cell-level security.\nEvaluation: Deny always wins. None beats Write. Closest member overrides parent.\nClassic trap: Group A = Write, Group B = None → user gets None. To unblock, remove the None, don't add more Writes." },
  { q:"A client is enabling Workforce for the first time. What decisions are locked at Enable, and in what order do you make them?",
    hint:"Locked at first enable: Granularity (Employee / Job / Employee + Job), Employee Demographics (must be selected at first enable if wanted), 53-Week Planning, granularity mapping dimensions.\nOrder: pick granularity → pick demographics → choose comp components → enable Merit / FTE / Flex Account Mapping → Configure page: import Components, set Options/Tiers → run Benefits and Taxes Wizard.\nRemind the client: you can add features later, but cannot remove them." },
  { q:"Describe the Benefits and Taxes Wizard prerequisites and the three screens it walks through.",
    hint:"Prerequisites (on the Configure page) BEFORE launching the wizard: import members into the Component dimension, configure Options (Benefits / Additional Earnings), configure Tiers (Taxes).\nWizard screens: Details (type, value type, max value, taxable, threshold scope) → Rates (rate tables, tiers) → Review.\nComponent Types: Simple, Rate Table, Rate Table and Threshold, Custom." },
  { q:"A client wants to link Workforce with Projects so project plans reflect real employees and rates. What integration design do you recommend?",
    hint:"Enable Workforce BEFORE Projects so employees and jobs exist when Projects turns on.\nUse Data Maps / Smart Push: Compensation Data → feeds labor cost; Headcount/FTE → feeds utilization.\nAlign Resource Classes: Labor in Projects pulls hours + rates from Workforce jobs.\nRun Project Integration data maps on schedule; drill-through from Projects back to Workforce for audit." },

  /* ---------------- v2 additions (4) ---------------- */
  { q:"Compare the three Approval Unit Templates — Bottom Up, Distribute, and Free Form — and when you'd pick each.",
    hint:"Bottom Up: leaves enter budgets → Promote upward through the hierarchy. Default & simplest. Good for decentralized planning where field owners produce the numbers.\nDistribute: top owner sets targets → pushes DOWN to leaves → leaves edit and Submit back up. Good when HQ sets the guardrails first.\nFree Form: no fixed direction. Any owner can take action at any node — flexible but less auditable. Good for mature orgs with clear ownership.\nAll three use the same Approval Unit Hierarchy; only the action flow differs.\nKey exam trap: Bottom Up owners PROMOTE, Distribute owners SUBMIT — not the same verb." },

  { q:"What is locked at application creation (and first module-enable) vs. what can you change later?",
    hint:"Locked forever at CREATE:\n  • Plan Type (Input/BSO) cube names\n  • Reporting (ASO) cube names\n  • 12-month vs 13-period calendar shape\n  • Fiscal Year Start Date convention (Same CY / Previous CY)\n  • Application type (Modules vs FreeForm)\n\nLocked at first ENABLE of a module:\n  • Workforce granularity (Employee / Job / Employee+Job)\n  • Employee Demographics (must be chosen on first enable if wanted)\n  • 53-Week Planning\n  • Custom dim count for Financials (max 5)\n\nFlexible after go-live: user access, metadata members, forms, rules, dashboards, most module features can be added (but not removed).\nRule of thumb: 'structure' locks, 'content' flexes." },

  { q:"Trace how data flows from Capital → Projects → Financials, and which data maps make it happen.",
    hint:"Capital → Projects: capital projects (equipment purchases, facility builds) push asset cost, depreciation, and project-linked cost into Projects via the Capital–Projects Integration data map. Use when a capex project feeds project WBS.\nCapital → Financials: depreciation expense and asset balances push to Financials via the Capital Integration data map → hits Income Statement and Balance Sheet.\nProjects → Financials: project revenue, labor cost, and expense roll up via Project Integration data map → populates the P&L.\nWorkforce → Projects: compensation + FTE feeds project labor cost (enable Workforce FIRST).\nAll sync via Data Maps; Smart Push triggers them on form save. Run as scheduled jobs for consistency." },

  { q:"IPM Insights surfaces anomalies, forecast variance & bias, and prediction accuracy. How do you act on each type?",
    hint:"Anomalies: unexpected values vs. historical pattern. Investigate the source data — bad load? one-off event? reclassify or exclude.\nForecast Variance: plan vs. actuals gap. Large variance → driver review, talk to the planner, adjust assumptions.\nForecast Bias: systematic over- or under-forecasting. If bias is consistent → retrain the model, change seasonality, or switch algorithm (ETS → ARIMA).\nPrediction Accuracy: MAPE / RMSE over time. Falling accuracy → refresh historical window, check for structural breaks (COVID, reorg).\nIPM Insights runs on EPM Enterprise only (not Standard)." },
];

/* ---------------------------------------------------------
   ESSAY_MC — one multiple-choice question per essay prompt.
   Used for Learn "essay concepts" mode and Hard quiz difficulty.
   --------------------------------------------------------- */
const ESSAY_MC = [
  { topic:"Planning vs FreeForm",
    q:"A client has a highly custom revenue-allocation process that doesn't fit the Financials module. Which application approach gives the most flexibility while still using Planning features?",
    opts:["Modules-only Planning application","FreeForm Planning application with user-defined dimensions","Strategic Modeling only","Essbase standalone cube"],
    correct:1,
    explain:"FreeForm keeps all Planning capabilities (forms, rules, reports, IPM) but lets you design your own cubes and dimensions without adopting module schemas." },
  { topic:"Valid intersections vs cell security",
    q:"Which statement best distinguishes valid intersections from cell-level security?",
    opts:["Both are permission-based","Valid intersections restrict data model combinations; cell security restricts user access to specific cells","Valid intersections only apply to ASO cubes","Cell security always overrides valid intersections"],
    correct:1,
    explain:"Valid intersections enforce business-logical combinations for everyone; cell-level security adds user- or group-based restrictions on top." },
  { topic:"Data Map vs Data Integration",
    q:"Which scenario is the best fit for a Data Map rather than a Data Integration?",
    opts:["Importing a CSV from a third-party ERP nightly","Pushing data between two Plan Types inside the same Planning application on form save","Mapping COA accounts from Oracle Fusion into Planning","Running a multi-step transformation with drill-through"],
    correct:1,
    explain:"Data Maps (with Smart Push) are optimized for intra-app cube-to-cube movement on save. External/complex transformations belong to Data Integration." },
  { topic:"Groovy performance",
    q:"Why does Groovy typically outperform Calc Script business rules on form-save calculations?",
    opts:["Groovy always skips aggregation","Groovy rules are data-aware and can scope calcs to only the edited cells","Groovy bypasses Essbase entirely","Calc Scripts can't read dimensions"],
    correct:1,
    explain:"Groovy's getEditedCells / grid context APIs let the rule narrow its FIX to what the user actually changed, shrinking the block count processed." },
  { topic:"Navigation flows",
    q:"A company wants different user experiences for executives, planners, and HR. The recommended approach is:",
    opts:["Build one global flow and let roles hide themselves","Create role- or group-scoped navigation flows and hide irrelevant artifacts per flow","Disable modules for each role","Use EPM Automate at login"],
    correct:1,
    explain:"Role- or group-scoped navigation flows with tailored clusters/tabs are the standard way to customize the UX per audience." },
  { topic:"Workforce granularity",
    q:"A client wants to plan headcount and compensation at the individual employee level, tracking specific jobs per person. The correct Workforce configuration is:",
    opts:["Employee-only","Job-only","Employee and Job","Strategic Modeling"],
    correct:2,
    explain:"Employee + Job granularity supports per-employee comp with job linkage; the other modes drop one side of that detail." },
  { topic:"IPM",
    q:"Which component of IPM uses historical data to automatically generate baseline forecasts?",
    opts:["Valid intersections","Predictive Planning / auto-predict","Data validations","Approval units"],
    correct:1,
    explain:"Predictive Planning and auto-predict train ML models (ETS, ARIMA, etc.) on history to produce baseline forecasts pushed to a target scenario." },
  { topic:"Approval starts",
    q:"Which statement correctly describes the difference between Bottom-up and Distribute approval starts?",
    opts:["Bottom-up starts at the top and pushes budgets down; Distribute pulls from leaves","Distribute starts at the top owner, pushes targets down, leaves return them; Bottom-up starts at leaves and promotes upward","Both behave identically","Only Bottom-up supports reviewers"],
    correct:1,
    explain:"Bottom-up = leaves promote upward. Distribute = top owner distributes targets to leaves, which then submit back up." },
  { topic:"Backups / EPM Automate",
    q:"The most reliable way to pull a nightly Planning snapshot to an on-prem archive is:",
    opts:["Manually download from the UI","A scheduled EPM Automate script that runs login → downloadSnapshot → logout","A Data Map","A Groovy rule"],
    correct:1,
    explain:"EPM Automate is the supported scripting tool for automated backups, refreshes, and other cloud admin actions; it's scheduled externally (cron/Task Scheduler)." },
  { topic:"Reports bursting",
    q:"To produce 200 per-entity PDFs from a single Planning report monthly, you would use:",
    opts:["Dashboard 2.0","Reports bursting with Entity as the bursting dimension","A composite form","Strategic Modeling"],
    correct:1,
    explain:"Reports (Narrative Reporting) bursting iterates the designated dimension and outputs one artifact per member, delivered on schedule." },
  { topic:"Required dimensions",
    q:"Which of these is NOT a required dimension in a Planning Modules application?",
    opts:["Account","Period","Product","Scenario"],
    correct:2,
    explain:"The six required dimensions are Account, Period, Years, Scenario, Version, and Entity (+ Currency when multicurrency is on). Product is user-defined — common, but not required." },
  { topic:"BSO vs ASO",
    q:"A planner needs to enter budget values and have business rules calculate against them. Which cube type is this?",
    opts:["ASO (Aggregate Storage)","BSO (Block Storage) — the Input cube","Hybrid Essbase only","Reporting cube"],
    correct:1,
    explain:"Input happens in the BSO cube and rules run against BSO. ASO is for high-volume reporting and does not run calc scripts." },
  { topic:"Refresh Database",
    q:"You added a new Entity member to the Planning outline. What must you do before planners see it on forms?",
    opts:["Run Smart Push","Run Refresh Database (Actions menu)","Restart the service","Nothing — it's automatic"],
    correct:1,
    explain:"Metadata changes don't reach the Essbase cube until Refresh Database runs. This is the classic 'member is missing' fix." },
  { topic:"Permission evaluation",
    q:"A user is in Group A (Write on Entity E1) and Group B (None on Entity E1). What access does the user have?",
    opts:["Write","Read","None","Deny"],
    correct:2,
    explain:"Deny > None > Write > Read. None overrides Write — the user is blocked on E1 until the None is removed." },
  { topic:"Budget Revisions prerequisites",
    q:"A client wants to use Budget Revisions with ERP Cloud Budgetary Control. Which set of prerequisites is correct?",
    opts:["Single currency, provided COA, standard Essbase","Hybrid Essbase, single currency, own chart of accounts","Multicurrency, Hybrid Essbase, own COA","Hybrid Essbase, multicurrency, provided COA"],
    correct:1,
    explain:"Budget Revisions requires Hybrid Essbase, single currency, and the client's own chart of accounts. Multicurrency is not supported." },
  { topic:"Predictive Planning scope",
    q:"A customer is on EPM Standard (not Enterprise). Which IPM feature can they still use?",
    opts:["IPM Insights","Bring Your Own ML","AutoPredict","Predictive Planning manual mode"],
    correct:2,
    explain:"AutoPredict is the one IPM feature available with Planning in EPM Standard. Everything else in IPM (Insights, PMML import, full Predictive Planning) requires EPM Enterprise." },
  { topic:"Smart Push vs Data Map",
    q:"Which best describes Smart Push?",
    opts:["A separate tool that replaces Data Maps","A Data Map that runs automatically when a form is saved","An ERP Cloud integration","A reporting-only feature"],
    correct:1,
    explain:"Smart Push uses the same underlying Data Map; the difference is activation — it fires on form save so the target cube stays in sync during planning." },
  { topic:"Component Dimension (Workforce)",
    q:"Before launching the Benefits and Taxes Wizard, what must an admin do?",
    opts:["Run Refresh Database only","Import members into the Component dimension and configure Options/Tiers","Enable 53-Week Planning","Disable Flexible Account Mapping"],
    correct:1,
    explain:"The wizard operates on Component members — you must import them and configure Options (Benefits / Additional Earnings) and Tiers (Taxes) on the Configure page first." },
  { topic:"Module enablement order",
    q:"A client plans to use both Workforce and Projects, with Projects tracking employee utilization. In what order should they be enabled?",
    opts:["Projects first, then Workforce","Either order works","Workforce first, then Projects","Only enable Workforce — Projects is optional"],
    correct:2,
    explain:"Workforce holds employee details (salary, hours, FTE) that Projects consumes for utilization. Enable Workforce first so the data is there when Projects integrations run." },

  /* ---------------- v2 additions (15) ---------------- */
  { topic:"Year dimension naming",
    q:"A planner is surprised that the dimension holding fiscal years in a Planning Modules app is named 'Years' (plural), not 'Year'. Why?",
    opts:["Essbase requires plural names for every dimension","'Years' is the reserved Oracle name for the Year dimension in Modules apps — it cannot be renamed","Because multi-year forecasts need a different dim name","It was renamed in 2024 and will revert in 2026"],
    correct:1,
    explain:"In Planning Modules, the time/year dimension is named 'Years' and it's one of the reserved dimension names. Don't try to rename it — rules and module artifacts reference the exact name." },

  { topic:"Fiscal Year Start Date",
    q:"A UK client's fiscal year runs April 2025 → March 2026. Their FY is labeled 'FY25'. Which Fiscal Year Start Date option matches?",
    opts:["Same Calendar Year (FY25 starts in 2025)","Previous Calendar Year (FY25 starts in 2024)","Next Calendar Year","No option — customize via Groovy"],
    correct:0,
    explain:"FY25 starts in calendar 2025 (April 2025), so you pick 'Same Calendar Year'. 'Previous Calendar Year' would be used if FY25 started in April 2024. This is locked at app creation." },

  { topic:"Dimension limits",
    q:"What is the maximum total number of dimensions allowed in a Planning Modules application?",
    opts:["12","16","32","Unlimited"],
    correct:2,
    explain:"A Planning app supports up to 32 dimensions total (required + user-defined). Of those, 31 can have aliases. Financials is capped at 5 custom dimensions; other modules have their own limits." },

  { topic:"Employee Demographics timing",
    q:"A customer decides in year two that they want to track Employee Demographics in Workforce. What's the problem?",
    opts:["Nothing — it can be turned on anytime","Employee Demographics must be enabled on first Workforce enable; retrofitting requires a new Workforce app or data reload","It requires Predictive Planning","It needs Hybrid Essbase"],
    correct:1,
    explain:"Employee Demographics is a first-enable decision in Workforce. If it wasn't selected at first enable, you cannot just flip it on — you face a significant rework. Plan it up front." },

  { topic:"Reserved module prefixes",
    q:"Which prefix is RESERVED by Oracle for Financials module artifacts, meaning custom artifacts cannot use it?",
    opts:["OEP_","OWP_","OFS_","OPF_"],
    correct:2,
    explain:"OFS_ = Financials. OEP_ is shared/common, OWP_ = Workforce, OPF_ = Projects, OCX_ = Capital. None of these may prefix custom artifact names." },

  { topic:"Custom dimensions in Financials",
    q:"What is the maximum number of custom dimensions you can add to the Financials module?",
    opts:["1","3","5","10"],
    correct:2,
    explain:"Financials allows up to 5 custom dimensions (on top of required ones). Other modules have different limits. Plan the 5 carefully — removing one later is painful." },

  { topic:"User Variables order",
    q:"After adding a new Entity member, when must user variables that filter on Entity be refreshed?",
    opts:["Before Refresh Database","Refresh Database must run first — only then can user variables resolve the new member","User variables are automatic","Only after a service restart"],
    correct:1,
    explain:"Metadata changes don't reach Essbase until Refresh Database completes. User variables that reference the new member won't resolve until Refresh Database has run." },

  { topic:"Funds Reserve behavior",
    q:"A planner has a pending Budget Revision that passes Funds Check. They then run Funds Reserve. What happens to the revision?",
    opts:["It stays pending","It is applied and the pending revision is cleared","It is deleted without applying","It requires a second approval"],
    correct:1,
    explain:"Funds Reserve commits the revision into Budgetary Control and clears the pending queue. Funds Check is a pre-flight validation only; Funds Reserve is the commit action." },

  { topic:"Workforce defaults — Employee granularity",
    q:"In an Employee-only Workforce app, what is the default granularity pair used for employee defaults (Synchronize Defaults 2.0)?",
    opts:["Department + Location","Pay Type + Employee Type","Job + Entity","Grade + Union"],
    correct:1,
    explain:"For Employee granularity, defaults sync on Pay Type + Employee Type. For Job granularity, defaults sync on Union Code + Job. For Employee + Job, you get both pairings." },

  { topic:"Threshold Amount — FICA",
    q:"You configure a Social Security tax that caps at the SSA wage base. Which B&T Wizard option handles this 'stop taxing above $X' behavior?",
    opts:["Simple","Rate Table","Rate Table and Threshold","Custom Groovy rule"],
    correct:2,
    explain:"Rate Table + Threshold is the component type designed for wage-base caps (FICA, SSA). The Threshold Amount sets the ceiling; tax stops accruing above it." },

  { topic:"Workforce Rules 2.0",
    q:"After updating employee defaults in a Workforce 2.0 app, which rule propagates those defaults down to all affected employees?",
    opts:["Calculate Compensation","Process Loaded Data","Synchronize Defaults 2.0","Refresh Database"],
    correct:2,
    explain:"Synchronize Defaults 2.0 walks the employee roster and applies updated default values. Synchronize Definition 2.0 handles structural definition changes. Use the right one for the right change." },

  { topic:"OWP_Custom Template",
    q:"A planner needs to move an employee from one Entity to another mid-year, keeping the salary intact. Which template handles this?",
    opts:["Add Requisition","Change Job","OWP_Custom Template (employee transfer)","Terminate Employee"],
    correct:2,
    explain:"OWP_Custom Template is the out-of-the-box transfer template — it moves an employee across Entity/Department while preserving comp details. 'Change Job' swaps the Job code, not the Entity." },

  { topic:"Declining Balance salvage",
    q:"When configuring Declining Balance (Year) depreciation in Capital, what is required for salvage value?",
    opts:["Must be zero","Must be ≥ 1% of asset cost (cannot be zero)","Must equal Straight-Line salvage","No salvage allowed"],
    correct:1,
    explain:"DB Year mathematically collapses if salvage = 0 (rate would have to be 100%), so Capital requires salvage ≥ 1% of cost. Straight-Line allows zero salvage; DB does not." },

  { topic:"Approval actions — Bottom Up",
    q:"An Entity owner finishes inputting their budget in a Bottom Up approval template. Which action sends it up the hierarchy?",
    opts:["Submit","Promote","Distribute","Approve"],
    correct:1,
    explain:"Bottom Up = Promote (leaves push UP). Distribute owners Submit. Freeze locks a unit from edits. Getting the verb wrong is a common exam trap — match the template to the action." },

  { topic:"EPM Automate — runIntegration",
    q:"You have legacy scripts using `runDataRule` to execute Data Management integrations. What should you replace it with in EPM Automate?",
    opts:["runBusinessRule","runIntegration","executeDataMap","runDailyMaintenance"],
    correct:1,
    explain:"`runDataRule` is deprecated. Use `runIntegration` for Data Integration jobs. `executeDataMap` is for intra-app Data Maps; those are different objects." },
];

/* ---------------------------------------------------------
   EXAM_Q — real-format exam practice questions from ExamsIndex
   1Z0-1080-25 demo PDF. Includes single-select AND multi-select
   (pick 2 / pick 3) questions. `correct` is always an array of
   zero-based option indices. `pick` is the required selection count.
   --------------------------------------------------------- */
const EXAM_Q = [
  {
    topic: "IPM — Bring Your Own ML",
    pick: 1,
    q: "Which task must be completed before EPM administrators import a Machine Learning model into Planning?",
    opts: [
      "Data Scientists build and train the ML model in a data science tool and save it as a PMML file.",
      "Data Scientists create Groovy rules designed to evaluate historical data and identify patterns.",
      "EPM Administrators create a data model and push data to it to generate a PMML file.",
      "EPM Administrators create data maps and Groovy rules to move and process data.",
    ],
    correct: [0],
    explain: "The 'Bring Your Own ML' feature requires data scientists to build and train the ML model in a third-party data science tool (or Oracle Data Science Cloud) and save it as a PMML file. The EPM administrator imports that prebuilt PMML file into Planning; the app then auto-generates the Groovy rules needed to integrate the model.",
  },
  {
    topic: "Operations — Scheduling Jobs",
    pick: 2,
    q: "You need to schedule a weekly data import job. Which two statements are true about scheduling jobs?",
    opts: [
      "You can check the execution status of a job only if it completed.",
      "You can set the daily maintenance time when scheduling cloning environment jobs.",
      "You can set to receive notifications when the job has completed.",
      "You can schedule an Import Data job to run later at intervals.",
      "You can delete jobs that are currently processing.",
    ],
    correct: [2, 3],
    explain: "C and D are true. The Jobs console supports email notifications on completion (C) and recurring schedules for Import Data jobs — daily, weekly, or at a custom interval (D). A is false: the Jobs console shows Running status in real time. B is false: daily maintenance time is a system-wide application setting, not a per-job option. E is false: running jobs can't be deleted until they complete or fail.",
  },
  {
    topic: "Navigation Flows — Customization Categories",
    pick: 3,
    q: "Which three are Navigation Flow customization categories?",
    opts: [
      "Role",
      "User",
      "Group",
      "Artifact",
      "Global",
    ],
    correct: [0, 2, 4],
    explain: "Navigation flows are customized at three levels: Role (e.g., Planner vs Administrator), Group (teams or departments), and Global (the default applied to all users unless overridden). User-level customization isn't supported — flows target roles/groups. 'Artifact' is a migration concept, not a nav-flow category.",
  },
  {
    topic: "Projects — Revenue & Expense Assumptions",
    pick: 3,
    q: "Which three types of revenue and expense assumptions drive data calculations in Projects?",
    opts: [
      "Working days and hours",
      "Plan start year",
      "Standard rates",
      "Program mappings",
      "Project rates",
      "Discount rates",
    ],
    correct: [0, 2, 4],
    explain: "Working days & hours (resource availability → labor cost and revenue), Standard rates (default hourly/daily rates across projects), and Project rates (project-specific rates that override the standard) all directly drive Projects financials. Plan start year is a timeline parameter, Program mappings integrate data across programs, and Discount rates are for NPV/financial analysis — none are direct revenue/expense drivers.",
  },
  {
    topic: "Module Integration — Workforce → Projects",
    pick: 1,
    q: "Which module should you enable first to track the utilization of employees in Projects?",
    opts: [
      "Projects module before Financials module",
      "Financials module before Projects module",
      "Workforce module before Projects module",
      "Projects module before Workforce module",
    ],
    correct: [2],
    explain: "Workforce holds employee details (roles, salaries, hours, FTE) that Projects consumes to calculate utilization. Enable Workforce first, then Projects can pull the employee data via integration/data maps and track utilization against project tasks and budgets. Financials handles P&L but doesn't manage employee-level data.",
  },
  {
    topic: "Module Integration — Workforce → Financials",
    pick: 1,
    q: "You can override expense lines in Financials with the more detailed values that Workforce stores. What steps would you take to move the detailed values to Financials?",
    opts: [
      "In data maps, for Financial Statement Integration, define how the detailed Workforce accounts roll up into the Financials accounts.",
      "On the Financials Integration Summary form, calculate compensation data to update the underlying details for Workforce data.",
      "On the Financials Integration Summary form, from the Actions menu, select the Rollup business rule.",
      "In data maps, for Compensation Data, synchronize and then push the data.",
    ],
    correct: [0],
    explain: "The out-of-the-box 'Financial Statement Integration' data map defines how detailed Workforce accounts (salary, taxes, benefits) roll up into Financials accounts. Once the mapping is set, you synchronize and push the data. The Financials Integration Summary form only views rolled-up data — there's no 'Rollup' rule in its Actions menu, and the Compensation Data map alone is too narrow for this scenario.",
  },
  {
    topic: "Financials — Revenue & Expense Navigation Flow",
    pick: 1,
    q: "You want to input data into Financials. For Financials, there is a predefined navigation flow with cards listed for both Revenue and Expenses. What is the sequence of the cards for Revenue and Expenses?",
    opts: [
      "Overview, Driver and Trend Based, Rolling Forecast, Direct Entry, Income Statement",
      "Assumptions, Allocations, Detailed Bottom Up, Strategic Top-Down, Direct Input, Overview",
      "Assumptions, Direct Input, Driver and/or Trend Based, High Level Overview, Detailed Overview, Summary",
      "Overview, Assumptions, Allocations, Detailed Bottom-Up, Driver and/or Trend based, Direct Input",
    ],
    correct: [0],
    explain: "The out-of-the-box Financials navigation flow walks users from high-level context into detailed entry and back to reporting: Overview → Driver and Trend Based → Rolling Forecast → Direct Entry → Income Statement. 'Allocations', 'Detailed Bottom-Up', and 'Strategic Top-Down' appear in other flows/modules but are not part of the default Financials Revenue & Expenses sequence.",
  },
  {
    topic: "Operations — Clone Snapshot",
    pick: 1,
    q: "What feature can Service Administrators use to automatically complete all the actions required to create an exact copy of the current application in a target environment — including the removal of the current application and data, if any, from the target environment?",
    opts: [
      "Replicate Snapshot",
      "Migration Export",
      "Clone Snapshot",
      "Migration Backup",
    ],
    correct: [2],
    explain: "Clone Snapshot (on the source environment) automates the entire end-to-end clone: export a snapshot, delete the target's existing application and data, then import and apply the snapshot so the target is an exact copy of the source. Migration Export only exports artifacts, Migration Backup just creates a recovery file, and 'Replicate Snapshot' isn't a real feature name.",
  },
  {
    topic: "Required Dimensions",
    pick: 3,
    q: "Which three of the following are required dimensions in every Planning Modules application (excluding Currency, which is added only when Multicurrency is enabled)?",
    opts: [
      "Account",
      "Product",
      "Scenario",
      "Entity",
      "Region",
      "Department",
    ],
    correct: [0, 2, 3],
    explain: "The required dims are Account, Period, Years, Scenario, Version, and Entity (+ Currency when multicurrency is on). Product, Region, and Department are typical user-defined dimensions but are not required.",
  },
  {
    topic: "Workforce Granularity",
    pick: 3,
    q: "Which three granularity levels are available when first enabling the Workforce module?",
    opts: [
      "Employee",
      "Job",
      "Department",
      "Employee and Job",
      "Position",
    ],
    correct: [0, 1, 3],
    explain: "Workforce granularity is one of Employee, Job, or Employee and Job. This choice is locked on first enable. Department and Position aren't granularity options — they're dimensions.",
  },
  {
    topic: "Project Types",
    pick: 3,
    q: "Which three are valid Project Types in the Projects module?",
    opts: [
      "Contract",
      "Indirect",
      "Grants",
      "Capital",
      "Research",
    ],
    correct: [0, 1, 3],
    explain: "The three project types are Contract, Indirect, and Capital. Grants and Research aren't project types in the Projects module.",
  },
  {
    topic: "Permission Hierarchy",
    pick: 1,
    q: "A user belongs to Group A with Write on an Entity and Group B with None on the same Entity. What is their effective access?",
    opts: [
      "Write (unions take the most permissive)",
      "Read (fallback)",
      "None (None overrides Write)",
      "Deny",
    ],
    correct: [2],
    explain: "The evaluation order is Deny > None > Write > Read. None always overrides Write — this is the single most tested permission trap on the exam.",
  },
  {
    topic: "Budget Revisions Prerequisites",
    pick: 3,
    q: "Budget Revisions integrates with Oracle ERP Cloud Budgetary Control. Which three configurations are required?",
    opts: [
      "Hybrid Essbase",
      "Multicurrency enabled",
      "Single currency",
      "Your own chart of accounts (not provided COA)",
      "ASO-only reporting",
    ],
    correct: [0, 2, 3],
    explain: "Budget Revisions needs Hybrid Essbase, single currency, and your own chart of accounts. Multicurrency is NOT supported, and reporting is not constrained to ASO-only.",
  },
  {
    topic: "PMML / Bring Your Own ML",
    pick: 1,
    q: "An EPM admin wants to deploy a custom machine learning model into Planning via IPM. What file format does the data scientist provide?",
    opts: [
      "A Groovy script file (.grv)",
      "A PMML file (.pmml)",
      "A .cube export",
      "A CSV with model coefficients",
    ],
    correct: [1],
    explain: "Bring Your Own ML is driven by PMML — a universal XML-based ML exchange format. The data scientist trains externally (e.g., scikit-learn → sklearn2pmml), exports .pmml, and the admin imports it into IPM where Planning auto-wires the Groovy.",
  },
  {
    topic: "Module Prefixes",
    pick: 2,
    q: "Which two of these predefined prefixes identify Workforce and Projects artifacts, respectively?",
    opts: [
      "OEP_",
      "OWP_",
      "OFS_",
      "OPF_",
      "OCX_",
    ],
    correct: [1, 3],
    explain: "OWP_ prefixes Workforce artifacts; OPF_ prefixes Projects artifacts. OEP_ is common-across-modules, OFS_ is Financials, OCX_ is Capital. Custom artifact names may NOT use these prefixes.",
  },
  {
    topic: "Calendar / PM Cloud Integration",
    pick: 1,
    q: "A client wants to integrate Projects with Oracle Project Management (ERP). Which accounting calendar is NOT supported for this integration?",
    opts: [
      "12-period monthly",
      "4-4-5",
      "5-4-4",
      "4-4-4",
    ],
    correct: [3],
    explain: "Project Management Cloud integration supports 12-period monthly, 4-4-5, 5-4-4, and 4-5-4. 4-4-4 (36-week pseudo-calendars) is not supported.",
  },
  {
    topic: "Things Locked After Creation",
    pick: 3,
    q: "Which three of the following CANNOT be changed after a Planning Modules app is created?",
    opts: [
      "Input cube name",
      "Reporting cube name",
      "A new user-defined dimension member",
      "13-period vs 12-month calendar choice",
      "The set of planners who have Write access",
    ],
    correct: [0, 1, 3],
    explain: "Cube names and the calendar shape (13-period vs 12-month) are locked at creation. You can always add members to user-defined dimensions and change user access after go-live.",
  },
  {
    topic: "EPM Automate Backup Pattern",
    pick: 1,
    q: "Which sequence of EPM Automate commands is the standard nightly-snapshot-to-archive pattern?",
    opts: [
      "login → runDailyMaintenance → downloadSnapshot → logout",
      "login → importMetadata → exportData → logout",
      "downloadSnapshot → login → logout",
      "runBusinessRule → downloadSnapshot → logout",
    ],
    correct: [0],
    explain: "The supported nightly pattern is login → runDailyMaintenance (lets backup complete) → downloadSnapshot (pull it local) → logout. Scheduled externally via cron or Task Scheduler.",
  },
  {
    topic: "Groovy Use Cases",
    pick: 3,
    q: "Which three are scenarios where Groovy is required or strongly recommended over Calc Script?",
    opts: [
      "You need to calculate only the cells the user just edited on a form",
      "You need to call a REST API from inside the rule",
      "You need a simple FIX/ENDFIX aggregation across a dimension",
      "You're adding a new employee, project, or asset (Add Requisition / Add Project / Add Asset)",
      "You want the rule to run every time the daily maintenance window fires",
    ],
    correct: [0, 1, 3],
    explain: "Groovy shines for: edited-cells-only calcs (performance), REST calls, loops/conditional logic, and Add-X templates. A plain FIX aggregation is fine in Calc Script; daily-maintenance-triggered runs are scheduled jobs, not a rule-language concern.",
  },
  {
    topic: "IPM Components",
    pick: 2,
    q: "Which two of the following are components of Intelligent Performance Management (IPM)?",
    opts: [
      "IPM Insights",
      "Predictive Planning",
      "Strategic Modeling",
      "Narrative Reporting",
    ],
    correct: [0, 1],
    explain: "IPM = Predictive Planning + IPM Insights + AutoPredict + Bring Your Own ML. Strategic Modeling and Narrative Reporting are separate products/features, not part of IPM.",
  },

  /* ---------------- v2 additions (16) ---------------- */
  {
    topic: "Oracle Ecosystem — Four Pillars",
    pick: 1,
    q: "Oracle groups its Fusion Cloud Applications into four pillars. Which list is correct?",
    opts: [
      "ERP, SCM, CRM, HCM",
      "ERP, EPM, HCM, CX",
      "ERP, EPM, SCM, MDM",
      "EPM, Data Cloud, CX, HR",
    ],
    correct: [1],
    explain: "The four pillars are ERP (finance ops), EPM (planning & performance), HCM (people), CX (customer experience). EPM sits adjacent to ERP — ERP records what happened, EPM plans what should happen next.",
  },
  {
    topic: "ERP ↔ EPM direction",
    pick: 1,
    q: "Which statement about the ERP ↔ EPM integration is correct?",
    opts: [
      "ERP pulls plans from EPM; EPM never pulls actuals from ERP",
      "EPM pulls actuals from ERP; ERP pulls approved budgets/revisions from EPM",
      "Both systems share a single ledger",
      "Integration requires a third-party data warehouse",
    ],
    correct: [1],
    explain: "Standard pattern: EPM pulls ACTUALS from ERP (via Data Integration) to compute variance; ERP pulls approved BUDGETS/REVISIONS from EPM (via Budget Revisions + Budgetary Control). Money flows both ways — actuals in, budgets out.",
  },
  {
    topic: "Fiscal Year Start Date",
    pick: 1,
    q: "A client's fiscal year FY26 runs July 2025 to June 2026. At app creation, which Fiscal Year Start Date setting applies?",
    opts: [
      "Same Calendar Year",
      "Previous Calendar Year",
      "Rolling — updates each year",
      "Not supported — must use 12-month calendar",
    ],
    correct: [1],
    explain: "FY26 starts in calendar 2025, so the FY label is one ahead of the start year — that's 'Previous Calendar Year'. Opposite of a calendar-year fiscal. Locked at creation.",
  },
  {
    topic: "Dimension Maximums",
    pick: 2,
    q: "Which two statements about Planning dimension limits are true?",
    opts: [
      "Max 32 total dimensions per application",
      "Max 16 total dimensions per application",
      "Aliases allowed on all 32 dimensions",
      "Aliases allowed on 31 of the 32 dimensions",
      "Financials supports unlimited custom dimensions",
    ],
    correct: [0, 3],
    explain: "32 dimensions max total. Aliases are allowed on 31 of them (the Period dim doesn't get an alias table the same way). Financials caps custom dims at 5.",
  },
  {
    topic: "Things locked at creation",
    pick: 3,
    q: "Which three of the following are LOCKED at Planning application creation and cannot be changed later?",
    opts: [
      "Cube names (BSO input cubes and ASO reporting cubes)",
      "Application type (Modules vs FreeForm)",
      "The list of planners who can write to forms",
      "12-month vs 13-period calendar shape",
      "Custom forms and dashboards",
    ],
    correct: [0, 1, 3],
    explain: "Cube names, app type (Modules/FreeForm), and calendar shape are locked at creation. User access and forms are flexible throughout the life of the app.",
  },
  {
    topic: "53-Week Planning",
    pick: 1,
    q: "A client wants to add 53-Week Planning to Workforce a year after go-live. What's the issue?",
    opts: [
      "It can be enabled anytime",
      "53-Week Planning is a first-enable decision and cannot be retrofitted without significant rework",
      "It requires Predictive Planning",
      "It conflicts with 4-4-5 calendars only",
    ],
    correct: [1],
    explain: "53-Week Planning is locked on first module enable. Retrofitting means a new app or heavy data migration. Always confirm the client's calendar shape before first enable.",
  },
  {
    topic: "Workforce — Component Types",
    pick: 3,
    q: "Which three are valid Workforce Component Types used by the Benefits and Taxes Wizard?",
    opts: [
      "Simple",
      "Rate Table",
      "Rate Table and Threshold",
      "Custom",
      "Tiered Groovy",
      "Dynamic",
    ],
    correct: [0, 1, 2],
    explain: "The four component types are Simple, Rate Table, Rate Table and Threshold, and Custom. 'Tiered Groovy' and 'Dynamic' aren't component types — they're made up. Custom is for calcs that don't fit the first three.",
  },
  {
    topic: "Employee granularity defaults",
    pick: 1,
    q: "In an Employee-granularity Workforce app, Synchronize Defaults 2.0 applies defaults using which pairing?",
    opts: [
      "Department + Location",
      "Pay Type + Employee Type",
      "Union Code + Job",
      "Entity + Scenario",
    ],
    correct: [1],
    explain: "Employee granularity uses Pay Type + Employee Type as the default pair. Job granularity uses Union Code + Job. Employee + Job uses both pairings. Know which pair fires for which granularity — common exam trap.",
  },
  {
    topic: "Approval verbs — Distribute",
    pick: 1,
    q: "In a Distribute-template approval process, a leaf owner has finished editing the targets pushed down to them. Which action returns the plan up the hierarchy?",
    opts: [
      "Promote",
      "Submit",
      "Reject",
      "Freeze",
    ],
    correct: [1],
    explain: "Distribute owners SUBMIT (leaves return the edited plan). Bottom Up owners PROMOTE (leaves push up). Same direction (up), different verb — it's the template that determines which verb appears.",
  },
  {
    topic: "Approval Unit member limit",
    pick: 1,
    q: "What is the maximum number of primary-dimension members that can be assigned to a single Approval Unit Hierarchy?",
    opts: [
      "10",
      "30",
      "100",
      "Unlimited",
    ],
    correct: [1],
    explain: "An Approval Unit Hierarchy supports up to 30 members. If you have more, split across multiple hierarchies or restructure the Entity dim.",
  },
  {
    topic: "Capital — Declining Balance",
    pick: 1,
    q: "When choosing Declining Balance (Year) depreciation for an asset in Capital, what salvage-value rule applies?",
    opts: [
      "Salvage must be zero",
      "Salvage must be ≥ 1% of cost",
      "Salvage must equal annual depreciation",
      "Salvage is calculated automatically",
    ],
    correct: [1],
    explain: "Declining Balance requires salvage ≥ 1% of cost (it divides by salvage internally; zero would break the math). Straight-Line accepts zero salvage; DB does not.",
  },
  {
    topic: "Capital — asset types",
    pick: 3,
    q: "Which three asset types does the Capital module support?",
    opts: [
      "Tangible",
      "Intangible",
      "Leased (IFRS 16)",
      "Consumable",
      "Financial",
    ],
    correct: [0, 1, 2],
    explain: "Capital supports Tangible (physical), Intangible (software, patents), and Leased assets (IFRS 16 / ASC 842 right-of-use). Consumables go to OpEx, Financial assets belong to Strategic Modeling.",
  },
  {
    topic: "IPM — Insight types",
    pick: 3,
    q: "Which three types of insights does IPM Insights surface on actuals and forecasts?",
    opts: [
      "Anomalies",
      "Forecast Variance",
      "Forecast Bias",
      "Dimensional Drift",
      "Cube Size Growth",
    ],
    correct: [0, 1, 2],
    explain: "IPM Insights analyzes Anomalies (unexpected values), Forecast Variance (plan vs actual gap), and Forecast Bias (systematic over/under-prediction). Dimensional drift and cube size are operations concerns, not IPM insights.",
  },
  {
    topic: "EPM Automate — deprecated commands",
    pick: 1,
    q: "Legacy scripts use `runDataRule` to trigger an integration job. What should replace it in a modern EPM Automate script?",
    opts: [
      "runBusinessRule",
      "executeDataMap",
      "runIntegration",
      "refreshDatabase",
    ],
    correct: [2],
    explain: "`runDataRule` (Data Management) is deprecated in favor of `runIntegration` (Data Integration). `executeDataMap` handles intra-app Data Maps — that's a different artifact.",
  },
  {
    topic: "Snapshot copy between environments",
    pick: 1,
    q: "You want to copy a snapshot from your Production pod to your Test pod without downloading it locally. Which EPM Automate command does this?",
    opts: [
      "downloadSnapshot",
      "uploadSnapshot",
      "copySnapshotFromInstance",
      "recreate",
    ],
    correct: [2],
    explain: "`copySnapshotFromInstance` moves a snapshot pod-to-pod over the backbone without a local download. Saves bandwidth + time on large snapshots.",
  },
  {
    topic: "Service operations — recreate vs resetService",
    pick: 1,
    q: "A customer wants a clean, empty environment — all apps, data, and users removed. Which EPM Automate command does this?",
    opts: [
      "resetService (restarts services only)",
      "recreate (wipes and reprovisions the service)",
      "runDailyMaintenance",
      "upgrade",
    ],
    correct: [1],
    explain: "`recreate` wipes the environment and reprovisions it empty — dangerous but powerful. `resetService` just restarts the service and preserves data. Use `recreate` for full refresh; use `resetService` to recover from a hung service.",
  },
];
