/* =====================================================================
   deutsch.lab — content for German II (K5–K8)
   CARDS, VOCAB, QUIZ, GRAMMAR, K8_SECTIONS
   ===================================================================== */

const CARDS = [
  // K5 · Grammar
  { ch:'K5', type:'GR', front:'aus (Präposition)', back:'from a place / made of', note:'Always Dativ: Ich komme aus der Schweiz.' },
  { ch:'K5', type:'GR', front:'seit (Präposition)', back:'since / for (ongoing action)', note:'Use present tense! Seit einem Jahr lerne ich Deutsch.' },
  { ch:'K5', type:'GR', front:'bei (Präposition)', back:"at, near, with / at someone's place", note:'Always Dativ: bei Aldi, bei meiner Mutter.' },
  { ch:'K5', type:'GR', front:'mit (Präposition)', back:'with', note:'Always Dativ: mit meinem Freund.' },
  { ch:'K5', type:'GR', front:'zu (Präposition)', back:'to (a nearby place); for (occasion)', note:'Always Dativ: zum Bahnhof (zu+dem).' },
  { ch:'K5', type:'GR', front:'nach (Präposition)', back:'after; to (cities/countries without article)', note:'nach Berlin, nach dem Unterricht.' },
  { ch:'K5', type:'GR', front:'von (Präposition)', back:'from / of (possession/origin)', note:'Always Dativ: vom Lehrer (von+dem).' },
  { ch:'K5', type:'GR', front:'außer (Präposition)', back:'except for / besides', note:'Always Dativ: Außer mir kommt niemand.' },
  { ch:'K5', type:'GR', front:'womit / damit', back:'with what? / with it (da/wo-compound)', note:'Womit schreibst du? — Damit.' },
  { ch:'K5', type:'GR', front:'wofür / dafür', back:'for what? / for it', note:'Wofür brauchst du das? — Dafür.' },
  { ch:'K5', type:'GR', front:'worauf / darauf', back:'on what? / on it', note:'Worauf wartest du? — Darauf.' },
  { ch:'K5', type:'GR', front:'mich / mir', back:'me (Akk) / me (Dat)', note:'Er kennt mich. | Er gibt mir das Buch.' },
  { ch:'K5', type:'GR', front:'dich / dir', back:'you (Akk) / you (Dat)', note:'Ich sehe dich. | Ich gebe dir das.' },
  { ch:'K5', type:'GR', front:'ihn / ihm', back:'him (Akk) / him (Dat)', note:'Ich kenne ihn. | Ich gebe ihm das Buch.' },
  { ch:'K5', type:'GR', front:'sie / ihr (feminine)', back:'her (Akk) / her (Dat)', note:'Ich sehe sie. | Ich helfe ihr.' },
  { ch:'K5', type:'GR', front:'uns / euch / ihnen', back:'us / you-all / them (Akk = Dat except ihnen)', note:'Dat: uns, euch, ihnen.' },
  { ch:'K5', type:'GR', front:'Two-way prep: wo? vs wohin?', back:'wo? → Dativ (location) · wohin? → Akkusativ (motion into)', note:'in/auf/unter/über/neben/zwischen/hinter/an/vor.' },
  { ch:'K5', type:'GR', front:'Akkusativ-Präpositionen (dogfud)', back:'durch · ohne · gegen · für · um', note:'Always Akkusativ. Mnemonic: d-o-g-f-u-d.' },
  { ch:'K5', type:'GR', front:'8 Dativ-only Präpositionen', back:'aus · außer · bei · mit · nach · seit · von · zu', note:'Always Dativ. (zu+dem=zum · von+dem=vom · bei+dem=beim)' },
  { ch:'K5', type:'GR', front:'9 Wechselpräpositionen', back:'in · auf · unter · über · neben · zwischen · hinter · an · vor', note:'Wo? Dativ (liegen/stehen/hängen) · Wohin? Akkusativ (legen/stellen/hängen).' },

  // K5 · Vocab
  { ch:'K5', type:'VO', front:'der Bahnhof', back:'train station' },
  { ch:'K5', type:'VO', front:'die Apotheke', back:'pharmacy' },
  { ch:'K5', type:'VO', front:'das Rathaus', back:'city hall' },
  { ch:'K5', type:'VO', front:'die Bibliothek', back:'library' },
  { ch:'K5', type:'VO', front:'das Krankenhaus', back:'hospital' },
  { ch:'K5', type:'VO', front:'die Post', back:'post office' },
  { ch:'K5', type:'VO', front:'die Bäckerei', back:'bakery' },
  { ch:'K5', type:'VO', front:'helfen (+ Dativ)', back:'to help (dative verb)', note:'Ich helfe dir.' },
  { ch:'K5', type:'VO', front:'gehören (+ Dativ)', back:'to belong to', note:'Das Buch gehört mir.' },
  { ch:'K5', type:'VO', front:'gefallen (+ Dativ)', back:'to please / to like', note:'Das Buch gefällt mir = I like the book.' },
  { ch:'K5', type:'VO', front:'schmecken (+ Dativ)', back:'to taste (good)', note:'Das schmeckt mir.' },

  // K6 · Grammar (Perfekt / Präteritum / conjunctions)
  { ch:'K6', type:'GR', front:'Präteritum: war / waren', back:'was / were (sein)', note:'ich war, du warst, er war, wir waren, ihr wart, sie waren.' },
  { ch:'K6', type:'GR', front:'Präteritum: hatte / hatten', back:'had (haben)', note:'ich hatte, du hattest, er hatte, wir hatten.' },
  { ch:'K6', type:'GR', front:'Perfekt: haben or sein?', back:'sein → motion/change of state. haben → most others.', note:'Ich bin gegangen. | Ich habe gegessen.' },
  { ch:'K6', type:'GR', front:'Partizip II: regular (weak)', back:'ge- + stem + -t', note:'kaufen → gekauft, spielen → gespielt.' },
  { ch:'K6', type:'GR', front:'Partizip II: strong', back:'ge- + (new) stem + -en', note:'gehen → gegangen, sprechen → gesprochen.' },
  { ch:'K6', type:'GR', front:'Partizip II: -ieren verbs', back:'NO ge-: just stem + -iert', note:'telefonieren → telefoniert, studieren → studiert.' },
  { ch:'K6', type:'GR', front:'Partizip II: inseparable prefix (be-/er-/ver-/ent-/emp-/zer-/ge-)', back:'NO ge-', note:'besuchen → besucht, verstehen → verstanden, vergessen → vergessen.' },
  { ch:'K6', type:'GR', front:'Partizip II: separable prefix', back:'ge- goes BETWEEN prefix and stem', note:'aufmachen → aufgemacht, einkaufen → eingekauft.' },
  { ch:'K6', type:'GR', front:'als vs. wenn vs. wann', back:'als = single past event · wenn = recurring/if · wann = question word', note:'Als ich jung war… | Wenn ich müde bin… | Wann kommst du?' },
  { ch:'K6', type:'GR', front:'weil vs. denn', back:'weil → verb to end · denn → normal word order', note:'Ich esse, weil ich Hunger habe. | Ich esse, denn ich habe Hunger.' },
  { ch:'K6', type:'GR', front:'dass', back:'that (conjunction) — verb to end', note:'Ich finde, dass Deutsch schön ist.' },

  // K6 · Vocab
  { ch:'K6', type:'VO', front:'die Kindheit', back:'childhood' },
  { ch:'K6', type:'VO', front:'aufwachsen', back:'to grow up', note:'ist aufgewachsen (sein!).' },
  { ch:'K6', type:'VO', front:'damals', back:'back then / at that time' },
  { ch:'K6', type:'VO', front:'früher', back:'formerly / in the past / used to' },
  { ch:'K6', type:'VO', front:'plötzlich', back:'suddenly' },
  { ch:'K6', type:'VO', front:'zuerst / dann / danach / schließlich', back:'first / then / afterwards / finally' },
  { ch:'K6', type:'VO', front:'verbringen', back:'to spend (time)', note:'hat verbracht.' },
  { ch:'K6', type:'VO', front:'passieren', back:'to happen', note:'ist passiert — sein! Was ist passiert?' },
  { ch:'K6', type:'VO', front:'erzählen', back:'to tell (a story)', note:'hat erzählt.' },
  { ch:'K6', type:'VO', front:'einladen', back:'to invite', note:'lädt ein → hat eingeladen (separable, stem-change).' },
  { ch:'K6', type:'VO', front:'vergessen', back:'to forget', note:'vergisst → hat vergessen (insep. ver- → KEIN ge-).' },
  { ch:'K6', type:'VO', front:'besuchen', back:'to visit', note:'hat besucht (insep. be- → KEIN ge-).' },

  // K7 · Grammar (Relativ + Adjektive + Komparativ)
  { ch:'K7', type:'GR', front:'Relativpronomen: masculine', back:'Nom der · Akk den · Dat dem', note:'Der Mann, den ich kenne, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: feminine', back:'Nom die · Akk die · Dat der', note:'Die Frau, der ich helfe, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: neuter', back:'Nom das · Akk das · Dat dem', note:'Das Kind, das spielt, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: plural', back:'Nom/Akk die · Dat denen', note:'Die Leute, denen ich helfe, …' },
  { ch:'K7', type:'GR', front:'Adjektivendung after der/die/das (weak): Nom m/f/n', back:'-e / -e / -e', note:'der alte Mann, die alte Frau, das alte Kind.' },
  { ch:'K7', type:'GR', front:'Adjektivendung after ein/kein/mein (mixed): Nom m/f/n', back:'-er / -e / -es', note:'ein alter Mann, eine alte Frau, ein altes Kind.' },
  { ch:'K7', type:'GR', front:'Adjektivendung Akkusativ (weak)', back:'-en / -e / -e / -en', note:'den alten Mann, die alte Frau, das alte Kind, die alten Leute.' },
  { ch:'K7', type:'GR', front:'Adjektivendung Dativ (all forms)', back:'always -en', note:'dem alten Mann, der alten Frau, dem alten Kind, den alten Leuten.' },
  { ch:'K7', type:'GR', front:'Komparativ', back:'adj + -er (+ umlaut for alt/groß/jung etc.)', note:'schneller, größer, älter, jünger.' },
  { ch:'K7', type:'GR', front:'Superlativ (predicate)', back:'am + adj + -sten', note:'am schnellsten, am größten, am ältesten.' },
  { ch:'K7', type:'GR', front:'Superlativ (attributive)', back:'der/die/das + adj + -ste + (ending)', note:'der schnellste Zug, die älteste Frau.' },
  { ch:'K7', type:'GR', front:'Irregular: gut / viel / gern', back:'besser / mehr / lieber → am besten / am meisten / am liebsten' },

  // K7 · Vocab
  { ch:'K7', type:'VO', front:'das Café / Kaffeehaus', back:'café / coffeehouse', note:'Viennese tradition.' },
  { ch:'K7', type:'VO', front:'die Melange', back:'Viennese coffee with steamed milk' },
  { ch:'K7', type:'VO', front:'der Kellner / die Kellnerin', back:'waiter / waitress' },
  { ch:'K7', type:'VO', front:'die Rechnung', back:'the bill / check', note:'Die Rechnung, bitte!' },
  { ch:'K7', type:'VO', front:'das Trinkgeld', back:'tip (gratuity)' },
  { ch:'K7', type:'VO', front:'bestellen', back:'to order (food/drink)' },
  { ch:'K7', type:'VO', front:'empfehlen', back:'to recommend', note:'Irregular: er empfiehlt.' },
  { ch:'K7', type:'VO', front:'schmecken', back:'to taste good', note:'Das schmeckt!' },
  { ch:'K7', type:'VO', front:'die Speisekarte', back:'menu' },
  { ch:'K7', type:'VO', front:'die Vorspeise / das Hauptgericht / die Nachspeise', back:'starter / main course / dessert' },

  // K8 · Grammar (Konjunktiv II, Partizip I, Futur, Passiv, Infinitivkonstruktionen)
  { ch:'K8', type:'GR', front:'Konjunktiv II: würde + Infinitiv', back:'would + verb (hypothetical / polite)', note:'Ich würde gern reisen. Was würdest du machen?' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: wäre', back:'would be (from sein)', note:'Ich wäre glücklich. Wenn ich reich wäre…' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: hätte', back:'would have (from haben)', note:'Ich hätte gern einen Kaffee.' },
  { ch:'K8', type:'GR', front:'Konjunktiv II der Modalverben', back:'könnte, müsste, dürfte, wollte, sollte (+ Infinitiv)', note:'Umlaut für können/müssen/dürfen — NOT for wollen/sollen.' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: wenn-Satz ("Kicker")', back:'Wenn + … + Konj II am Ende, würde/wäre/hätte …', note:'wenn = Kicker → konjugiertes Verb ans Ende. Wenn ich Zeit hätte, würde ich mehr lesen.' },
  { ch:'K8', type:'GR', front:'Partizip I (Form)', back:'Infinitiv + d (+ Adjektivendung): lesen → lesend', note:'Used like an adjective: ein schnell fahrendes Auto.' },
  { ch:'K8', type:'GR', front:'Partizip I = Relativsatz mit "der/die/das …"', back:'ein protestierender Student = ein Student, der protestiert', note:'Weinende Kinder = Kinder, die weinen.' },
  { ch:'K8', type:'GR', front:'Futur: werden + Infinitiv (am Ende)', back:'will + verb (future)', note:'Wir werden heute in die Neue Galerie gehen.' },
  { ch:'K8', type:'GR', front:'werden — Präsens konjugieren', back:'ich werde · du wirst · er wird · wir werden · ihr werdet · sie werden', note:'Stem change in du/er. Used for Futur AND Passiv.' },
  { ch:'K8', type:'GR', front:'Passiv Präsens', back:'wird + Partizip II', note:'Das Auto wird repariert.' },
  { ch:'K8', type:'GR', front:'Passiv Präteritum', back:'wurde + Partizip II', note:'Das Auto wurde repariert.' },
  { ch:'K8', type:'GR', front:'Passiv Perfekt', back:'ist + Partizip II + worden', note:'Das Auto ist repariert worden.' },
  { ch:'K8', type:'GR', front:'Passiv agent (by whom?)', back:'von + Dativ', note:'Das Buch wird von dem Lehrer gelesen.' },
  { ch:'K8', type:'GR', front:'um … zu + Infinitiv', back:'in order to do something', note:'Ich lerne Deutsch, um in Wien zu leben.' },
  { ch:'K8', type:'GR', front:'ohne … zu + Infinitiv', back:'without doing something', note:'Er ging, ohne Tschüss zu sagen.' },
  { ch:'K8', type:'GR', front:'statt … zu + Infinitiv', back:'instead of doing something', note:'Statt zu lernen, schläft er.' },
  { ch:'K8', type:'GR', front:'Separable verb + zu', back:'zu goes BETWEEN prefix and stem: aufzumachen', note:'um die Tür aufzumachen.' },

  // K8 · Vocab
  { ch:'K8', type:'VO', front:'die Umwelt', back:'the environment' },
  { ch:'K8', type:'VO', front:'die Umweltverschmutzung', back:'environmental pollution' },
  { ch:'K8', type:'VO', front:'der Klimawandel', back:'climate change' },
  { ch:'K8', type:'VO', front:'die Nachhaltigkeit', back:'sustainability', note:'nachhaltig = sustainable.' },
  { ch:'K8', type:'VO', front:'erneuerbare Energien', back:'renewable energies' },
  { ch:'K8', type:'VO', front:'der Müll / der Abfall', back:'garbage / waste' },
  { ch:'K8', type:'VO', front:'schützen', back:'to protect' },
  { ch:'K8', type:'VO', front:'verbrauchen', back:'to consume / use up' },
  { ch:'K8', type:'VO', front:'sparen', back:'to save' },
  { ch:'K8', type:'VO', front:'die Gleichberechtigung', back:'equal rights' },
  { ch:'K8', type:'VO', front:'die Demokratie', back:'democracy' },
  { ch:'K8', type:'VO', front:'wählen', back:'to vote / to elect / to choose', note:'die Wahl = the election.' },
  { ch:'K8', type:'VO', front:'das Gesetz', back:'law (pl: Gesetze)' },
  { ch:'K8', type:'VO', front:'die Regierung', back:'government' },
  { ch:'K8', type:'VO', front:'die Gesellschaft', back:'society' },
  { ch:'K8', type:'VO', front:'die Bewerbung', back:'job application', note:'sich bewerben = to apply.' },
  { ch:'K8', type:'VO', front:'der Lebenslauf', back:'résumé / CV' },
  { ch:'K8', type:'VO', front:'das Vorstellungsgespräch', back:'job interview' },
  { ch:'K8', type:'VO', front:'das Gehalt', back:'salary' },
  { ch:'K8', type:'VO', front:'einstellen', back:'to hire', note:'stellt ein, hat eingestellt.' },
  { ch:'K8', type:'VO', front:'kündigen', back:'to quit / to fire' },
  { ch:'K8', type:'VO', front:'die Ausbildung', back:'vocational training' },
  { ch:'K8', type:'VO', front:'umziehen', back:'to move (to a new home)', note:'ist umgezogen (separable, sein!).' },
  { ch:'K8', type:'VO', front:'der Bewerber / die Bewerberin', back:'applicant', note:'sich um eine Stelle bewerben.' },
  { ch:'K8', type:'VO', front:'das Praktikum', back:'internship', note:'pl: die Praktika.' },
  { ch:'K8', type:'VO', front:'die Erfahrung', back:'experience' },

  // K8 · Grammar — extras drawn from K8.6–8.10 (Auto, Wenn-Satz, -los, Komposita, Partizip I)
  { ch:'K8', type:'GR', front:'Wenn-Satz: REAL vs. IRREAL', back:'real → Indikativ; irreal → Konjunktiv II', note:'Real: "Wenn ich müde bin, schlafe ich." · Irreal: "Wenn ich müde wäre, würde ich schlafen."' },
  { ch:'K8', type:'GR', front:'Adjektive auf -los (Nomen + los)', back:'= "ohne X" — die Chance + los → chancenlos', note:'Bsp.: der autolose Sonntag = ein Sonntag ohne Autos. Hacker sind fast chancenlos.' },
  { ch:'K8', type:'GR', front:'Komposita definieren mit Relativsatz', back:'das X ist die/der/das Y, …', note:'Sonnenuntergang = die Tageszeit, zu der die Sonne jeden Abend untergeht.' },
  { ch:'K8', type:'GR', front:'Partizip I + Adjektivendung — n. Nom. nach "ein"', back:'-es: ein lesendes Kind, ein fahrendes Auto', note:'fahren → fahrend → fahrendes (Adj.-Endung wie "klein" → kleines).' },
  { ch:'K8', type:'GR', front:'Partizip I + Adjektivendung — m. Nom. nach "ein"', back:'-er: ein lesender Student, ein protestierender Student', note:'Mixed Dekl. m. Nom. → -er.' },
  { ch:'K8', type:'GR', front:'Partizip I + Adjektivendung — Pl. Nom. ohne Artikel', back:'-e: weinende Kinder, lachende Kinder', note:'Starke Pl. Nom. → -e.' },

  // K8 · Vocab — extras: Auto/Mobilität, Sprache/Komposita, Avantgarde, Utopie/Dystopie
  { ch:'K8', type:'VO', front:'das Auto / Auto fahren', back:'car / to drive a car', note:'Mobilität in der Zukunft: selbstfahrendes Auto.' },
  { ch:'K8', type:'VO', front:'die Erfindung', back:'invention', note:'erfinden → der Erfinder / die Erfinderin.' },
  { ch:'K8', type:'VO', front:'die Mobilität', back:'mobility' },
  { ch:'K8', type:'VO', front:'die Zukunft', back:'future', note:'in der Zukunft = in the future.' },
  { ch:'K8', type:'VO', front:'die Innovation', back:'innovation', note:'Jugend forscht = youth research competition.' },
  { ch:'K8', type:'VO', front:'die Sprache', back:'language', note:'Sprache im Wandel der Zeit = language change over time.' },
  { ch:'K8', type:'VO', front:'das Lehnwort / das Fremdwort', back:'loanword / foreign word', note:'Anglizismen im Deutschen: googeln, leaken, updaten, chillen.' },
  { ch:'K8', type:'VO', front:'die Jugendsprache', back:'youth slang', note:'Jugendwort des Jahres = youth word of the year.' },
  { ch:'K8', type:'VO', front:'das Kompositum (pl: Komposita)', back:'compound word', note:'Sonne+Untergang → der Sonnenuntergang. Article = letztes Element.' },
  { ch:'K8', type:'VO', front:'der Sonnenuntergang', back:'sunset', note:'Komposita-Beispiel: die Tageszeit, zu der die Sonne untergeht.' },
  { ch:'K8', type:'VO', front:'die Avantgarde', back:'avant-garde art / movement', note:'innovativ, provokativ, unkonventionell, revolutionär, sozialkritisch.' },
  { ch:'K8', type:'VO', front:'innovativ / provokativ / unkonventionell', back:'innovative / provocative / unconventional', note:'Adjektive für Avantgarde-Kunst.' },
  { ch:'K8', type:'VO', front:'der Dadaismus', back:'Dadaism (avant-garde art movement)', note:'Hugo Ball, "Karawane" 1916 — Lautgedicht, gegen jede Sprachregel.' },
  { ch:'K8', type:'VO', front:'das Lautgedicht', back:'sound poem', note:'Karawane: keine Bedeutung, keine Grammatik, nur Laute.' },
  { ch:'K8', type:'VO', front:'die Utopie', back:'utopia (ideal society)' },
  { ch:'K8', type:'VO', front:'die Dystopie', back:'dystopia (nightmare society)', note:'Beispiel: Metropolis (Fritz Lang, 1927).' },
  { ch:'K8', type:'VO', front:'„Berlin – Sinfonie der Großstadt"', back:'Walther Ruttmann, 1927 — Dokumentarfilm', note:'Tagesrhythmus einer Stadt klingt wie eine Sinfonie.' },
  { ch:'K8', type:'VO', front:'„Metropolis" (Fritz Lang)', back:'1927 expressionist film — dystopia', note:'Klassiker der deutschen Stummfilm-Dystopie.' },
  { ch:'K8', type:'VO', front:'chancenlos / arbeitslos / autolos', back:'without a chance / unemployed / without cars', note:'-los Suffix: Nomen + los = ohne X.' },
];

/* ===================== VOCAB (for vocab page) ===================== */
const VOCAB = [
  { ch:'K5', de:'der Bahnhof', en:'train station', note:'' },
  { ch:'K5', de:'die Apotheke', en:'pharmacy', note:'' },
  { ch:'K5', de:'das Rathaus', en:'city hall', note:'' },
  { ch:'K5', de:'die Bibliothek', en:'library', note:'' },
  { ch:'K5', de:'das Krankenhaus', en:'hospital', note:'' },
  { ch:'K5', de:'die Post', en:'post office', note:'' },
  { ch:'K5', de:'der Supermarkt', en:'supermarket', note:'' },
  { ch:'K5', de:'die Bäckerei', en:'bakery', note:'' },
  { ch:'K5', de:'die Metzgerei', en:'butcher shop', note:'' },
  { ch:'K5', de:'helfen (+Dat)', en:'to help', note:'Ich helfe dir.' },
  { ch:'K5', de:'gehören (+Dat)', en:'to belong to', note:'Das gehört mir.' },
  { ch:'K5', de:'gefallen (+Dat)', en:'to please / to like', note:'Das Buch gefällt mir.' },
  { ch:'K5', de:'schmecken (+Dat)', en:'to taste good', note:'Das schmeckt mir.' },
  { ch:'K5', de:'antworten (+Dat)', en:'to answer (a person)', note:'Ich antworte dir.' },
  { ch:'K5', de:'glauben (+Dat)', en:'to believe someone', note:'Ich glaube dir nicht.' },

  { ch:'K6', de:'die Kindheit', en:'childhood', note:'' },
  { ch:'K6', de:'aufwachsen', en:'to grow up', note:'ist aufgewachsen.' },
  { ch:'K6', de:'damals', en:'back then', note:'' },
  { ch:'K6', de:'früher', en:'in the past / used to', note:'' },
  { ch:'K6', de:'plötzlich', en:'suddenly', note:'' },
  { ch:'K6', de:'zuerst / danach / schließlich', en:'first / afterwards / finally', note:'' },
  { ch:'K6', de:'verbringen', en:'to spend (time)', note:'hat verbracht.' },
  { ch:'K6', de:'passieren', en:'to happen', note:'ist passiert — sein!' },
  { ch:'K6', de:'erzählen', en:'to tell (a story)', note:'hat erzählt.' },
  { ch:'K6', de:'besuchen', en:'to visit', note:'hat besucht (no ge-).' },
  { ch:'K6', de:'vergessen', en:'to forget', note:'hat vergessen (no ge-).' },
  { ch:'K6', de:'einladen', en:'to invite', note:'hat eingeladen (separable).' },

  { ch:'K7', de:'das Café / Kaffeehaus', en:'café / coffeehouse', note:'Viennese tradition.' },
  { ch:'K7', de:'die Melange', en:'Viennese coffee w/ steamed milk', note:'' },
  { ch:'K7', de:'der Kellner / die Kellnerin', en:'waiter / waitress', note:'' },
  { ch:'K7', de:'die Rechnung', en:'the bill / check', note:'' },
  { ch:'K7', de:'das Trinkgeld', en:'tip (gratuity)', note:'' },
  { ch:'K7', de:'bestellen', en:'to order', note:'' },
  { ch:'K7', de:'empfehlen', en:'to recommend', note:'er empfiehlt (Stammvokalwechsel).' },
  { ch:'K7', de:'die Speisekarte', en:'menu', note:'' },
  { ch:'K7', de:'die Vorspeise', en:'starter / appetizer', note:'' },
  { ch:'K7', de:'das Hauptgericht', en:'main course', note:'' },
  { ch:'K7', de:'die Nachspeise', en:'dessert', note:'' },
  { ch:'K7', de:'gemütlich', en:'cozy / pleasant', note:'' },
  { ch:'K7', de:'geöffnet / geschlossen', en:'open / closed', note:'' },

  { ch:'K8', de:'die Umwelt', en:'environment', note:'' },
  { ch:'K8', de:'die Umweltverschmutzung', en:'environmental pollution', note:'' },
  { ch:'K8', de:'der Klimawandel', en:'climate change', note:'' },
  { ch:'K8', de:'die Nachhaltigkeit', en:'sustainability', note:'nachhaltig = sustainable.' },
  { ch:'K8', de:'erneuerbare Energien', en:'renewable energies', note:'' },
  { ch:'K8', de:'der Müll / der Abfall', en:'garbage / waste', note:'' },
  { ch:'K8', de:'schützen', en:'to protect', note:'' },
  { ch:'K8', de:'verbrauchen', en:'to consume / use up', note:'' },
  { ch:'K8', de:'sparen', en:'to save', note:'' },
  { ch:'K8', de:'trennen', en:'to separate (trash etc.)', note:'Müll trennen.' },
  { ch:'K8', de:'die Gleichberechtigung', en:'equal rights', note:'' },
  { ch:'K8', de:'die Demokratie', en:'democracy', note:'' },
  { ch:'K8', de:'wählen', en:'to vote / elect', note:'die Wahl = election.' },
  { ch:'K8', de:'das Gesetz', en:'law', note:'pl: Gesetze.' },
  { ch:'K8', de:'die Regierung', en:'government', note:'' },
  { ch:'K8', de:'die Gesellschaft', en:'society', note:'' },
  { ch:'K8', de:'die Bewerbung', en:'job application', note:'sich bewerben.' },
  { ch:'K8', de:'der Lebenslauf', en:'résumé / CV', note:'' },
  { ch:'K8', de:'das Vorstellungsgespräch', en:'job interview', note:'' },
  { ch:'K8', de:'das Gehalt', en:'salary', note:'' },
  { ch:'K8', de:'einstellen', en:'to hire', note:'stellt ein.' },
  { ch:'K8', de:'kündigen', en:'to quit / fire', note:'' },
  { ch:'K8', de:'die Ausbildung', en:'vocational training', note:'' },
  { ch:'K8', de:'die Stelle', en:'position / job', note:'' },
  { ch:'K8', de:'umziehen', en:'to move (residence)', note:'ist umgezogen.' },

  // K8 · K8.6–8.10 extras (Auto/Mobilität, Sprache, Komposita, Avantgarde, Utopie/Dystopie)
  { ch:'K8', de:'das Auto / Auto fahren', en:'car / to drive a car', note:'selbstfahrendes Auto = self-driving car.' },
  { ch:'K8', de:'die Mobilität', en:'mobility', note:'' },
  { ch:'K8', de:'die Zukunft', en:'future', note:'in der Zukunft.' },
  { ch:'K8', de:'die Erfindung', en:'invention', note:'erfinden, der Erfinder.' },
  { ch:'K8', de:'die Innovation', en:'innovation', note:'Jugend forscht.' },
  { ch:'K8', de:'die Sprache', en:'language', note:'Sprache im Wandel der Zeit.' },
  { ch:'K8', de:'das Lehnwort / Fremdwort', en:'loanword / foreign word', note:'Anglizismen: googeln, leaken, chillen, updaten.' },
  { ch:'K8', de:'die Jugendsprache', en:'youth slang', note:'Jugendwort des Jahres.' },
  { ch:'K8', de:'das Kompositum (pl. Komposita)', en:'compound word', note:'Sonnenuntergang = die Tageszeit, zu der die Sonne untergeht.' },
  { ch:'K8', de:'der Sonnenuntergang', en:'sunset', note:'Klassisches Komposita-Beispiel.' },
  { ch:'K8', de:'die Avantgarde', en:'avant-garde', note:'innovativ, provokativ, unkonventionell, revolutionär.' },
  { ch:'K8', de:'innovativ / provokativ / unkonventionell', en:'innovative / provocative / unconventional', note:'Adjektive der Avantgarde.' },
  { ch:'K8', de:'der Dadaismus', en:'Dadaism', note:'Hugo Ball, „Karawane" 1916 — gegen jede Sprachregel.' },
  { ch:'K8', de:'das Lautgedicht', en:'sound poem', note:'„Karawane": nur Laute, keine Bedeutung.' },
  { ch:'K8', de:'die Utopie', en:'utopia', note:'' },
  { ch:'K8', de:'die Dystopie', en:'dystopia', note:'Beispiel-Film: Metropolis (Fritz Lang, 1927).' },
  { ch:'K8', de:'„Berlin – Sinfonie der Großstadt"', en:'documentary by Walther Ruttmann (1927)', note:'Tagesrhythmus einer Stadt = Sinfonie.' },
  { ch:'K8', de:'„Metropolis" (Fritz Lang)', en:'1927 expressionist dystopia', note:'Klassiker der deutschen Stummfilm-Dystopie.' },
  { ch:'K8', de:'chancenlos / arbeitslos / autolos', en:'without a chance / unemployed / without cars', note:'-los = ohne X.' },
];

/* ===================== QUIZ (explicit bank) ===================== */
const QUIZ = [
  // --- K5 ---
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Ich komme ___ der Schweiz.',
    opts:['aus','in','nach','zu'], a:0,
    explain:'aus = from (origin). Always Dativ.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Ich wohne ___ einem Jahr in Wien.',
    opts:['vor','seit','nach','für'], a:1,
    explain:'seit = for/since (ongoing action). Present tense + Dativ.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Er kauft immer ___ Aldi ein.',
    opts:['auf','bei','in','zu'], a:1,
    explain:'bei = at (a place/person). Always Dativ.' },
  { set:'K5', tag:'K5 · pronoun', type:'single',
    q:'Ich helfe ___.  (dem Lehrer)',
    opts:['ihn','ihm','er','ihr'], a:1,
    explain:'helfen takes Dativ → ihm for masculine.' },
  { set:'K5', tag:'K5 · 2-way prep', type:'single',
    q:'Das Buch liegt ___ dem Tisch.',
    opts:['auf','auf den','auf die','aufen'], a:0,
    explain:'liegen = state (wo?) → Dativ. auf + dem = auf dem.' },
  { set:'K5', tag:'K5 · 2-way prep', type:'single',
    q:'Ich lege das Buch ___ den Tisch.',
    opts:['auf','auf dem','auf die','auf einem'], a:0,
    explain:'legen = motion (wohin?) → Akkusativ. auf den Tisch.' },
  { set:'K5', tag:'K5 · wo-compound', type:'single',
    q:'___ schreibst du? — Mit einem Stift.',
    opts:['Wofür','Worauf','Womit','Wovon'], a:2,
    explain:'mit → womit.' },
  { set:'K5', tag:'K5 · pronoun', type:'single',
    q:'Das Buch gefällt ___ sehr. (to me)',
    opts:['mich','mir','ich','mein'], a:1,
    explain:'gefallen takes Dativ → mir.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Wir fahren ___ Bahnhof.',
    opts:['zu dem','zum','zur','zu der'], a:1,
    explain:'zu + dem = zum. Masculine Dativ contraction.' },

  // --- K6 ---
  { set:'K6', tag:'K6 · Präteritum', type:'single',
    q:'Als ich ein Kind ___, wohnten wir in Berlin.',
    opts:['bin','war','habe','hatte'], a:1,
    explain:'Präteritum of sein, 1./3. Sg. = war. In narratives use Präteritum of sein/haben/modals.' },
  { set:'K6', tag:'K6 · Perfekt aux', type:'single',
    q:'Ich ___ gestern nach Wien gefahren.',
    opts:['habe','bin','war','hatte'], a:1,
    explain:'fahren = motion → sein. Ich bin gefahren.' },
  { set:'K6', tag:'K6 · Perfekt aux', type:'single',
    q:'Ich ___ einen Apfel gegessen.',
    opts:['habe','bin','war','hatte'], a:0,
    explain:'essen → haben. No motion/change of state.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of telefonieren?',
    opts:['getelefoniert','telefoniert','telefoniergt','getelefonier'], a:1,
    explain:'-ieren verbs take NO ge-: just telefoniert.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of besuchen?',
    opts:['gebesucht','besucht','besuchtet','gebesuch'], a:1,
    explain:'Inseparable prefix be- → NO ge-: besucht.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of aufmachen?',
    opts:['aufgemacht','gemachtauf','aufmachtet','geaufmacht'], a:0,
    explain:'Separable verb: prefix + ge + stem + -t → aufgemacht.' },
  { set:'K6', tag:'K6 · als/wenn/wann', type:'single',
    q:'___ ich jung war, spielte ich Fußball.',
    opts:['Wenn','Als','Wann','Ob'], a:1,
    explain:'als = one-time past event.' },
  { set:'K6', tag:'K6 · als/wenn/wann', type:'single',
    q:'___ ich müde bin, schlafe ich früh.',
    opts:['Als','Wenn','Wann','Dass'], a:1,
    explain:'wenn = recurring condition ("whenever/if") — or future.' },
  { set:'K6', tag:'K6 · weil/denn', type:'single',
    q:'Ich esse, ___ ich Hunger habe. (verb goes to end!)',
    opts:['denn','weil','aber','und'], a:1,
    explain:'weil = subordinating conjunction → verb to end. denn keeps main-clause order.' },
  { set:'K6', tag:'K6 · Modal Präteritum', type:'single',
    q:'Als ich klein war, ___ ich nicht alleine bleiben.',
    opts:['kann','konnte','könnte','gekonnt'], a:1,
    explain:'Präteritum von Modalverben (immer ohne Umlaut): konnte. In Erzählungen wird Präteritum benutzt, sogar gesprochen.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Ich habe meinen Freund ___ . (einladen)',
    opts:['eingeladen','geeinladen','eingeladet','einladet'], a:0,
    explain:'einladen ist trennbar UND stark: prefix + ge + neuer Stamm + -en → eingeladen.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Sie hat ihre Schlüssel ___ . (vergessen)',
    opts:['gevergessen','vergessen','vergesst','vergisst'], a:1,
    explain:'Inseparable prefix ver- → KEIN ge-. Stark: vergessen → vergessen (kein zusätzliches Affix).' },
  { set:'K6', tag:'K6 · sein vs haben', type:'single',
    q:'Was ist gestern ___? — Mein Hund ist krank geworden.',
    opts:['gepassiert','passiert','ist passiert','war passiert'], a:1,
    explain:'passieren = Zustandswechsel → sein (ist passiert). Partizip ohne ge- (-ieren).' },
  { set:'K6', tag:'K6 · als/wenn', type:'single',
    q:'___ ich gestern nach Hause kam, war niemand da. (einmaliges Ereignis)',
    opts:['Wenn','Als','Wann','Ob'], a:1,
    explain:'als = einmaliges Ereignis in der Vergangenheit. wenn = wiederholt oder Bedingung.' },

  // --- K7 ---
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Der Mann, ___ ich kenne, heißt Peter. (masc. Akk)',
    opts:['der','den','dem','dessen'], a:1,
    explain:'Antecedent: masculine. Role in clause: object (Akk) → den.' },
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Die Frau, ___ ich helfe, ist nett. (fem. Dat — helfen!)',
    opts:['die','der','den','dessen'], a:1,
    explain:'helfen takes Dativ → der (fem. Dat).' },
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Die Leute, ___ ich vertraue, sind meine Freunde. (pl. Dat — vertrauen!)',
    opts:['die','denen','den','dessen'], a:1,
    explain:'vertrauen takes Dativ; plural Dativ = denen.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Ich sehe den ___ Mann. (alt, weak decl.)',
    opts:['alter','alte','alten','altes'], a:2,
    explain:'Masculine Akk weak → -en. den alten Mann.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Das ist ein ___ Kind. (klein, mixed decl., Nom n.)',
    opts:['klein','kleiner','kleine','kleines'], a:3,
    explain:'After ein- in Nom neuter → -es. ein kleines Kind.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Ich wohne in einem ___ Haus. (groß, Dat n.)',
    opts:['groß','großes','großen','großer'], a:2,
    explain:'Dativ endings are -en for all genders after ein-.' },
  { set:'K7', tag:'K7 · Komparativ', type:'single',
    q:'Komparativ von "alt"?',
    opts:['alter','älter','alterer','ältester'], a:1,
    explain:'Umlaut + -er: älter.' },
  { set:'K7', tag:'K7 · Superlativ', type:'single',
    q:'Superlativ (predicate) von "gut"?',
    opts:['am gut','am guten','am besten','am bester'], a:2,
    explain:'Irregular: gut → besser → am besten.' },

  // --- K8 ---
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'Wenn ich Zeit ___, würde ich mehr lernen.',
    opts:['habe','hätte','hatte','haben'], a:1,
    explain:'Konjunktiv II of haben = hätte. Wenn + Konj II …, (dann) würde …' },
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'An deiner Stelle ___ ich nach Hause gehen.',
    opts:['werde','würde','wurde','war'], a:1,
    explain:'Konjunktiv II: würde + Infinitiv. Polite/hypothetical.' },
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'Ich ___ gern einen Kaffee, bitte. (polite "would like")',
    opts:['habe','hätte','bin','würde'], a:1,
    explain:'Ich hätte gern… = standard polite request.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Auto ___ repariert. (Present passive)',
    opts:['ist','wird','hat','war'], a:1,
    explain:'Passiv Präsens: werden + Partizip II → wird repariert.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Haus ___ 1920 gebaut. (Past passive — Präteritum)',
    opts:['wird','wurde','ist','hat'], a:1,
    explain:'Passiv Präteritum: wurde + Partizip II.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Buch wird ___ dem Lehrer gelesen. (agent)',
    opts:['mit','von','bei','durch'], a:1,
    explain:'Agent in passive → von + Dativ.' },
  { set:'K8', tag:'K8 · um zu', type:'single',
    q:'Ich lerne Deutsch, ___ in Wien ___ leben.',
    opts:['um … zu','ohne … zu','statt … zu','damit … zu'], a:0,
    explain:'um … zu + Infinitiv = in order to.' },
  { set:'K8', tag:'K8 · ohne/statt zu', type:'single',
    q:'Er ging, ___ Tschüss ___ sagen.',
    opts:['um … zu','ohne … zu','statt … zu','weil … zu'], a:1,
    explain:'ohne … zu + Infinitiv = without doing.' },
  { set:'K8', tag:'K8 · separable+zu', type:'single',
    q:'Sie versucht, die Tür ___.',
    opts:['aufmachen zu','zu aufmachen','aufzumachen','aufmachenzu'], a:2,
    explain:'Separable verb + zu: zu goes BETWEEN prefix and stem → aufzumachen.' },
  { set:'K8', tag:'K8 · Konj II Modalverben', type:'single',
    q:'___ du mir helfen, bitte? (Konj II of können — polite)',
    opts:['Kannst','Konntest','Könntest','Kannst-du'], a:2,
    explain:'Konjunktiv II der Modalverben: können → könnte (Umlaut). Polite request.' },
  { set:'K8', tag:'K8 · Konj II Modalverben', type:'single',
    q:'Konjunktiv II of "müssen" für ich/er ist…',
    opts:['musste','müsste','muss','müssen'], a:1,
    explain:'müssen → müsste (mit Umlaut). Vergleiche Präteritum musste (ohne Umlaut).' },
  { set:'K8', tag:'K8 · Partizip I', type:'single',
    q:'Partizip I von "lesen" (vor einem Substantiv, Nom. n.) ist…',
    opts:['gelesend','lesend','lesendes','lesendem'], a:2,
    explain:'Partizip I = Infinitiv + d (+ Adjektivendung). "ein lesendes Kind" — adj. ending nach ein- Nom. n. = -es.' },
  { set:'K8', tag:'K8 · Partizip I', type:'single',
    q:'"Ein schnell ___ Auto" = ein Auto, das schnell fährt.',
    opts:['fahrend','fahrendes','fahrenden','fahrender'], a:1,
    explain:'fahren → fahrend → mit Adjektivendung: nach "ein" Nom. n. = -es → fahrendes.' },
  { set:'K8', tag:'K8 · Partizip I', type:'single',
    q:'Welcher Satz ist äquivalent zu "Weinende Kinder sind hier"?',
    opts:['Kinder, die weinen, sind hier.','Kinder, die geweint haben, sind hier.','Kinder, die weinen werden, sind hier.','Kinder, die zu weinen, sind hier.'], a:0,
    explain:'Partizip I = aktive, gleichzeitige Handlung → Relativsatz mit Präsens.' },
  { set:'K8', tag:'K8 · Futur', type:'single',
    q:'Wir ___ morgen ins Museum gehen. (Futur)',
    opts:['werden','wurden','würden','sind'], a:0,
    explain:'Futur = werden (Präsens) + Infinitiv am Ende. wir werden … gehen.' },
  { set:'K8', tag:'K8 · Futur', type:'single',
    q:'"Du ___ das verstehen." (Futur, 2. Sg.)',
    opts:['werde','wirst','wird','werdet'], a:1,
    explain:'werden Präsens: ich werde · DU WIRST · er wird · wir werden · ihr werdet · sie werden.' },
  { set:'K8', tag:'K8 · Futur', type:'single',
    q:'Wo steht der Infinitiv im Futur-Satz?',
    opts:['nach werden','vor werden','am Ende des Satzes','immer in der Mitte'], a:2,
    explain:'Futur: werden in V2-Position, Infinitiv am Satzende.' },
  { set:'K8', tag:'K8 · Wenn-Satz real/irreal', type:'single',
    q:'Welcher Satz ist IRREAL (Konjunktiv II)?',
    opts:['Wenn ich müde bin, schlafe ich.','Wenn ich Hunger habe, esse ich eine Banane.','Wenn ich müde wäre, würde ich schlafen.','Wenn das Wetter schön ist, gehen wir ins Café.'], a:2,
    explain:'Real (Indikativ) = "wenn ich müde bin"; irreal (Konj II) = "wenn ich müde wäre, würde ich…". Aus K8.7.' },
  { set:'K8', tag:'K8 · -los Suffix', type:'single',
    q:'„chancenlos" bedeutet…',
    opts:['mit Chance','ohne Chance','viele Chancen','eine kleine Chance'], a:1,
    explain:'Nomen + los = ohne X. Die Chance + los → ohne Chance. Aus K8.7 ("autolose Sonntag", "Hacker sind chancenlos").' },
  { set:'K8', tag:'K8 · -los Suffix', type:'single',
    q:'„Der ___ Sonntag" = ein Sonntag ohne Autos.',
    opts:['autonomose','autolose','autolosen','ohnelose'], a:1,
    explain:'Auto + los → autolos → autolose (Adj.-Endung m. Nom. nach „der" → -e schwach).' },
  { set:'K8', tag:'K8 · Komposita', type:'single',
    q:'Welcher Relativsatz definiert „der Sonnenuntergang"?',
    opts:['die Person, die die Sonne sieht','die Tageszeit, zu der die Sonne untergeht','das Wetter, das warm ist','der Mond, der scheint'], a:1,
    explain:'Komposita-Definition mit Relativsatz: Sonnenuntergang = die Tageszeit, zu der die Sonne (jeden Abend) untergeht. Aus K8.8.' },
  { set:'K8', tag:'K8 · Komposita', type:'single',
    q:'Welcher Artikel hat ein Kompositum?',
    opts:['immer der','immer die','der Artikel des ERSTEN Bestandteils','der Artikel des LETZTEN Bestandteils'], a:3,
    explain:'Kompositum bekommt das Genus des LETZTEN Wortes. das Sommer + die Hitze → die Sommerhitze.' },
  { set:'K8', tag:'K8 · Lehnwörter', type:'multi',
    q:'Welche sind Anglizismen / Lehnwörter im Deutschen? (alle wählen)',
    opts:['googeln','sprechen','leaken','schreiben','updaten','chillen'],
    a:[0,2,4,5],
    explain:'Aus K8.8: googeln, leaken, updaten, chillen — englische Verben werden mit deutscher Verb-Endung integriert.' },
  { set:'K8', tag:'K8 · Partizip I (Adj.)', type:'single',
    q:'„Ein Hund, der schläft" → ein ___ Hund. (m. Nom. nach „ein")',
    opts:['schlafend','schlafende','schlafender','schlafendes'], a:2,
    explain:'schlafen → schlafend → mixed Dekl. m. Nom. = -er. ein schlafender Hund.' },
  { set:'K8', tag:'K8 · Partizip I (Adj.)', type:'single',
    q:'„Kinder, die Eis essen" → ___ Kinder (Pl. Nom., kein Artikel)',
    opts:['Eis essende','Eis essender','Eis essendes','Eis essenden'], a:0,
    explain:'starke Pl. Nom. ohne Artikel → -e. Eis essende Kinder. Aus K8.9.' },
  { set:'K8', tag:'K8 · Partizip I (Adj.)', type:'single',
    q:'„Der ___ Papagei ist in die ___ Katze verliebt." (sprechen / singen, m. Nom. + f. Akk., bestimmter Artikel)',
    opts:['sprechende … singende','sprechender … singende','sprechende … singender','sprechender … singender'], a:0,
    explain:'Schwache Dekl. nach „der/die": m. Nom. → -e (sprechende), f. Akk. → -e (singende). Aus K8.9.' },
  { set:'K8', tag:'K8 · Avantgarde', type:'multi',
    q:'Welche Adjektive beschreiben Avantgarde-Kunst? (alle wählen)',
    opts:['konservativ','innovativ','provokativ','konventionell','revolutionär','sozialkritisch'],
    a:[1,2,4,5],
    explain:'Avantgarde-Adjektive aus K8.10: innovativ, progressiv, provokativ, unkonventionell, revolutionär, sozialkritisch — NICHT konservativ/konventionell.' },
  { set:'K8', tag:'K8 · Dadaismus', type:'single',
    q:'„Karawane" (1916, Hugo Ball) ist…',
    opts:['ein Liebesgedicht','ein Lautgedicht ohne Bedeutung — gegen jede Sprachregel','ein politisches Manifest','ein Roman'], a:1,
    explain:'Dadaismus / Avantgarde: keine Bedeutung, keine Grammatik, nur Laute. Hugo Ball war Mitbegründer von Dada. Aus K8.10.' },
  { set:'K8', tag:'K8 · Utopie/Dystopie', type:'single',
    q:'„Metropolis" (Fritz Lang, 1927) ist ein Beispiel für…',
    opts:['eine Utopie','eine Dystopie','einen Dokumentarfilm','eine Komödie'], a:1,
    explain:'Metropolis = Klassiker der deutschen Stummfilm-DYSTOPIE. Utopie = ideale Gesellschaft; Dystopie = Albtraumgesellschaft. Aus K8.10.' },
  { set:'K8', tag:'K8 · Berlin Symphony', type:'single',
    q:'„Berlin – Die Sinfonie der Großstadt" (1927) ist…',
    opts:['ein Musical','ein Dokumentarfilm von Walther Ruttmann','ein Roman von Fritz Lang','ein Theaterstück'], a:1,
    explain:'Walther Ruttmann, 1927 — Dokumentarfilm über Berlin in den 1920ern. Tagesrhythmus = Sinfonie. Aus K8.9.' },
  { set:'K8', tag:'K8 · Auto/Mobilität', type:'single',
    q:'„Mein Traumauto wäre ein Auto, das selbst fährt." Welche Struktur ist hier am Werk?',
    opts:['Passiv','Konjunktiv II + Relativsatz','Futur + Modalverb','Perfekt'], a:1,
    explain:'wäre = Konj II von sein, „das selbst fährt" = Relativsatz. Beides in K8.6.' },

  // --- Mixed final prep ---
  { set:'mixed', tag:'mixed', type:'single',
    q:'Wenn ich du ___, würde ich mehr schlafen.',
    opts:['bin','war','wäre','gewesen'], a:2,
    explain:'Konjunktiv II of sein = wäre.' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Ich bin gestern ins Kino ___.',
    opts:['gehen','gegangen','gegehen','geht'], a:1,
    explain:'Strong Partizip II: gehen → gegangen. sein!' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Die Umwelt muss ___ werden.',
    opts:['schützen','geschützt','schützte','zu schützen'], a:1,
    explain:'Passive with modal: modal + Partizip II + werden. muss geschützt werden.' },
  { set:'mixed', tag:'mixed', type:'multi',
    q:'Which prepositions are ALWAYS Dativ? (select all)',
    opts:['aus','bei','für','mit','nach','ohne','seit','von','zu'],
    a:[0,1,3,4,6,7,8],
    explain:'Dative-only: aus, außer, bei, mit, nach, seit, von, zu. für and ohne are Akkusativ-only.' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Das Kind, ___ Mutter Ärztin ist, heißt Anna.',
    opts:['das','dessen','deren','der'], a:1,
    explain:'Genitive relative pronoun for neuter/masculine = dessen. (K7 extension.)' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Present tense active → present passive: "Der Lehrer liest das Buch."',
    opts:['Das Buch wird gelesen.','Das Buch ist gelesen.','Das Buch wird lesen.','Das Buch war gelesen.'], a:0,
    explain:'Passiv Präsens: wird + Partizip II.' },
  { set:'mixed', tag:'mixed · Akk. Präp.', type:'multi',
    q:'Welche Präpositionen sind IMMER Akkusativ? (dogfud — alle wählen)',
    opts:['durch','mit','ohne','gegen','seit','für','um','aus'],
    a:[0,2,3,5,6],
    explain:'Akkusativ-only: durch · ohne · gegen · für · um (Mnemonic: dogfud).' },
  { set:'mixed', tag:'mixed · V2-Regel', type:'single',
    q:'"Heute Abend ___ wir ins Kino." Welches Verb steht in zweiter Position?',
    opts:['gehen','geht','wir gehen','ist'], a:0,
    explain:'V2-Regel: konjugiertes Verb bleibt in 2. Position, auch wenn der Satz nicht mit dem Subjekt beginnt.' },
  { set:'mixed', tag:'mixed · V2-Regel', type:'single',
    q:'Welcher Satz ist eine AUSNAHME zur V2-Regel (Verb zuerst)?',
    opts:['Heute gehen wir ins Kino.','Wohnst du in New York?','Meine Freundin und ich gehen.','Warum gehen wir?'], a:1,
    explain:'Ja/Nein-Fragen UND Imperative haben das konjugierte Verb in Position 1.' },
  { set:'mixed', tag:'mixed · Adjektiv', type:'single',
    q:'"Der Glühwein ___ heiß." Welche Adjektivendung?',
    opts:['heiß (keine Endung)','heißer','heißen','heißes'], a:0,
    explain:'Nach "sein" (Prädikatsadjektiv) → KEINE Endung. Nur attributive Adjektive (vor dem Substantiv) bekommen Endungen.' },
  { set:'mixed', tag:'mixed · Adjektiv', type:'single',
    q:'"Wir haben ___ Glühwein getrunken." (heiß, keine Artikel, Akk. m.)',
    opts:['heiß','heißen','heißer','heißes'], a:1,
    explain:'Ohne Artikel (starke Deklination) Akkusativ maskulin → -en. Beispiel: heißen Glühwein.' },
  { set:'mixed', tag:'mixed · Konjunktion', type:'single',
    q:'Welche ist eine KOORDINIERENDE Konjunktion (Verb bleibt in V2)?',
    opts:['weil','dass','denn','wenn'], a:2,
    explain:'Koordinierende: und, oder, denn, aber, sondern (0-Position, Verb bleibt V2). Subordinierende sind Kicker → Verb ans Ende.' },
  { set:'mixed', tag:'mixed · Konjunktion', type:'single',
    q:'"Schultze fährt nach Amerika, ___ er Cajun Musik liebt." (Verb am Ende!)',
    opts:['denn','und','aber','weil'], a:3,
    explain:'weil ist subordinierend (Kicker) → liebt am Ende. denn würde V2-Wortstellung erfordern.' },
  { set:'mixed', tag:'mixed · Imperativ', type:'single',
    q:'Imperativ (du-Form) von "trinken": "___ mehr Milch!"',
    opts:['Trinkst','Trink','Trinke du','Du trinkst'], a:1,
    explain:'Imperativ du-Form: Verbstamm ohne -st (Trink!). Verb in Position 1 — Subjekt fällt weg.' },
  { set:'mixed', tag:'mixed · Relativsatz', type:'single',
    q:'"Das ist meine Freundin, ___ ich Yoga mache." (mit + Relativpronomen, fem.)',
    opts:['die','der','mit der','mit die'], a:2,
    explain:'mit ist Dativ-Präposition → "mit der" (fem. Dativ). Präpositionen MIT Relativpronomen.' },
  { set:'mixed', tag:'mixed · Reflexiv', type:'single',
    q:'"Ich ___ jeden Morgen." (sich duschen — reflexiv)',
    opts:['dusche mich','duscht mich','duschen mich','mich dusche'], a:0,
    explain:'Reflexives Verb: sich duschen → ich dusche mich (Akk-Reflexivpronomen).' },
];

/* ===================== GRAMMAR tables ===================== */
const GRAMMAR = [
  {
    title: 'Subordinating conjunctions — dass / weil / wenn / als',
    sub:   'Verb moves to END of clause (Verbendstellung)',
    rows: [
      ['Word','Meaning','Example'],
      ['dass','that','Ich finde, dass Bananen lecker sind.'],
      ['weil','because (verb → end)','Ich esse, weil ich Hunger habe.'],
      ['wenn','when / if (recurring or future)','Wenn ich müde bin, schlafe ich.'],
      ['als','when (one-time past event)','Als ich jung war, wohnte ich in Berlin.'],
      ['denn','because (keeps main-clause order)','Ich esse, denn ich habe Hunger.'],
    ]
  },
  {
    title: 'Modal verbs — present tense',
    sub: 'Conjugated modal in V2, Infinitive at end: Ich muss Deutsch lernen.',
    rows: [
      ['Verb','Meaning','ich','du','er/sie/es','wir/sie/Sie'],
      ['können','can','kann','kannst','kann','können'],
      ['wollen','want to','will','willst','will','wollen'],
      ['müssen','must','muss','musst','muss','müssen'],
      ['dürfen','may','darf','darfst','darf','dürfen'],
      ['sollen','should','soll','sollst','soll','sollen'],
      ['möchten','would like','möchte','möchtest','möchte','möchten'],
    ]
  },
  {
    title: 'Two-way prepositions (Wechselpräpositionen)',
    sub: 'Wo? → Dativ · Wohin? → Akkusativ · in·auf·unter·über·neben·zwischen·hinter·an·vor',
    rows: [
      ['State verbs (Dativ)','Motion verbs (Akkusativ)'],
      ['liegen · stehen · hängen · sitzen','legen · stellen · hängen · setzen'],
      ['Das Buch liegt auf dem Tisch.','Ich lege das Buch auf den Tisch.'],
    ]
  },
  {
    title: 'Dative-only prepositions',
    sub: 'aus · außer · bei · mit · nach · seit · von · zu',
    rows: [
      ['Prep.','Meaning','Example'],
      ['aus','from; made of','Ich komme aus der Schweiz.'],
      ['bei','at, near, with','Ich kaufe bei Aldi ein.'],
      ['mit','with','Ich esse mit meiner Mutter.'],
      ['nach','after; to (cities)','Nach dem Unterricht trinken wir Kaffee.'],
      ['seit','since / for (ongoing)','Seit einem Jahr lebe ich hier.'],
      ['von','from / of','Das Buch ist vom Lehrer.'],
      ['zu','to (nearby)','Wir fahren zum Bahnhof.'],
    ]
  },
  {
    title: 'Da- and Wo-compounds',
    sub: 'For THINGS (not people). da(r)+prep = "with it" · wo(r)+prep = "with what?"',
    rows: [
      ['Prep.','Da-form','Wo-form'],
      ['mit','damit','womit'],
      ['für','dafür','wofür'],
      ['auf','darauf','worauf'],
      ['über','darüber','worüber'],
      ['an','daran','woran'],
      ['von','davon','wovon'],
    ]
  },
  {
    title: 'Personal pronouns — Nom / Akk / Dat',
    sub: '',
    rows: [
      ['Person','Nom','Akk','Dat'],
      ['ich','ich','mich','mir'],
      ['du','du','dich','dir'],
      ['er','er','ihn','ihm'],
      ['sie (f)','sie','sie','ihr'],
      ['es','es','es','ihm'],
      ['wir','wir','uns','uns'],
      ['ihr','ihr','euch','euch'],
      ['sie / Sie','sie / Sie','sie / Sie','ihnen / Ihnen'],
    ]
  },
  {
    title: 'Präteritum: sein & haben',
    sub: 'In narratives, sein/haben and modals stay in Präteritum even in speech.',
    rows: [
      ['Person','sein','haben'],
      ['ich','war','hatte'],
      ['du','warst','hattest'],
      ['er/sie/es','war','hatte'],
      ['wir','waren','hatten'],
      ['ihr','wart','hattet'],
      ['sie / Sie','waren','hatten'],
    ]
  },
  {
    title: 'Perfekt — Partizip II formation',
    sub: 'sein for motion/change-of-state. haben for most others.',
    rows: [
      ['Type','Pattern','Example'],
      ['Regular (weak)','ge- + stem + -t','kaufen → gekauft'],
      ['Irregular (strong)','ge- + new stem + -en','gehen → gegangen'],
      ['-ieren verbs','stem + -iert (no ge-)','telefonieren → telefoniert'],
      ['Inseparable prefix','no ge-','besuchen → besucht'],
      ['Separable prefix','prefix + ge + stem','aufmachen → aufgemacht'],
    ]
  },
  {
    title: 'Key strong verbs — Partizip II + aux',
    sub: 'Memorize these; they appear constantly.',
    rows: [
      ['Verb','Partizip II','Aux'],
      ['gehen','gegangen','sein'],
      ['fahren','gefahren','sein'],
      ['kommen','gekommen','sein'],
      ['bleiben','geblieben','sein'],
      ['werden','geworden','sein'],
      ['sein','gewesen','sein'],
      ['essen','gegessen','haben'],
      ['trinken','getrunken','haben'],
      ['schreiben','geschrieben','haben'],
      ['sprechen','gesprochen','haben'],
      ['denken','gedacht','haben'],
      ['bringen','gebracht','haben'],
      ['lesen','gelesen','haben'],
      ['sehen','gesehen','haben'],
    ]
  },
  {
    title: 'als / wenn / wann',
    sub: '',
    rows: [
      ['Word','Use','Example'],
      ['als','one-time past event','Als ich ein Kind war, wohnte ich in Berlin.'],
      ['wenn','recurring or if/whenever','Wenn ich müde bin, schlafe ich früh.'],
      ['wann','question word (when?)','Wann kommst du?'],
    ]
  },
  {
    title: 'Adjective endings — weak (after der/die/das)',
    sub: '',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','-e','-e','-e','-en'],
      ['Akk','-en','-e','-e','-en'],
      ['Dat','-en','-en','-en','-en'],
    ]
  },
  {
    title: 'Adjective endings — mixed (after ein/kein/mein)',
    sub: '',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','-er','-e','-es','-en'],
      ['Akk','-en','-e','-es','-en'],
      ['Dat','-en','-en','-en','-en'],
    ]
  },
  {
    title: 'Relative pronouns (Relativpronomen)',
    sub: 'Gender = antecedent. Case = role in the relative clause. Verb → end.',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','der','die','das','die'],
      ['Akk','den','die','das','die'],
      ['Dat','dem','der','dem','denen'],
      ['Gen','dessen','deren','dessen','deren'],
    ]
  },
  {
    title: 'Komparativ & Superlativ',
    sub: 'Regular: adj + -er | Superlative predicate: am + adj + -sten',
    rows: [
      ['Base','Komparativ','Superlativ (predicate)'],
      ['schnell','schneller','am schnellsten'],
      ['groß','größer','am größten'],
      ['alt','älter','am ältesten'],
      ['jung','jünger','am jüngsten'],
      ['gut','besser','am besten'],
      ['viel','mehr','am meisten'],
      ['gern','lieber','am liebsten'],
      ['hoch','höher','am höchsten'],
    ]
  },
  {
    title: 'Konjunktiv II — hypothetical / polite',
    sub: 'würde + Infinitiv for most. Irregular: wäre, hätte, könnte, müsste, sollte.',
    rows: [
      ['Person','würde','wäre','hätte','könnte'],
      ['ich','würde','wäre','hätte','könnte'],
      ['du','würdest','wärst','hättest','könntest'],
      ['er/sie/es','würde','wäre','hätte','könnte'],
      ['wir','würden','wären','hätten','könnten'],
      ['ihr','würdet','wärt','hättet','könntet'],
      ['sie / Sie','würden','wären','hätten','könnten'],
    ]
  },
  {
    title: 'Konjunktiv II der Modalverben',
    sub: 'Umlaut für können / müssen / dürfen — KEIN Umlaut für wollen / sollen.',
    rows: [
      ['Modal','Konj II','Beispiel'],
      ['können','könnte','Könntest du mir helfen?'],
      ['müssen','müsste','Ich müsste mehr lernen.'],
      ['dürfen','dürfte','Dürfte ich fragen?'],
      ['wollen','wollte','Ich wollte gehen.'],
      ['sollen','sollte','Du solltest schlafen.'],
    ]
  },
  {
    title: 'Partizip I — als Adjektiv',
    sub: 'Form: Infinitiv + d (+ Adjektivendung) · = Relativsatz mit "der/die/das …"',
    rows: [
      ['Verb','Partizip I','Beispiel = Relativsatz'],
      ['fahren','fahrend','ein schnell fahrendes Auto = ein Auto, das schnell fährt'],
      ['sprechen','sprechend','eine laut sprechende Professorin = eine Professorin, die laut spricht'],
      ['protestieren','protestierend','ein protestierender Student = ein Student, der protestiert'],
      ['weinen','weinend','weinende Kinder = Kinder, die weinen'],
      ['lesen','lesend','ein lesendes Kind = ein Kind, das liest'],
    ]
  },
  {
    title: 'Futur — werden + Infinitiv',
    sub: 'werden in V2-Position, Infinitiv am Satzende. Achtung: werden auch für Passiv!',
    rows: [
      ['Person','werden (Präsens)','Beispiel'],
      ['ich','werde','Ich werde Deutsch lernen.'],
      ['du','wirst','Du wirst das verstehen.'],
      ['er/sie/es','wird','Sie wird in Wien wohnen.'],
      ['wir','werden','Wir werden heute in die Galerie gehen.'],
      ['ihr','werdet','Ihr werdet müde sein.'],
      ['sie / Sie','werden','Sie werden bald kommen.'],
    ]
  },
  {
    title: 'Wortstellung — V2-Regel & Ausnahmen',
    sub: 'Konjugiertes Verb in 2. Position — Subjekt + Verb sind unzertrennlich, auch wenn ein anderes Element vorne steht.',
    rows: [
      ['Satztyp','Verb-Position','Beispiel'],
      ['Aussagesatz (Subjekt vorne)','V2','Meine Freundin und ich gehen heute Abend ins Kino.'],
      ['Aussagesatz (Element vorne)','V2 (Verb VOR Subjekt)','Heute Abend gehen meine Freundin und ich ins Kino.'],
      ['W-Frage','V2','Warum gehen wir heute Abend ins Kino?'],
      ['Ja/Nein-Frage (Ausnahme)','V1','Wohnst du in New York?'],
      ['Imperativ (Ausnahme)','V1, kein Subjekt','Trink mehr Milch! / Kommen Sie nach New York!'],
      ['Subord. Konj. (Kicker)','konj. Verb am Ende','Ich esse, weil ich Hunger habe.'],
    ]
  },
  {
    title: 'Akkusativ-Präpositionen — "dogfud"',
    sub: 'durch · ohne · gegen · für · um — IMMER Akkusativ.',
    rows: [
      ['Prep.','Bedeutung','Beispiel'],
      ['durch','through','durch den Park'],
      ['ohne','without','ohne meinen Computer'],
      ['gegen','against','gegen die Wand'],
      ['für','for','für meinen Freund'],
      ['um','around / at (time)','um die Ecke / um 10 Uhr'],
    ]
  },
  {
    title: 'Passiv',
    sub: 'werden + Partizip II · Agent: von + Dativ',
    rows: [
      ['Tense','Structure','Example'],
      ['Präsens','wird + PP','Das Buch wird gelesen.'],
      ['Präteritum','wurde + PP','Das Buch wurde gelesen.'],
      ['Perfekt','ist + PP + worden','Das Buch ist gelesen worden.'],
      ['Modal + Passiv','modal + PP + werden','Das Buch muss gelesen werden.'],
    ]
  },
  {
    title: 'Infinitivkonstruktionen',
    sub: 'zu + Infinitiv at clause end. Separable verb: zu goes between prefix and stem → aufzumachen.',
    rows: [
      ['Construction','Meaning','Example'],
      ['um … zu','in order to','Ich lerne Deutsch, um in Wien zu leben.'],
      ['ohne … zu','without doing','Er ging, ohne zu sagen.'],
      ['statt … zu','instead of doing','Statt zu lernen, schlief er.'],
    ]
  },
];

/* ===================== K8 focus page ===================== */
const K8_SECTIONS = [
  {
    title: 'Key grammar structures',
    flavor: 'purple',
    items: [
      { de:'Konjunktiv II', en:'würde + Inf · wäre · hätte · könnte', note:'Wenn ich Zeit hätte, würde ich lernen.' },
      { de:'Passiv Präsens', en:'wird + Partizip II', note:'Das Essen wird gekocht.' },
      { de:'Passiv Präteritum', en:'wurde + Partizip II', note:'Das Essen wurde gekocht.' },
      { de:'um … zu', en:'in order to', note:'Ich lerne, um zu bestehen.' },
      { de:'ohne … zu', en:'without doing', note:'Er ging, ohne zu fragen.' },
      { de:'statt … zu', en:'instead of doing', note:'Statt zu lernen, schlief er.' },
    ]
  },
  {
    title: 'Konjunktiv II phrases to know',
    flavor: 'normal',
    items: [
      { de:'Ich wäre gern reich.', en:'I would like to be rich.' },
      { de:'Wenn ich Zeit hätte…', en:'If I had time…' },
      { de:'Könntest du mir helfen?', en:'Could you help me?' },
      { de:'Ich würde gern reisen.', en:'I would like to travel.' },
      { de:'An deiner Stelle würde ich…', en:'If I were in your place, I would…' },
      { de:'Es wäre schön, wenn…', en:'It would be nice if…' },
      { de:'Ich hätte gern einen Kaffee.', en:"I'd like a coffee. (polite)" },
      { de:'Dürfte ich…?', en:'Would I be permitted to…?' },
    ]
  },
  {
    title: 'Umwelt & Gesellschaft',
    flavor: 'normal',
    items: [
      { de:'die Umwelt', en:'environment' },
      { de:'die Umweltverschmutzung', en:'environmental pollution' },
      { de:'der Klimawandel', en:'climate change' },
      { de:'die Nachhaltigkeit', en:'sustainability' },
      { de:'erneuerbare Energien', en:'renewable energies' },
      { de:'schützen', en:'to protect' },
      { de:'die Gleichberechtigung', en:'equal rights' },
      { de:'die Demokratie', en:'democracy' },
      { de:'wählen', en:'to vote / elect', note:'die Wahl = the election.' },
      { de:'das Gesetz', en:'law (pl: Gesetze)' },
      { de:'die Regierung', en:'government' },
      { de:'verbrauchen', en:'to consume / use up' },
    ]
  },
  {
    title: 'Beruf & Arbeit',
    flavor: 'normal',
    items: [
      { de:'die Bewerbung', en:'job application', note:'sich bewerben = to apply.' },
      { de:'der Lebenslauf', en:'résumé / CV' },
      { de:'das Vorstellungsgespräch', en:'job interview' },
      { de:'das Gehalt', en:'salary' },
      { de:'einstellen', en:'to hire' },
      { de:'kündigen', en:'to quit / to fire' },
      { de:'die Ausbildung', en:'vocational training' },
      { de:'die Stelle', en:'position / job' },
    ]
  },
  {
    title: 'Mobilität & Zukunft (K8.6)',
    flavor: 'normal',
    items: [
      { de:'das Auto / Auto fahren', en:'car / to drive a car', note:'Mobilität in der Zukunft.' },
      { de:'die Mobilität', en:'mobility' },
      { de:'die Zukunft', en:'future', note:'in der Zukunft.' },
      { de:'die Erfindung / der Erfinder', en:'invention / inventor', note:'erfinden, erfunden.' },
      { de:'die Innovation', en:'innovation', note:'Jugend forscht — youth research competition.' },
      { de:'das selbstfahrende Auto', en:'self-driving car', note:'Partizip I als Adjektiv: „fahrend" + Endung.' },
    ]
  },
  {
    title: 'Sprache im Wandel (K8.8)',
    flavor: 'purple',
    items: [
      { de:'Komposita-Definition', en:'use a relative clause: "der X = die/der/das Y, der/die/das …"', note:'Sonnenuntergang = die Tageszeit, zu der die Sonne (jeden Abend) untergeht.' },
      { de:'Lehnwörter / Anglizismen', en:'googeln, leaken, updaten, chillen, discovern', note:'Englische Verben + deutsche Verb-Endung -en.' },
      { de:'die Jugendsprache', en:'youth slang — "Jugendwort des Jahres" 2023/2024' },
      { de:'Adjektive auf -los', en:'Nomen + los = ohne X', note:'die Chance + los = chancenlos · das Auto + los = der autolose Sonntag.' },
      { de:'Partizip I (lesend, schlafend …)', en:'Infinitiv + d → Adjektiv (mit Endung)', note:'„Der sprechende Papagei ist in die singende Katze verliebt."' },
    ]
  },
  {
    title: 'Avantgarde, Dada & Dystopie (K8.9–8.10)',
    flavor: 'purple',
    items: [
      { de:'Avantgarde-Kunst', en:'innovativ · progressiv · provokativ · unkonventionell · revolutionär · sozialkritisch', note:'Adjektive für Avantgarde-Kunst (K8.10).' },
      { de:'Dadaismus / Hugo Ball „Karawane" (1916)', en:'sound poem — only Laute, no meaning, against every Sprachregel', note:'Dada-Mitbegründer; zeigt Absurdität der Normen.' },
      { de:'„Berlin – Sinfonie der Großstadt" (1927)', en:'documentary film by Walther Ruttmann', note:'Tagesrhythmus einer Stadt = Sinfonie verschiedener „Instrumente".' },
      { de:'die Utopie vs. die Dystopie', en:'ideal society vs. nightmare society' },
      { de:'„Metropolis" (Fritz Lang, 1927)', en:'classic German silent-film DYSTOPIA', note:'Klassiker der expressionistischen Stummfilm-Dystopie.' },
    ]
  },
];

/* ===================== KONJUGATION DRILL =====================
   Type the verb form for a given prompt. Modes:
   Perfekt, Konj II, Modal Konj II, Partizip I, Futur.
   Answer matching is forgiving (case + leading subject pronoun
   optional + accepted variants).
   ============================================================ */
const KONJUGATION = [
  // ---- Perfekt (Partizip II + correct aux) ----
  { mode:'Perfekt', q:'gehen · ich',         a:'bin gegangen',     alt:['ich bin gegangen'],     note:'Bewegung → sein. Stark: gehen → gegangen.' },
  { mode:'Perfekt', q:'essen · ich',         a:'habe gegessen',    alt:['ich habe gegessen'],    note:'haben (kein Zustandswechsel). Stark.' },
  { mode:'Perfekt', q:'fahren · er',         a:'ist gefahren',     alt:['er ist gefahren'],      note:'Bewegung → sein. Stark.' },
  { mode:'Perfekt', q:'bleiben · ich',       a:'bin geblieben',    alt:['ich bin geblieben'],    note:'Zustandsänderung → sein. Stark.' },
  { mode:'Perfekt', q:'werden · sie (3.Sg)', a:'ist geworden',     alt:['sie ist geworden'],     note:'Zustandsänderung → sein. Stark.' },
  { mode:'Perfekt', q:'lesen · ich',         a:'habe gelesen',     alt:['ich habe gelesen'],     note:'Stark: lesen → gelesen.' },
  { mode:'Perfekt', q:'sehen · wir',         a:'haben gesehen',    alt:['wir haben gesehen'],    note:'Stark: sehen → gesehen.' },
  { mode:'Perfekt', q:'sprechen · du',       a:'hast gesprochen',  alt:['du hast gesprochen'],   note:'Stark: sprechen → gesprochen.' },
  { mode:'Perfekt', q:'schreiben · ich',     a:'habe geschrieben', alt:['ich habe geschrieben'], note:'Stark: schreiben → geschrieben.' },
  { mode:'Perfekt', q:'denken · ich',        a:'habe gedacht',     alt:['ich habe gedacht'],     note:'Mischverb: denken → gedacht.' },
  { mode:'Perfekt', q:'telefonieren · sie',  a:'hat telefoniert',  alt:['sie hat telefoniert'],  note:'-ieren-Verben: KEIN ge-.' },
  { mode:'Perfekt', q:'studieren · wir',     a:'haben studiert',   alt:['wir haben studiert'],   note:'-ieren-Verben: KEIN ge-.' },
  { mode:'Perfekt', q:'besuchen · ich',      a:'habe besucht',     alt:['ich habe besucht'],     note:'Insep. be- → KEIN ge-.' },
  { mode:'Perfekt', q:'vergessen · sie',     a:'hat vergessen',    alt:['sie hat vergessen'],    note:'Insep. ver- → KEIN ge-.' },
  { mode:'Perfekt', q:'aufstehen · ich',     a:'bin aufgestanden', alt:['ich bin aufgestanden'], note:'Trennbar + Bewegung: prefix + ge + Stamm + sein.' },
  { mode:'Perfekt', q:'einladen · ich',      a:'habe eingeladen',  alt:['ich habe eingeladen'],  note:'Trennbar + stark.' },
  { mode:'Perfekt', q:'aufmachen · er',      a:'hat aufgemacht',   alt:['er hat aufgemacht'],    note:'Trennbar + schwach: prefix + ge + Stamm + -t.' },

  // ---- Konj II (sein, haben, würde + Inf) ----
  { mode:'Konj II', q:'sein · ich',                    a:'wäre',              note:'Unregelmäßig.' },
  { mode:'Konj II', q:'sein · wir',                    a:'wären' },
  { mode:'Konj II', q:'sein · du',                     a:'wärst',             alt:['wärest'] },
  { mode:'Konj II', q:'haben · ich',                   a:'hätte' },
  { mode:'Konj II', q:'haben · du',                    a:'hättest' },
  { mode:'Konj II', q:'haben · sie (3.Pl)',            a:'hätten' },
  { mode:'Konj II', q:'gehen · ich',                   a:'würde gehen',       alt:['ich würde gehen'], note:'Standardform: würde + Infinitiv.' },
  { mode:'Konj II', q:'lernen · wir',                  a:'würden lernen',     alt:['wir würden lernen'] },
  { mode:'Konj II', q:'reisen · ich (gern)',           a:'würde gern reisen', alt:['ich würde gern reisen'], note:'"gern" zwischen würde und Infinitiv.' },
  { mode:'Konj II', q:'„Ich __ gern einen Kaffee." (polite)', a:'hätte', note:'„Ich hätte gern…" = höflicher Wunsch.' },

  // ---- Modal Konj II (5 Modalverben) ----
  { mode:'Modal Konj II', q:'können · ich',  a:'könnte',  note:'Umlaut!' },
  { mode:'Modal Konj II', q:'können · du',   a:'könntest' },
  { mode:'Modal Konj II', q:'können · wir',  a:'könnten' },
  { mode:'Modal Konj II', q:'müssen · ich',  a:'müsste',  note:'Umlaut. Vergleiche Präteritum musste (ohne Umlaut).' },
  { mode:'Modal Konj II', q:'müssen · du',   a:'müsstest' },
  { mode:'Modal Konj II', q:'dürfen · ich',  a:'dürfte',  note:'Umlaut. Höflich.' },
  { mode:'Modal Konj II', q:'dürfen · ihr',  a:'dürftet' },
  { mode:'Modal Konj II', q:'wollen · ich',  a:'wollte',  note:'KEIN Umlaut. Identisch mit Präteritum.' },
  { mode:'Modal Konj II', q:'sollen · du',   a:'solltest', note:'KEIN Umlaut. „Du solltest mehr schlafen."' },

  // ---- Partizip I als Adjektiv (mit Endung) ----
  { mode:'Partizip I', q:'fahren — vor "Auto" (n. Nom., nach "ein")',         a:'fahrendes',       note:'fahren → fahrend → -es (n. Nom. mixed).' },
  { mode:'Partizip I', q:'sprechen — vor "Professorin" (f. Nom., nach "eine")', a:'sprechende',    note:'-e nach "eine" (f. Nom.).' },
  { mode:'Partizip I', q:'lesen — vor "Kind" (n. Nom., nach "ein")',           a:'lesendes' },
  { mode:'Partizip I', q:'protestieren — vor "Student" (m. Nom., nach "ein")', a:'protestierender', note:'-er nach "ein" (m. Nom. mixed).' },
  { mode:'Partizip I', q:'weinen — vor "Kinder" (Pl. Nom., kein Artikel)',     a:'weinende',        note:'-e starke Pl. Nom.' },
  { mode:'Partizip I', q:'arbeiten — vor "Mann" (m. Nom., nach "ein")',        a:'arbeitender' },

  // ---- Futur (werden + Inf am Ende) ----
  { mode:'Futur', q:'gehen · wir (ins Museum)',     a:'wir werden ins Museum gehen',     note:'werden V2, Infinitiv am Ende.' },
  { mode:'Futur', q:'lernen · ich (Deutsch)',       a:'ich werde Deutsch lernen' },
  { mode:'Futur', q:'verstehen · du (das)',         a:'du wirst das verstehen',          note:'2.Sg.: du wirst (Stammwechsel).' },
  { mode:'Futur', q:'kommen · sie (3.Pl, bald)',    a:'sie werden bald kommen' },
  { mode:'Futur', q:'sein · ihr (müde)',            a:'ihr werdet müde sein',            note:'2.Pl.: ihr werdet.' },

  // ---- Konj II — extras: Wenn-Sätze (real/irreal aus K8.7) ----
  { mode:'Konj II', q:'müde · ich → IRREAL: Wenn ich müde …, … ich schlafen.', a:'wäre, würde', alt:['wäre würde','wäre, würde'], note:'Wenn ich müde wäre, würde ich schlafen. (Konj II beider Verben.)' },
  { mode:'Konj II', q:'Zeit · ich → IRREAL: Wenn ich Zeit …, … ich mehr lesen.', a:'hätte, würde', alt:['hätte würde'], note:'Wenn ich Zeit hätte, würde ich mehr lesen.' },
  { mode:'Konj II', q:'reich · ich → IRREAL: Wenn ich reich …, … ich um die Welt reisen.', a:'wäre, würde', alt:['wäre würde'], note:'Wenn ich reich wäre, würde ich um die Welt reisen.' },

  // ---- Partizip I — extras (mehr Gender-/Artikel-Varianten aus K8.9) ----
  { mode:'Partizip I', q:'schlafen — vor "Hund" (m. Nom., nach "der")',     a:'schlafende',  note:'Schwache Dekl. m. Nom. nach „der" → -e. Der schlafende Hund.' },
  { mode:'Partizip I', q:'singen — vor "Katze" (f. Akk., nach "die")',      a:'singende',    note:'Schwache Dekl. f. Akk. nach „die" → -e. Die singende Katze.' },
  { mode:'Partizip I', q:'sprechen — vor "Papagei" (m. Nom., nach "der")',  a:'sprechende',  note:'Schwache Dekl. m. Nom. nach „der" → -e. Der sprechende Papagei.' },
  { mode:'Partizip I', q:'Eis essen — vor "Kinder" (Pl. Nom., nach "die")', a:'eis essenden', alt:['Eis essenden'], note:'Schwache Pl. Nom. nach „die" → -en. Die Eis essenden Kinder.' },
];

/* ===================== ACTIVE RECALL ====================
   Open-ended prompts grouped by Final-Vorbereitung topic.
   Try to answer aus dem Kopf BEFORE revealing the hint.
   ====================================================== */
const ACTIVE_RECALL = [
  // ----- I. Grammatik aus Kapitel 8 -----
  { cat:'K8 · Konjunktiv II',
    q:'Translate aus dem Kopf: "If I were the King of England, I would drink tea every day."',
    hint:'Wenn ich der König von England wäre, würde ich jeden Tag Tee trinken.\n\n· wenn = Kicker → wäre am Ende des Wenn-Satzes\n· Hauptsatz: würde + Infinitiv (trinken) am Ende' },
  { cat:'K8 · Konjunktiv II',
    q:'Konjugiere wäre und hätte (alle 6 Personen) — diese sind UNREGELMÄSSIG.',
    hint:'wäre: ich wäre · du wärst · er wäre · wir wären · ihr wärt · sie wären\nhätte: ich hätte · du hättest · er hätte · wir hätten · ihr hättet · sie hätten' },
  { cat:'K8 · Konjunktiv II',
    q:'Konj II der 5 Modalverben — und welche 3 bekommen einen Umlaut?',
    hint:'könnte · müsste · dürfte (Umlaut!) · wollte · sollte (KEIN Umlaut)\nFormel: + Infinitiv am Ende. "Du solltest mehr schlafen."' },
  { cat:'K8 · Konjunktiv II',
    q:'Translate: "I would be permitted to wear a hat every day if I were the Queen of Sweden."',
    hint:'Ich dürfte jeden Tag einen Hut tragen, wenn ich die Königin von Schweden wäre.\n\n· dürfte (Konj II von dürfen) + tragen (Inf am Ende)\n· wenn-Satz mit wäre am Ende' },
  { cat:'K8 · Partizip I',
    q:'Wie bildet man Partizip I? Gib die Formel und 2 Beispiele.',
    hint:'Formel: Infinitiv + d (+ Adjektivendung)\n• fahren → fahrend → ein schnell fahrendes Auto\n• weinen → weinend → weinende Kinder\n\nFunktion: wie ein Adjektiv vor einem Substantiv.' },
  { cat:'K8 · Partizip I',
    q:'Schreib "ein protestierender Student" als RELATIVSATZ.',
    hint:'ein Student, der protestiert.\n\n(Partizip I = aktive, gleichzeitige Handlung → "der/die/das + Verb im Präsens")' },
  { cat:'K8 · Partizip I',
    q:'Form mit Partizip I: "a loudly speaking professor" (eine Professorin, die laut spricht).',
    hint:'eine laut sprechende Professorin\n\n· sprechen → sprechend\n· nach "eine" Nom. fem. → -e ending → sprechende' },
  { cat:'K8 · Futur',
    q:'Wie bildet man das Futur? Wo steht der Infinitiv?',
    hint:'werden (Präsens, V2) + Infinitiv AM ENDE.\nBsp.: Wir werden heute in die Neue Galerie gehen.' },
  { cat:'K8 · Futur',
    q:'Konjugiere "werden" im Präsens (alle 6 Personen).',
    hint:'ich werde · du wirst · er/sie/es wird · wir werden · ihr werdet · sie/Sie werden\n\n(Achtung: Stammwechsel du wirst / er wird. werden ist auch das Hilfsverb für Passiv!)' },

  // ----- II. Wiederholtes: Verben & Zeiten -----
  { cat:'Verben · Tenses',
    q:'Bilde Perfekt: gehen, essen, telefonieren, besuchen, aufmachen.',
    hint:'• gehen → ich BIN gegangen (sein, Bewegung)\n• essen → ich HABE gegessen\n• telefonieren → ich habe telefoniert (KEIN ge-)\n• besuchen → ich habe besucht (untrennbar be- → KEIN ge-)\n• aufmachen → ich habe aufgemacht (trennbar: prefix + ge + stem)' },
  { cat:'Verben · Tenses',
    q:'Wann benutzt man Präteritum statt Perfekt im gesprochenen Deutsch?',
    hint:'Auch in der Konversation: sein (war), haben (hatte) und Modalverben (konnte, sollte, musste, wollte, durfte) — KEIN Umlaut im Präteritum!\nIn schriftlichen Erzählungen: alle Verben im Präteritum.' },
  { cat:'Verben · Tenses',
    q:'Trennbares Verb "ankommen" im Präsens-Satz: "I arrive in Berlin at 10."',
    hint:'Ich komme um 10 Uhr in Berlin AN.\n\n(Präfix "an" wandert ans Satzende.)' },
  { cat:'Verben · Reflexiv',
    q:'Konjugiere "sich anziehen" im Präsens (ich/du/er/wir).',
    hint:'ich ziehe MICH an · du ziehst DICH an · er zieht SICH an · wir ziehen UNS an\n\n(Reflexivpronomen + trennbares Verb!)' },

  // ----- II. Nomen & Fälle -----
  { cat:'Fälle · Artikel',
    q:'Bestimmte Artikel in allen 3 Fällen × 4 Genera (12 Formen).',
    hint:'Nom: der · die · das · die\nAkk: den · die · das · die\nDat: dem · der · dem · den (+ -n am Substantiv im Plural!)' },
  { cat:'Fälle · Artikel',
    q:'Unbestimmte Artikel (ein-) in allen 3 Fällen × 4 Genera.',
    hint:'Nom: ein · eine · ein · keine\nAkk: einen · eine · ein · keine\nDat: einem · einer · einem · keinen' },
  { cat:'Fälle · Pronomen',
    q:'Personalpronomen Akk und Dat — alle 8 Personen.',
    hint:'Akk: mich · dich · ihn · sie · es · uns · euch · sie/Sie\nDat: mir · dir · ihm · ihr · ihm · uns · euch · ihnen/Ihnen' },

  // ----- II. Adjektive -----
  { cat:'Adjektive',
    q:'Wann brauchen Adjektive KEINE Endung?',
    hint:'Nach dem Verb "sein" (Prädikatsadjektiv):\n"Der Glühwein WAR heiß." (keine Endung)\n\nVor einem Substantiv (attributiv) brauchen sie IMMER eine Endung.' },
  { cat:'Adjektive',
    q:'Setz die Endungen: "Wir haben heiß__ Glühwein, lecker__ Eis und gut__ Gespräche gehabt." (kein Artikel)',
    hint:'heißEN Glühwein (Akk. m., starke Dekl. → -en)\nleckerES Eis (Akk. n., starke Dekl. → -es)\ngutE Gespräche (Akk. pl., starke Dekl. → -e)' },
  { cat:'Adjektive · Komparativ',
    q:'Komparativ + Superlativ von: groß, alt, gut, viel, gern.',
    hint:'groß → größer → am größten\nalt → älter → am ältesten\ngut → besser → am besten (irregulär!)\nviel → mehr → am meisten (irregulär!)\ngern → lieber → am liebsten (irregulär!)' },

  // ----- II. Konjunktionen -----
  { cat:'Konjunktionen',
    q:'5 koordinierende Konjunktionen — und was passiert mit dem Verb?',
    hint:'und · oder · denn · aber · sondern (nach Negation)\n→ 0-Position: das konjugierte Verb bleibt in zweiter Position.\n"Schultze fährt nach Amerika, denn er LIEBT Cajun Musik."' },
  { cat:'Konjunktionen',
    q:'Subordinierende Konjunktionen ("Kicker"): nenne 3 + Effekt aufs Verb.',
    hint:'dass · weil · wenn (auch: als, ob, obwohl, damit, …)\n→ "kicken" das konjugierte Verb ans Ende des Nebensatzes.\n"Schultze fährt nach Amerika, weil er Cajun Musik LIEBT."' },
  { cat:'Konjunktionen · Relativsatz',
    q:'Relativpronomen mit Präposition: "Das ist meine Freundin, ___ ich Yoga mache." (mit + fem.)',
    hint:'mit der ich Yoga mache.\n\n(mit = Dativ-Präp. → fem. Dativ Relativpronomen "der". Im Relativsatz: Verb am Ende.)' },
  { cat:'Konjunktionen · Relativsatz',
    q:'Komplettiere: "Im Kurs ist ein Student, ___ ich schon lange kenne und ___ mein Freund ist."',
    hint:'…, DEN ich schon lange kenne (Akk. m. — Objekt von "kenne"), und DER mein Freund ist (Nom. m. — Subjekt).' },

  // ----- II. Präpositionen -----
  { cat:'Präpositionen',
    q:'Akkusativ-Präpositionen — die 5 (Mnemonic dogfud)?',
    hint:'durch · ohne · gegen · für · um (d-o-g-f-u-d)\nBsp.: "Ich kann nicht ohne meinen Computer leben."' },
  { cat:'Präpositionen',
    q:'Dativ-Präpositionen — alle 8.',
    hint:'aus · außer · bei · mit · nach · seit · von · zu\nBsp.: "Ich komme MIT meinem Freund AUS der Bibliothek und wir gehen ZUM Kino."\nKontraktionen: zum (zu+dem), zur (zu+der), vom (von+dem), beim (bei+dem).' },
  { cat:'Präpositionen',
    q:'Die 9 Wechselpräpositionen — und welcher Fall wann?',
    hint:'in · auf · unter · über · neben · zwischen · hinter · an · vor\n\nWo? → Dativ (liegen/stehen/hängen): "Das Buch liegt auf DEM Tisch."\nWohin? → Akkusativ (legen/stellen/hängen): "Ich lege das Buch auf DEN Tisch."' },

  // ----- III. Schreiben -----
  { cat:'Schreiben · V2',
    q:'V2-Regel: 3 Beispielsätze (Subjekt vorne / Element vorne / Perfekt).',
    hint:'1. "Meine Freundin und ich GEHEN heute Abend ins Kino."\n2. "Heute Abend GEHEN meine Freundin und ich ins Kino." (Verb VOR Subjekt!)\n3. "Heute Abend SIND meine Freundin und ich ins Kino GEGANGEN." (Hilfsverb V2, Partizip am Ende)' },
  { cat:'Schreiben · V2',
    q:'Welche 2 Satztypen sind AUSNAHMEN zur V2-Regel?',
    hint:'1. Ja/Nein-Fragen → Verb in V1: "Wohnst du in New York?" / "Lesen Sie gerne Shakespeare?"\n2. Imperative → Verb in V1: "Trink mehr Milch!" / "Kommen Sie nach New York!"' },
  { cat:'Schreiben · Stil',
    q:'Tipp aus der Vorbereitung: Wie kann man die Syntax variieren?',
    hint:'Nicht immer mit dem Subjekt anfangen! Konjunktionen benutzen, um Gedanken zu verbinden. Strukturen aus dem Semester verwenden (Konj II, Passiv, Relativsätze, Partizip I, Futur).' },

  // ----- IV. Lesen -----
  { cat:'Lesen · Strategie',
    q:'Welche Strategie für Lesetexte mit Fragen oder richtig/falsch?',
    hint:'1. Titel + visuelle Hinweise → Genre erkennen\n2. Fragen / r-f-Statements ZUERST lesen — so weißt du, worauf du achtest\n3. Text überfliegen (skim) — Hauptthema?\n4. Dann genauer lesen und beantworten' },

  // ----- Extras (Lücken) -----
  { cat:'K8 · Partizip I',
    q:'Schreib drei Partizip-I-Phrasen um in Relativsätze: "ein lachendes Kind", "die schlafende Katze", "ein arbeitender Mann".',
    hint:'• ein lachendes Kind → ein Kind, das lacht\n• die schlafende Katze → die Katze, die schläft\n• ein arbeitender Mann → ein Mann, der arbeitet\n\nFormel: Adjektivendung wird zum Pronomen (Genus + Kasus), Verb im Präsens am Ende.' },
  { cat:'Verben · Trennbar',
    q:'Trennbares Verb in 3 Tempora: aufstehen (ich, jeden Tag / gestern / morgen).',
    hint:'• Präsens: Ich STEHE jeden Tag um 7 Uhr AUF.\n• Perfekt: Ich BIN gestern um 7 Uhr AUFGESTANDEN. (sein!)\n• Futur: Ich WERDE morgen um 7 Uhr AUFSTEHEN. (Infinitiv ans Ende, zusammen!)' },
  { cat:'Schreiben · Negation',
    q:'kein vs. nicht — wann benutzt man was?',
    hint:'kein = negiert Substantive mit ein/kein Artikel: "Ich habe KEIN Geld." / "Sie hat keine Zeit."\nnicht = negiert alles andere (Verben, definite Substantive, Adjektive, ganze Sätze): "Ich gehe NICHT." / "Das ist NICHT mein Auto."' },

  // ----- K8.6–8.10 (Auto, Sprache, Avantgarde, Utopie/Dystopie) -----
  { cat:'K8 · Konjunktiv II',
    q:'Erklär den Unterschied: REALER Wenn-Satz vs. IRREALER Wenn-Satz. Gib 1 Beispiel pro Typ.',
    hint:'REAL (Indikativ): "Wenn ich müde bin, schlafe ich." (= whenever I am tired)\nIRREAL (Konjunktiv II): "Wenn ich müde wäre, würde ich schlafen." (= if I were tired)\n\n→ Real beschreibt eine wirkliche Situation. Irreal beschreibt eine hypothetische / unmögliche Situation. Aus K8.7.' },
  { cat:'K8 · Sprache',
    q:'Definiere „der Sonnenuntergang" mit einem Relativsatz (Komposita-Strategie).',
    hint:'„Der Sonnenuntergang ist die Tageszeit, zu der die Sonne (jeden Abend) untergeht."\n\nKomposita-Definition: das X = die/der/das Y, [Relativsatz]. So kannst du jedes Kompositum erklären, wenn du das Wort selbst nicht erklären kannst. Aus K8.8.' },
  { cat:'K8 · Sprache',
    q:'Was sind „Lehnwörter" und „Anglizismen" im Deutschen? Nenne 4 Beispiele aus K8.8.',
    hint:'Lehnwörter / Fremdwörter / Anglizismen = Wörter aus anderen Sprachen (oft Englisch), die mit deutscher Grammatik integriert werden.\n\n• googeln (← to google)\n• leaken (← to leak)\n• updaten (← to update)\n• chillen (← to chill)\n• discovern (← to discover)\n\nDie Verb-Endung -en macht sie konjugierbar: ich google, du updatest, …' },
  { cat:'K8 · Sprache',
    q:'Adjektive auf -los: bilde 3 Beispiele und erklär die Bedeutung.',
    hint:'Nomen + los = ohne X.\n• die Chance + los → chancenlos = ohne Chance ("Hacker sind fast chancenlos.")\n• das Auto + los → autolos → "der autolose Sonntag" = ein Sonntag ohne Autos\n• die Arbeit + los → arbeitslos = ohne Arbeit (= unemployed)\n• das Heim + los → obdachlos / heimatlos\n\nWichtig: -los wird wie ein normales Adjektiv dekliniert (autolose, autolosen …). Aus K8.7.' },
  { cat:'K8 · Partizip I',
    q:'Schreib „der sprechende Papagei ist in die singende Katze verliebt" — und erklär die Adjektivendungen.',
    hint:'• der sprech-EN-DE Papagei: m. Nom. nach „der" (schwach) → -e\n• die sing-EN-DE Katze: f. Akk. nach „die" (schwach) → -e\n\nMerksatz aus K8.9 (Warm-Up). Partizip I = Infinitiv + d → wie ein Adjektiv mit normaler Endung.' },
  { cat:'K8 · Avantgarde',
    q:'Was charakterisiert Avantgarde-Kunst? Nenne mindestens 4 Adjektive.',
    hint:'innovativ · progressiv · provokativ · unkonventionell · unrealistisch · nicht-stereotypisch · extrem · revolutionär · politisch · protestierend · kritisierend · sozialkritisch.\n\nAvantgarde will gegen Normen, Konventionen, Erwartungen verstoßen — und etwas Neues schaffen. Aus K8.10.' },
  { cat:'K8 · Avantgarde',
    q:'Warum ist Hugo Balls „Karawane" (1916) ein Avantgarde-/Dada-Werk?',
    hint:'„Karawane" hat keine Bedeutung, keine Grammatik, nur Laute — „Nonsense".\n\n→ Es zeigt die Absurdität der Sprachnormen, geht GEGEN jede Sprachregel, und ist deshalb radikal-unkonventionell.\n\nHugo Ball war Mitbegründer des Dadaismus (Cabaret Voltaire, Zürich, 1916). Ein „Lautgedicht". Aus K8.10.' },
  { cat:'K8 · Avantgarde',
    q:'Definiere Utopie und Dystopie. Nenne ein Filmbeispiel für jede.',
    hint:'• Utopie = ideale, perfekte Gesellschaft (Wunschbild).\n• Dystopie = Albtraum-Gesellschaft (Warnung).\n\nFilmbeispiel:\n• „Metropolis" (Fritz Lang, 1927) — DYSTOPIE — Klassiker des deutschen Stummfilms, soziale Spaltung Arbeiter/Elite.\n• „Berlin – Sinfonie der Großstadt" (Walther Ruttmann, 1927) ist KEINE Dystopie, sondern ein DOKUMENTARFILM. Aus K8.10.' },
  { cat:'K8 · Avantgarde',
    q:'Was ist „Berlin – Sinfonie der Großstadt"? Wer hat ihn gemacht und warum heißt er „Sinfonie"?',
    hint:'• Walther Ruttmann, 1927\n• Dokumentarfilm über Berlin in den 1920er Jahren\n• „Sinfonie" weil der Tagesrhythmus einer Stadt klingt wie eine Sinfonie — ein Zusammenspiel von verschiedenen „Instrumenten" (Menschen, Maschinen, Verkehr) mit unterschiedlichem Tempo.\n\nAus K8.9.' },
  { cat:'K8 · Auto/Mobilität',
    q:'Beschreib dein Traumauto (Konjunktiv II). Gib 3 Sätze: was es WÄRE, was es HÄTTE, was es MACHEN WÜRDE.',
    hint:'• „Mein Traumauto WÄRE ein selbstfahrendes Elektroauto."\n• „Es HÄTTE Solarzellen auf dem Dach."\n• „Es WÜRDE mich automatisch zur Uni FAHREN."\n\nKonj II + Inf am Ende. Aus K8.6.' },
];
