/* =====================================================================
   deutsch.lab — content for German II (K5–K8)
   CARDS, VOCAB, QUIZ, GRAMMAR, K8_SECTIONS
   ===================================================================== */

const CARDS = [
  // K5 · Grammar
  { ch:'K5', type:'GR', front:'aus (Präposition)', back:'from a place / made of', note:'Always Dativ: Ich komme aus der Schweiz.' },
  { ch:'K5', type:'GR', front:'seit (Präposition)', back:'since / for (ongoing action)', note:'Use present tense! Seit einem Jahr lerne ich Deutsch.' },
  { ch:'K5', type:'GR', front:'bei (Präposition)', back:"at, near, with / at someone's place", note:'Always Dativ: bei Aldi, bei meiner Mutter.' },
  { ch:'K5', type:'GR', front:'mit (Präposition)', back:'with', note:'Always Dativ: mit meinem Freund.' },
  { ch:'K5', type:'GR', front:'zu (Präposition)', back:'to (a nearby place); for (occasion)', note:'Always Dativ: zum Bahnhof (zu+dem).' },
  { ch:'K5', type:'GR', front:'nach (Präposition)', back:'after; to (cities/countries without article)', note:'nach Berlin, nach dem Unterricht.' },
  { ch:'K5', type:'GR', front:'von (Präposition)', back:'from / of (possession/origin)', note:'Always Dativ: vom Lehrer (von+dem).' },
  { ch:'K5', type:'GR', front:'außer (Präposition)', back:'except for / besides', note:'Always Dativ: Außer mir kommt niemand.' },
  { ch:'K5', type:'GR', front:'womit / damit', back:'with what? / with it (da/wo-compound)', note:'Womit schreibst du? — Damit.' },
  { ch:'K5', type:'GR', front:'wofür / dafür', back:'for what? / for it', note:'Wofür brauchst du das? — Dafür.' },
  { ch:'K5', type:'GR', front:'worauf / darauf', back:'on what? / on it', note:'Worauf wartest du? — Darauf.' },
  { ch:'K5', type:'GR', front:'mich / mir', back:'me (Akk) / me (Dat)', note:'Er kennt mich. | Er gibt mir das Buch.' },
  { ch:'K5', type:'GR', front:'dich / dir', back:'you (Akk) / you (Dat)', note:'Ich sehe dich. | Ich gebe dir das.' },
  { ch:'K5', type:'GR', front:'ihn / ihm', back:'him (Akk) / him (Dat)', note:'Ich kenne ihn. | Ich gebe ihm das Buch.' },
  { ch:'K5', type:'GR', front:'sie / ihr (feminine)', back:'her (Akk) / her (Dat)', note:'Ich sehe sie. | Ich helfe ihr.' },
  { ch:'K5', type:'GR', front:'uns / euch / ihnen', back:'us / you-all / them (Akk = Dat except ihnen)', note:'Dat: uns, euch, ihnen.' },
  { ch:'K5', type:'GR', front:'Two-way prep: wo? vs wohin?', back:'wo? → Dativ (location) · wohin? → Akkusativ (motion into)', note:'in/auf/unter/über/neben/zwischen/hinter/an/vor.' },

  // K5 · Vocab
  { ch:'K5', type:'VO', front:'der Bahnhof', back:'train station' },
  { ch:'K5', type:'VO', front:'die Apotheke', back:'pharmacy' },
  { ch:'K5', type:'VO', front:'das Rathaus', back:'city hall' },
  { ch:'K5', type:'VO', front:'die Bibliothek', back:'library' },
  { ch:'K5', type:'VO', front:'das Krankenhaus', back:'hospital' },
  { ch:'K5', type:'VO', front:'die Post', back:'post office' },
  { ch:'K5', type:'VO', front:'die Bäckerei', back:'bakery' },
  { ch:'K5', type:'VO', front:'helfen (+ Dativ)', back:'to help (dative verb)', note:'Ich helfe dir.' },
  { ch:'K5', type:'VO', front:'gehören (+ Dativ)', back:'to belong to', note:'Das Buch gehört mir.' },
  { ch:'K5', type:'VO', front:'gefallen (+ Dativ)', back:'to please / to like', note:'Das Buch gefällt mir = I like the book.' },
  { ch:'K5', type:'VO', front:'schmecken (+ Dativ)', back:'to taste (good)', note:'Das schmeckt mir.' },

  // K6 · Grammar (Perfekt / Präteritum / conjunctions)
  { ch:'K6', type:'GR', front:'Präteritum: war / waren', back:'was / were (sein)', note:'ich war, du warst, er war, wir waren, ihr wart, sie waren.' },
  { ch:'K6', type:'GR', front:'Präteritum: hatte / hatten', back:'had (haben)', note:'ich hatte, du hattest, er hatte, wir hatten.' },
  { ch:'K6', type:'GR', front:'Perfekt: haben or sein?', back:'sein → motion/change of state. haben → most others.', note:'Ich bin gegangen. | Ich habe gegessen.' },
  { ch:'K6', type:'GR', front:'Partizip II: regular (weak)', back:'ge- + stem + -t', note:'kaufen → gekauft, spielen → gespielt.' },
  { ch:'K6', type:'GR', front:'Partizip II: strong', back:'ge- + (new) stem + -en', note:'gehen → gegangen, sprechen → gesprochen.' },
  { ch:'K6', type:'GR', front:'Partizip II: -ieren verbs', back:'NO ge-: just stem + -iert', note:'telefonieren → telefoniert, studieren → studiert.' },
  { ch:'K6', type:'GR', front:'Partizip II: inseparable prefix (be-/er-/ver-/ent-/emp-/zer-/ge-)', back:'NO ge-', note:'besuchen → besucht, verstehen → verstanden, vergessen → vergessen.' },
  { ch:'K6', type:'GR', front:'Partizip II: separable prefix', back:'ge- goes BETWEEN prefix and stem', note:'aufmachen → aufgemacht, einkaufen → eingekauft.' },
  { ch:'K6', type:'GR', front:'als vs. wenn vs. wann', back:'als = single past event · wenn = recurring/if · wann = question word', note:'Als ich jung war… | Wenn ich müde bin… | Wann kommst du?' },
  { ch:'K6', type:'GR', front:'weil vs. denn', back:'weil → verb to end · denn → normal word order', note:'Ich esse, weil ich Hunger habe. | Ich esse, denn ich habe Hunger.' },
  { ch:'K6', type:'GR', front:'dass', back:'that (conjunction) — verb to end', note:'Ich finde, dass Deutsch schön ist.' },

  // K6 · Vocab
  { ch:'K6', type:'VO', front:'die Kindheit', back:'childhood' },
  { ch:'K6', type:'VO', front:'aufwachsen', back:'to grow up', note:'ist aufgewachsen (sein!).' },
  { ch:'K6', type:'VO', front:'damals', back:'back then / at that time' },
  { ch:'K6', type:'VO', front:'früher', back:'formerly / in the past / used to' },
  { ch:'K6', type:'VO', front:'plötzlich', back:'suddenly' },
  { ch:'K6', type:'VO', front:'zuerst / dann / danach / schließlich', back:'first / then / afterwards / finally' },
  { ch:'K6', type:'VO', front:'verbringen', back:'to spend (time)', note:'hat verbracht.' },
  { ch:'K6', type:'VO', front:'passieren', back:'to happen', note:'ist passiert — sein! Was ist passiert?' },

  // K7 · Grammar (Relativ + Adjektive + Komparativ)
  { ch:'K7', type:'GR', front:'Relativpronomen: masculine', back:'Nom der · Akk den · Dat dem', note:'Der Mann, den ich kenne, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: feminine', back:'Nom die · Akk die · Dat der', note:'Die Frau, der ich helfe, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: neuter', back:'Nom das · Akk das · Dat dem', note:'Das Kind, das spielt, …' },
  { ch:'K7', type:'GR', front:'Relativpronomen: plural', back:'Nom/Akk die · Dat denen', note:'Die Leute, denen ich helfe, …' },
  { ch:'K7', type:'GR', front:'Adjektivendung after der/die/das (weak): Nom m/f/n', back:'-e / -e / -e', note:'der alte Mann, die alte Frau, das alte Kind.' },
  { ch:'K7', type:'GR', front:'Adjektivendung after ein/kein/mein (mixed): Nom m/f/n', back:'-er / -e / -es', note:'ein alter Mann, eine alte Frau, ein altes Kind.' },
  { ch:'K7', type:'GR', front:'Adjektivendung Akkusativ (weak)', back:'-en / -e / -e / -en', note:'den alten Mann, die alte Frau, das alte Kind, die alten Leute.' },
  { ch:'K7', type:'GR', front:'Adjektivendung Dativ (all forms)', back:'always -en', note:'dem alten Mann, der alten Frau, dem alten Kind, den alten Leuten.' },
  { ch:'K7', type:'GR', front:'Komparativ', back:'adj + -er (+ umlaut for alt/groß/jung etc.)', note:'schneller, größer, älter, jünger.' },
  { ch:'K7', type:'GR', front:'Superlativ (predicate)', back:'am + adj + -sten', note:'am schnellsten, am größten, am ältesten.' },
  { ch:'K7', type:'GR', front:'Superlativ (attributive)', back:'der/die/das + adj + -ste + (ending)', note:'der schnellste Zug, die älteste Frau.' },
  { ch:'K7', type:'GR', front:'Irregular: gut / viel / gern', back:'besser / mehr / lieber → am besten / am meisten / am liebsten' },

  // K7 · Vocab
  { ch:'K7', type:'VO', front:'das Café / Kaffeehaus', back:'café / coffeehouse', note:'Viennese tradition.' },
  { ch:'K7', type:'VO', front:'die Melange', back:'Viennese coffee with steamed milk' },
  { ch:'K7', type:'VO', front:'der Kellner / die Kellnerin', back:'waiter / waitress' },
  { ch:'K7', type:'VO', front:'die Rechnung', back:'the bill / check', note:'Die Rechnung, bitte!' },
  { ch:'K7', type:'VO', front:'das Trinkgeld', back:'tip (gratuity)' },
  { ch:'K7', type:'VO', front:'bestellen', back:'to order (food/drink)' },
  { ch:'K7', type:'VO', front:'empfehlen', back:'to recommend', note:'Irregular: er empfiehlt.' },
  { ch:'K7', type:'VO', front:'schmecken', back:'to taste good', note:'Das schmeckt!' },
  { ch:'K7', type:'VO', front:'die Speisekarte', back:'menu' },
  { ch:'K7', type:'VO', front:'die Vorspeise / das Hauptgericht / die Nachspeise', back:'starter / main course / dessert' },

  // K8 · Grammar (Konjunktiv II, Passiv, Infinitivkonstruktionen)
  { ch:'K8', type:'GR', front:'Konjunktiv II: würde + Infinitiv', back:'would + verb (hypothetical / polite)', note:'Ich würde gern reisen. Was würdest du machen?' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: wäre', back:'would be (from sein)', note:'Ich wäre glücklich. Wenn ich reich wäre…' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: hätte', back:'would have (from haben)', note:'Ich hätte gern einen Kaffee.' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: könnte / müsste / sollte', back:'could / would have to / should', note:'Könntest du mir helfen? Ich müsste mehr lernen.' },
  { ch:'K8', type:'GR', front:'Konjunktiv II: wenn-Satz', back:'Wenn + Konj II …, dann würde/wäre/hätte …', note:'Wenn ich Zeit hätte, würde ich mehr lesen.' },
  { ch:'K8', type:'GR', front:'Passiv Präsens', back:'wird + Partizip II', note:'Das Auto wird repariert.' },
  { ch:'K8', type:'GR', front:'Passiv Präteritum', back:'wurde + Partizip II', note:'Das Auto wurde repariert.' },
  { ch:'K8', type:'GR', front:'Passiv Perfekt', back:'ist + Partizip II + worden', note:'Das Auto ist repariert worden.' },
  { ch:'K8', type:'GR', front:'Passiv agent (by whom?)', back:'von + Dativ', note:'Das Buch wird von dem Lehrer gelesen.' },
  { ch:'K8', type:'GR', front:'um … zu + Infinitiv', back:'in order to do something', note:'Ich lerne Deutsch, um in Wien zu leben.' },
  { ch:'K8', type:'GR', front:'ohne … zu + Infinitiv', back:'without doing something', note:'Er ging, ohne Tschüss zu sagen.' },
  { ch:'K8', type:'GR', front:'statt … zu + Infinitiv', back:'instead of doing something', note:'Statt zu lernen, schläft er.' },
  { ch:'K8', type:'GR', front:'Separable verb + zu', back:'zu goes BETWEEN prefix and stem: aufzumachen', note:'um die Tür aufzumachen.' },

  // K8 · Vocab
  { ch:'K8', type:'VO', front:'die Umwelt', back:'the environment' },
  { ch:'K8', type:'VO', front:'die Umweltverschmutzung', back:'environmental pollution' },
  { ch:'K8', type:'VO', front:'der Klimawandel', back:'climate change' },
  { ch:'K8', type:'VO', front:'die Nachhaltigkeit', back:'sustainability', note:'nachhaltig = sustainable.' },
  { ch:'K8', type:'VO', front:'erneuerbare Energien', back:'renewable energies' },
  { ch:'K8', type:'VO', front:'der Müll / der Abfall', back:'garbage / waste' },
  { ch:'K8', type:'VO', front:'schützen', back:'to protect' },
  { ch:'K8', type:'VO', front:'verbrauchen', back:'to consume / use up' },
  { ch:'K8', type:'VO', front:'sparen', back:'to save' },
  { ch:'K8', type:'VO', front:'die Gleichberechtigung', back:'equal rights' },
  { ch:'K8', type:'VO', front:'die Demokratie', back:'democracy' },
  { ch:'K8', type:'VO', front:'wählen', back:'to vote / to elect / to choose', note:'die Wahl = the election.' },
  { ch:'K8', type:'VO', front:'das Gesetz', back:'law (pl: Gesetze)' },
  { ch:'K8', type:'VO', front:'die Regierung', back:'government' },
  { ch:'K8', type:'VO', front:'die Gesellschaft', back:'society' },
  { ch:'K8', type:'VO', front:'die Bewerbung', back:'job application', note:'sich bewerben = to apply.' },
  { ch:'K8', type:'VO', front:'der Lebenslauf', back:'résumé / CV' },
  { ch:'K8', type:'VO', front:'das Vorstellungsgespräch', back:'job interview' },
  { ch:'K8', type:'VO', front:'das Gehalt', back:'salary' },
  { ch:'K8', type:'VO', front:'einstellen', back:'to hire', note:'stellt ein, hat eingestellt.' },
  { ch:'K8', type:'VO', front:'kündigen', back:'to quit / to fire' },
  { ch:'K8', type:'VO', front:'die Ausbildung', back:'vocational training' },
  { ch:'K8', type:'VO', front:'umziehen', back:'to move (to a new home)', note:'ist umgezogen (separable, sein!).' },
  { ch:'K8', type:'VO', front:'an deiner Stelle würde ich…', back:'if I were in your place, I would…', note:'Key Konjunktiv II phrase.' },
  { ch:'K8', type:'VO', front:'Es wäre schön, wenn…', back:'it would be nice if…', note:'Followed by Konjunktiv II verb at end.' },
];

/* ===================== VOCAB (for vocab page) ===================== */
const VOCAB = [
  { ch:'K5', de:'der Bahnhof', en:'train station', note:'' },
  { ch:'K5', de:'die Apotheke', en:'pharmacy', note:'' },
  { ch:'K5', de:'das Rathaus', en:'city hall', note:'' },
  { ch:'K5', de:'die Bibliothek', en:'library', note:'' },
  { ch:'K5', de:'das Krankenhaus', en:'hospital', note:'' },
  { ch:'K5', de:'die Post', en:'post office', note:'' },
  { ch:'K5', de:'der Supermarkt', en:'supermarket', note:'' },
  { ch:'K5', de:'die Bäckerei', en:'bakery', note:'' },
  { ch:'K5', de:'die Metzgerei', en:'butcher shop', note:'' },
  { ch:'K5', de:'helfen (+Dat)', en:'to help', note:'Ich helfe dir.' },
  { ch:'K5', de:'gehören (+Dat)', en:'to belong to', note:'Das gehört mir.' },
  { ch:'K5', de:'gefallen (+Dat)', en:'to please / to like', note:'Das Buch gefällt mir.' },
  { ch:'K5', de:'schmecken (+Dat)', en:'to taste good', note:'Das schmeckt mir.' },
  { ch:'K5', de:'antworten (+Dat)', en:'to answer (a person)', note:'Ich antworte dir.' },
  { ch:'K5', de:'glauben (+Dat)', en:'to believe someone', note:'Ich glaube dir nicht.' },

  { ch:'K6', de:'die Kindheit', en:'childhood', note:'' },
  { ch:'K6', de:'aufwachsen', en:'to grow up', note:'ist aufgewachsen.' },
  { ch:'K6', de:'damals', en:'back then', note:'' },
  { ch:'K6', de:'früher', en:'in the past / used to', note:'' },
  { ch:'K6', de:'plötzlich', en:'suddenly', note:'' },
  { ch:'K6', de:'zuerst / danach / schließlich', en:'first / afterwards / finally', note:'' },
  { ch:'K6', de:'verbringen', en:'to spend (time)', note:'hat verbracht.' },
  { ch:'K6', de:'passieren', en:'to happen', note:'ist passiert — sein!' },
  { ch:'K6', de:'erzählen', en:'to tell (a story)', note:'hat erzählt.' },
  { ch:'K6', de:'besuchen', en:'to visit', note:'hat besucht (no ge-).' },
  { ch:'K6', de:'vergessen', en:'to forget', note:'hat vergessen (no ge-).' },
  { ch:'K6', de:'einladen', en:'to invite', note:'hat eingeladen (separable).' },

  { ch:'K7', de:'das Café / Kaffeehaus', en:'café / coffeehouse', note:'Viennese tradition.' },
  { ch:'K7', de:'die Melange', en:'Viennese coffee w/ steamed milk', note:'' },
  { ch:'K7', de:'der Kellner / die Kellnerin', en:'waiter / waitress', note:'' },
  { ch:'K7', de:'die Rechnung', en:'the bill / check', note:'' },
  { ch:'K7', de:'das Trinkgeld', en:'tip (gratuity)', note:'' },
  { ch:'K7', de:'bestellen', en:'to order', note:'' },
  { ch:'K7', de:'empfehlen', en:'to recommend', note:'er empfiehlt (Stammvokalwechsel).' },
  { ch:'K7', de:'die Speisekarte', en:'menu', note:'' },
  { ch:'K7', de:'die Vorspeise', en:'starter / appetizer', note:'' },
  { ch:'K7', de:'das Hauptgericht', en:'main course', note:'' },
  { ch:'K7', de:'die Nachspeise', en:'dessert', note:'' },
  { ch:'K7', de:'gemütlich', en:'cozy / pleasant', note:'' },
  { ch:'K7', de:'geöffnet / geschlossen', en:'open / closed', note:'' },

  { ch:'K8', de:'die Umwelt', en:'environment', note:'' },
  { ch:'K8', de:'die Umweltverschmutzung', en:'environmental pollution', note:'' },
  { ch:'K8', de:'der Klimawandel', en:'climate change', note:'' },
  { ch:'K8', de:'die Nachhaltigkeit', en:'sustainability', note:'nachhaltig = sustainable.' },
  { ch:'K8', de:'erneuerbare Energien', en:'renewable energies', note:'' },
  { ch:'K8', de:'der Müll / der Abfall', en:'garbage / waste', note:'' },
  { ch:'K8', de:'schützen', en:'to protect', note:'' },
  { ch:'K8', de:'verbrauchen', en:'to consume / use up', note:'' },
  { ch:'K8', de:'sparen', en:'to save', note:'' },
  { ch:'K8', de:'trennen', en:'to separate (trash etc.)', note:'Müll trennen.' },
  { ch:'K8', de:'die Gleichberechtigung', en:'equal rights', note:'' },
  { ch:'K8', de:'die Demokratie', en:'democracy', note:'' },
  { ch:'K8', de:'wählen', en:'to vote / elect', note:'die Wahl = election.' },
  { ch:'K8', de:'das Gesetz', en:'law', note:'pl: Gesetze.' },
  { ch:'K8', de:'die Regierung', en:'government', note:'' },
  { ch:'K8', de:'die Gesellschaft', en:'society', note:'' },
  { ch:'K8', de:'die Bewerbung', en:'job application', note:'sich bewerben.' },
  { ch:'K8', de:'der Lebenslauf', en:'résumé / CV', note:'' },
  { ch:'K8', de:'das Vorstellungsgespräch', en:'job interview', note:'' },
  { ch:'K8', de:'das Gehalt', en:'salary', note:'' },
  { ch:'K8', de:'einstellen', en:'to hire', note:'stellt ein.' },
  { ch:'K8', de:'kündigen', en:'to quit / fire', note:'' },
  { ch:'K8', de:'die Ausbildung', en:'vocational training', note:'' },
  { ch:'K8', de:'die Stelle', en:'position / job', note:'' },
  { ch:'K8', de:'umziehen', en:'to move (residence)', note:'ist umgezogen.' },
];

/* ===================== QUIZ (explicit bank) ===================== */
const QUIZ = [
  // --- K5 ---
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Ich komme ___ der Schweiz.',
    opts:['aus','in','nach','zu'], a:0,
    explain:'aus = from (origin). Always Dativ.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Ich wohne ___ einem Jahr in Wien.',
    opts:['vor','seit','nach','für'], a:1,
    explain:'seit = for/since (ongoing action). Present tense + Dativ.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Er kauft immer ___ Aldi ein.',
    opts:['auf','bei','in','zu'], a:1,
    explain:'bei = at (a place/person). Always Dativ.' },
  { set:'K5', tag:'K5 · pronoun', type:'single',
    q:'Ich helfe ___.  (dem Lehrer)',
    opts:['ihn','ihm','er','ihr'], a:1,
    explain:'helfen takes Dativ → ihm for masculine.' },
  { set:'K5', tag:'K5 · 2-way prep', type:'single',
    q:'Das Buch liegt ___ dem Tisch.',
    opts:['auf','auf den','auf die','aufen'], a:0,
    explain:'liegen = state (wo?) → Dativ. auf + dem = auf dem.' },
  { set:'K5', tag:'K5 · 2-way prep', type:'single',
    q:'Ich lege das Buch ___ den Tisch.',
    opts:['auf','auf dem','auf die','auf einem'], a:0,
    explain:'legen = motion (wohin?) → Akkusativ. auf den Tisch.' },
  { set:'K5', tag:'K5 · wo-compound', type:'single',
    q:'___ schreibst du? — Mit einem Stift.',
    opts:['Wofür','Worauf','Womit','Wovon'], a:2,
    explain:'mit → womit.' },
  { set:'K5', tag:'K5 · pronoun', type:'single',
    q:'Das Buch gefällt ___ sehr. (to me)',
    opts:['mich','mir','ich','mein'], a:1,
    explain:'gefallen takes Dativ → mir.' },
  { set:'K5', tag:'K5 · Dativ', type:'single',
    q:'Wir fahren ___ Bahnhof.',
    opts:['zu dem','zum','zur','zu der'], a:1,
    explain:'zu + dem = zum. Masculine Dativ contraction.' },

  // --- K6 ---
  { set:'K6', tag:'K6 · Präteritum', type:'single',
    q:'Als ich ein Kind ___, wohnten wir in Berlin.',
    opts:['bin','war','habe','hatte'], a:1,
    explain:'Präteritum of sein, 1./3. Sg. = war. In narratives use Präteritum of sein/haben/modals.' },
  { set:'K6', tag:'K6 · Perfekt aux', type:'single',
    q:'Ich ___ gestern nach Wien gefahren.',
    opts:['habe','bin','war','hatte'], a:1,
    explain:'fahren = motion → sein. Ich bin gefahren.' },
  { set:'K6', tag:'K6 · Perfekt aux', type:'single',
    q:'Ich ___ einen Apfel gegessen.',
    opts:['habe','bin','war','hatte'], a:0,
    explain:'essen → haben. No motion/change of state.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of telefonieren?',
    opts:['getelefoniert','telefoniert','telefoniergt','getelefonier'], a:1,
    explain:'-ieren verbs take NO ge-: just telefoniert.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of besuchen?',
    opts:['gebesucht','besucht','besuchtet','gebesuch'], a:1,
    explain:'Inseparable prefix be- → NO ge-: besucht.' },
  { set:'K6', tag:'K6 · Partizip II', type:'single',
    q:'Partizip II of aufmachen?',
    opts:['aufgemacht','gemachtauf','aufmachtet','geaufmacht'], a:0,
    explain:'Separable verb: prefix + ge + stem + -t → aufgemacht.' },
  { set:'K6', tag:'K6 · als/wenn/wann', type:'single',
    q:'___ ich jung war, spielte ich Fußball.',
    opts:['Wenn','Als','Wann','Ob'], a:1,
    explain:'als = one-time past event.' },
  { set:'K6', tag:'K6 · als/wenn/wann', type:'single',
    q:'___ ich müde bin, schlafe ich früh.',
    opts:['Als','Wenn','Wann','Dass'], a:1,
    explain:'wenn = recurring condition ("whenever/if") — or future.' },
  { set:'K6', tag:'K6 · weil/denn', type:'single',
    q:'Ich esse, ___ ich Hunger habe. (verb goes to end!)',
    opts:['denn','weil','aber','und'], a:1,
    explain:'weil = subordinating conjunction → verb to end. denn keeps main-clause order.' },

  // --- K7 ---
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Der Mann, ___ ich kenne, heißt Peter. (masc. Akk)',
    opts:['der','den','dem','dessen'], a:1,
    explain:'Antecedent: masculine. Role in clause: object (Akk) → den.' },
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Die Frau, ___ ich helfe, ist nett. (fem. Dat — helfen!)',
    opts:['die','der','den','dessen'], a:1,
    explain:'helfen takes Dativ → der (fem. Dat).' },
  { set:'K7', tag:'K7 · Relativpronomen', type:'single',
    q:'Die Leute, ___ ich vertraue, sind meine Freunde. (pl. Dat — vertrauen!)',
    opts:['die','denen','den','dessen'], a:1,
    explain:'vertrauen takes Dativ; plural Dativ = denen.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Ich sehe den ___ Mann. (alt, weak decl.)',
    opts:['alter','alte','alten','altes'], a:2,
    explain:'Masculine Akk weak → -en. den alten Mann.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Das ist ein ___ Kind. (klein, mixed decl., Nom n.)',
    opts:['klein','kleiner','kleine','kleines'], a:3,
    explain:'After ein- in Nom neuter → -es. ein kleines Kind.' },
  { set:'K7', tag:'K7 · Adjektiv', type:'single',
    q:'Ich wohne in einem ___ Haus. (groß, Dat n.)',
    opts:['groß','großes','großen','großer'], a:2,
    explain:'Dativ endings are -en for all genders after ein-.' },
  { set:'K7', tag:'K7 · Komparativ', type:'single',
    q:'Komparativ von "alt"?',
    opts:['alter','älter','alterer','ältester'], a:1,
    explain:'Umlaut + -er: älter.' },
  { set:'K7', tag:'K7 · Superlativ', type:'single',
    q:'Superlativ (predicate) von "gut"?',
    opts:['am gut','am guten','am besten','am bester'], a:2,
    explain:'Irregular: gut → besser → am besten.' },

  // --- K8 ---
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'Wenn ich Zeit ___, würde ich mehr lernen.',
    opts:['habe','hätte','hatte','haben'], a:1,
    explain:'Konjunktiv II of haben = hätte. Wenn + Konj II …, (dann) würde …' },
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'An deiner Stelle ___ ich nach Hause gehen.',
    opts:['werde','würde','wurde','war'], a:1,
    explain:'Konjunktiv II: würde + Infinitiv. Polite/hypothetical.' },
  { set:'K8', tag:'K8 · Konj II', type:'single',
    q:'Ich ___ gern einen Kaffee, bitte. (polite "would like")',
    opts:['habe','hätte','bin','würde'], a:1,
    explain:'Ich hätte gern… = standard polite request.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Auto ___ repariert. (Present passive)',
    opts:['ist','wird','hat','war'], a:1,
    explain:'Passiv Präsens: werden + Partizip II → wird repariert.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Haus ___ 1920 gebaut. (Past passive — Präteritum)',
    opts:['wird','wurde','ist','hat'], a:1,
    explain:'Passiv Präteritum: wurde + Partizip II.' },
  { set:'K8', tag:'K8 · Passiv', type:'single',
    q:'Das Buch wird ___ dem Lehrer gelesen. (agent)',
    opts:['mit','von','bei','durch'], a:1,
    explain:'Agent in passive → von + Dativ.' },
  { set:'K8', tag:'K8 · um zu', type:'single',
    q:'Ich lerne Deutsch, ___ in Wien ___ leben.',
    opts:['um … zu','ohne … zu','statt … zu','damit … zu'], a:0,
    explain:'um … zu + Infinitiv = in order to.' },
  { set:'K8', tag:'K8 · ohne/statt zu', type:'single',
    q:'Er ging, ___ Tschüss ___ sagen.',
    opts:['um … zu','ohne … zu','statt … zu','weil … zu'], a:1,
    explain:'ohne … zu + Infinitiv = without doing.' },
  { set:'K8', tag:'K8 · separable+zu', type:'single',
    q:'Sie versucht, die Tür ___.',
    opts:['aufmachen zu','zu aufmachen','aufzumachen','aufmachenzu'], a:2,
    explain:'Separable verb + zu: zu goes BETWEEN prefix and stem → aufzumachen.' },

  // --- Mixed final prep ---
  { set:'mixed', tag:'mixed', type:'single',
    q:'Wenn ich du ___, würde ich mehr schlafen.',
    opts:['bin','war','wäre','gewesen'], a:2,
    explain:'Konjunktiv II of sein = wäre.' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Ich bin gestern ins Kino ___.',
    opts:['gehen','gegangen','gegehen','geht'], a:1,
    explain:'Strong Partizip II: gehen → gegangen. sein!' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Die Umwelt muss ___ werden.',
    opts:['schützen','geschützt','schützte','zu schützen'], a:1,
    explain:'Passive with modal: modal + Partizip II + werden. muss geschützt werden.' },
  { set:'mixed', tag:'mixed', type:'multi',
    q:'Which prepositions are ALWAYS Dativ? (select all)',
    opts:['aus','bei','für','mit','nach','ohne','seit','von','zu'],
    a:[0,1,3,4,6,7,8],
    explain:'Dative-only: aus, außer, bei, mit, nach, seit, von, zu. für and ohne are Akkusativ-only.' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Das Kind, ___ Mutter Ärztin ist, heißt Anna.',
    opts:['das','dessen','deren','der'], a:1,
    explain:'Genitive relative pronoun for neuter/masculine = dessen. (K7 extension.)' },
  { set:'mixed', tag:'mixed', type:'single',
    q:'Present tense active → present passive: "Der Lehrer liest das Buch."',
    opts:['Das Buch wird gelesen.','Das Buch ist gelesen.','Das Buch wird lesen.','Das Buch war gelesen.'], a:0,
    explain:'Passiv Präsens: wird + Partizip II.' },
];

/* ===================== GRAMMAR tables ===================== */
const GRAMMAR = [
  {
    title: 'Subordinating conjunctions — dass / weil / wenn / als',
    sub:   'Verb moves to END of clause (Verbendstellung)',
    rows: [
      ['Word','Meaning','Example'],
      ['dass','that','Ich finde, dass Bananen lecker sind.'],
      ['weil','because (verb → end)','Ich esse, weil ich Hunger habe.'],
      ['wenn','when / if (recurring or future)','Wenn ich müde bin, schlafe ich.'],
      ['als','when (one-time past event)','Als ich jung war, wohnte ich in Berlin.'],
      ['denn','because (keeps main-clause order)','Ich esse, denn ich habe Hunger.'],
    ]
  },
  {
    title: 'Modal verbs — present tense',
    sub: 'Conjugated modal in V2, Infinitive at end: Ich muss Deutsch lernen.',
    rows: [
      ['Verb','Meaning','ich','du','er/sie/es','wir/sie/Sie'],
      ['können','can','kann','kannst','kann','können'],
      ['wollen','want to','will','willst','will','wollen'],
      ['müssen','must','muss','musst','muss','müssen'],
      ['dürfen','may','darf','darfst','darf','dürfen'],
      ['sollen','should','soll','sollst','soll','sollen'],
      ['möchten','would like','möchte','möchtest','möchte','möchten'],
    ]
  },
  {
    title: 'Two-way prepositions (Wechselpräpositionen)',
    sub: 'Wo? → Dativ · Wohin? → Akkusativ · in·auf·unter·über·neben·zwischen·hinter·an·vor',
    rows: [
      ['State verbs (Dativ)','Motion verbs (Akkusativ)'],
      ['liegen · stehen · hängen · sitzen','legen · stellen · hängen · setzen'],
      ['Das Buch liegt auf dem Tisch.','Ich lege das Buch auf den Tisch.'],
    ]
  },
  {
    title: 'Dative-only prepositions',
    sub: 'aus · außer · bei · mit · nach · seit · von · zu',
    rows: [
      ['Prep.','Meaning','Example'],
      ['aus','from; made of','Ich komme aus der Schweiz.'],
      ['bei','at, near, with','Ich kaufe bei Aldi ein.'],
      ['mit','with','Ich esse mit meiner Mutter.'],
      ['nach','after; to (cities)','Nach dem Unterricht trinken wir Kaffee.'],
      ['seit','since / for (ongoing)','Seit einem Jahr lebe ich hier.'],
      ['von','from / of','Das Buch ist vom Lehrer.'],
      ['zu','to (nearby)','Wir fahren zum Bahnhof.'],
    ]
  },
  {
    title: 'Da- and Wo-compounds',
    sub: 'For THINGS (not people). da(r)+prep = "with it" · wo(r)+prep = "with what?"',
    rows: [
      ['Prep.','Da-form','Wo-form'],
      ['mit','damit','womit'],
      ['für','dafür','wofür'],
      ['auf','darauf','worauf'],
      ['über','darüber','worüber'],
      ['an','daran','woran'],
      ['von','davon','wovon'],
    ]
  },
  {
    title: 'Personal pronouns — Nom / Akk / Dat',
    sub: '',
    rows: [
      ['Person','Nom','Akk','Dat'],
      ['ich','ich','mich','mir'],
      ['du','du','dich','dir'],
      ['er','er','ihn','ihm'],
      ['sie (f)','sie','sie','ihr'],
      ['es','es','es','ihm'],
      ['wir','wir','uns','uns'],
      ['ihr','ihr','euch','euch'],
      ['sie / Sie','sie / Sie','sie / Sie','ihnen / Ihnen'],
    ]
  },
  {
    title: 'Präteritum: sein & haben',
    sub: 'In narratives, sein/haben and modals stay in Präteritum even in speech.',
    rows: [
      ['Person','sein','haben'],
      ['ich','war','hatte'],
      ['du','warst','hattest'],
      ['er/sie/es','war','hatte'],
      ['wir','waren','hatten'],
      ['ihr','wart','hattet'],
      ['sie / Sie','waren','hatten'],
    ]
  },
  {
    title: 'Perfekt — Partizip II formation',
    sub: 'sein for motion/change-of-state. haben for most others.',
    rows: [
      ['Type','Pattern','Example'],
      ['Regular (weak)','ge- + stem + -t','kaufen → gekauft'],
      ['Irregular (strong)','ge- + new stem + -en','gehen → gegangen'],
      ['-ieren verbs','stem + -iert (no ge-)','telefonieren → telefoniert'],
      ['Inseparable prefix','no ge-','besuchen → besucht'],
      ['Separable prefix','prefix + ge + stem','aufmachen → aufgemacht'],
    ]
  },
  {
    title: 'Key strong verbs — Partizip II + aux',
    sub: 'Memorize these; they appear constantly.',
    rows: [
      ['Verb','Partizip II','Aux'],
      ['gehen','gegangen','sein'],
      ['fahren','gefahren','sein'],
      ['kommen','gekommen','sein'],
      ['bleiben','geblieben','sein'],
      ['werden','geworden','sein'],
      ['sein','gewesen','sein'],
      ['essen','gegessen','haben'],
      ['trinken','getrunken','haben'],
      ['schreiben','geschrieben','haben'],
      ['sprechen','gesprochen','haben'],
      ['denken','gedacht','haben'],
      ['bringen','gebracht','haben'],
      ['lesen','gelesen','haben'],
      ['sehen','gesehen','haben'],
    ]
  },
  {
    title: 'als / wenn / wann',
    sub: '',
    rows: [
      ['Word','Use','Example'],
      ['als','one-time past event','Als ich ein Kind war, wohnte ich in Berlin.'],
      ['wenn','recurring or if/whenever','Wenn ich müde bin, schlafe ich früh.'],
      ['wann','question word (when?)','Wann kommst du?'],
    ]
  },
  {
    title: 'Adjective endings — weak (after der/die/das)',
    sub: '',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','-e','-e','-e','-en'],
      ['Akk','-en','-e','-e','-en'],
      ['Dat','-en','-en','-en','-en'],
    ]
  },
  {
    title: 'Adjective endings — mixed (after ein/kein/mein)',
    sub: '',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','-er','-e','-es','-en'],
      ['Akk','-en','-e','-es','-en'],
      ['Dat','-en','-en','-en','-en'],
    ]
  },
  {
    title: 'Relative pronouns (Relativpronomen)',
    sub: 'Gender = antecedent. Case = role in the relative clause. Verb → end.',
    rows: [
      ['Case','Mask.','Fem.','Neut.','Pl.'],
      ['Nom','der','die','das','die'],
      ['Akk','den','die','das','die'],
      ['Dat','dem','der','dem','denen'],
      ['Gen','dessen','deren','dessen','deren'],
    ]
  },
  {
    title: 'Komparativ & Superlativ',
    sub: 'Regular: adj + -er | Superlative predicate: am + adj + -sten',
    rows: [
      ['Base','Komparativ','Superlativ (predicate)'],
      ['schnell','schneller','am schnellsten'],
      ['groß','größer','am größten'],
      ['alt','älter','am ältesten'],
      ['jung','jünger','am jüngsten'],
      ['gut','besser','am besten'],
      ['viel','mehr','am meisten'],
      ['gern','lieber','am liebsten'],
      ['hoch','höher','am höchsten'],
    ]
  },
  {
    title: 'Konjunktiv II — hypothetical / polite',
    sub: 'würde + Infinitiv for most. Irregular: wäre, hätte, könnte, müsste, sollte.',
    rows: [
      ['Person','würde','wäre','hätte','könnte'],
      ['ich','würde','wäre','hätte','könnte'],
      ['du','würdest','wärst','hättest','könntest'],
      ['er/sie/es','würde','wäre','hätte','könnte'],
      ['wir','würden','wären','hätten','könnten'],
      ['ihr','würdet','wärt','hättet','könntet'],
      ['sie / Sie','würden','wären','hätten','könnten'],
    ]
  },
  {
    title: 'Passiv',
    sub: 'werden + Partizip II · Agent: von + Dativ',
    rows: [
      ['Tense','Structure','Example'],
      ['Präsens','wird + PP','Das Buch wird gelesen.'],
      ['Präteritum','wurde + PP','Das Buch wurde gelesen.'],
      ['Perfekt','ist + PP + worden','Das Buch ist gelesen worden.'],
      ['Modal + Passiv','modal + PP + werden','Das Buch muss gelesen werden.'],
    ]
  },
  {
    title: 'Infinitivkonstruktionen',
    sub: 'zu + Infinitiv at clause end. Separable verb: zu goes between prefix and stem → aufzumachen.',
    rows: [
      ['Construction','Meaning','Example'],
      ['um … zu','in order to','Ich lerne Deutsch, um in Wien zu leben.'],
      ['ohne … zu','without doing','Er ging, ohne zu sagen.'],
      ['statt … zu','instead of doing','Statt zu lernen, schlief er.'],
    ]
  },
];

/* ===================== K8 focus page ===================== */
const K8_SECTIONS = [
  {
    title: 'Key grammar structures',
    flavor: 'purple',
    items: [
      { de:'Konjunktiv II', en:'würde + Inf · wäre · hätte · könnte', note:'Wenn ich Zeit hätte, würde ich lernen.' },
      { de:'Passiv Präsens', en:'wird + Partizip II', note:'Das Essen wird gekocht.' },
      { de:'Passiv Präteritum', en:'wurde + Partizip II', note:'Das Essen wurde gekocht.' },
      { de:'um … zu', en:'in order to', note:'Ich lerne, um zu bestehen.' },
      { de:'ohne … zu', en:'without doing', note:'Er ging, ohne zu fragen.' },
      { de:'statt … zu', en:'instead of doing', note:'Statt zu lernen, schlief er.' },
    ]
  },
  {
    title: 'Konjunktiv II phrases to know',
    flavor: 'normal',
    items: [
      { de:'Ich wäre gern reich.', en:'I would like to be rich.' },
      { de:'Wenn ich Zeit hätte…', en:'If I had time…' },
      { de:'Könntest du mir helfen?', en:'Could you help me?' },
      { de:'Ich würde gern reisen.', en:'I would like to travel.' },
      { de:'An deiner Stelle würde ich…', en:'If I were in your place, I would…' },
      { de:'Es wäre schön, wenn…', en:'It would be nice if…' },
      { de:'Ich hätte gern einen Kaffee.', en:"I'd like a coffee. (polite)" },
      { de:'Dürfte ich…?', en:'Would I be permitted to…?' },
    ]
  },
  {
    title: 'Umwelt & Gesellschaft',
    flavor: 'normal',
    items: [
      { de:'die Umwelt', en:'environment' },
      { de:'die Umweltverschmutzung', en:'environmental pollution' },
      { de:'der Klimawandel', en:'climate change' },
      { de:'die Nachhaltigkeit', en:'sustainability' },
      { de:'erneuerbare Energien', en:'renewable energies' },
      { de:'schützen', en:'to protect' },
      { de:'die Gleichberechtigung', en:'equal rights' },
      { de:'die Demokratie', en:'democracy' },
      { de:'wählen', en:'to vote / elect', note:'die Wahl = the election.' },
      { de:'das Gesetz', en:'law (pl: Gesetze)' },
      { de:'die Regierung', en:'government' },
      { de:'verbrauchen', en:'to consume / use up' },
    ]
  },
  {
    title: 'Beruf & Arbeit',
    flavor: 'normal',
    items: [
      { de:'die Bewerbung', en:'job application', note:'sich bewerben = to apply.' },
      { de:'der Lebenslauf', en:'résumé / CV' },
      { de:'das Vorstellungsgespräch', en:'job interview' },
      { de:'das Gehalt', en:'salary' },
      { de:'einstellen', en:'to hire' },
      { de:'kündigen', en:'to quit / to fire' },
      { de:'die Ausbildung', en:'vocational training' },
      { de:'die Stelle', en:'position / job' },
    ]
  },
];

/* ===================== VERBS (for Conjugate drill) =====================
   For each verb: infinitive, English gloss, Präteritum (3rd sg.),
   Partizip II, auxiliary (haben/sein), chapter tag.
   ====================================================================== */
const VERBS = [
  // core irregulars
  { inf:'sein',       en:'to be',            pret:'war',        part:'gewesen',     aux:'sein',  ch:'K6' },
  { inf:'haben',      en:'to have',          pret:'hatte',      part:'gehabt',      aux:'haben', ch:'K6' },
  { inf:'werden',     en:'to become',        pret:'wurde',      part:'geworden',    aux:'sein',  ch:'K8' },
  // motion / sein
  { inf:'gehen',      en:'to go',            pret:'ging',       part:'gegangen',    aux:'sein',  ch:'K6' },
  { inf:'kommen',     en:'to come',          pret:'kam',        part:'gekommen',    aux:'sein',  ch:'K6' },
  { inf:'fahren',     en:'to drive/travel',  pret:'fuhr',       part:'gefahren',    aux:'sein',  ch:'K6' },
  { inf:'fliegen',    en:'to fly',           pret:'flog',       part:'geflogen',    aux:'sein',  ch:'K6' },
  { inf:'laufen',     en:'to run',           pret:'lief',       part:'gelaufen',    aux:'sein',  ch:'K6' },
  { inf:'bleiben',    en:'to stay',          pret:'blieb',      part:'geblieben',   aux:'sein',  ch:'K6' },
  { inf:'passieren',  en:'to happen',        pret:'passierte',  part:'passiert',    aux:'sein',  ch:'K6' },
  { inf:'aufwachsen', en:'to grow up',       pret:'wuchs auf',  part:'aufgewachsen',aux:'sein',  ch:'K6' },
  { inf:'umziehen',   en:'to move (house)',  pret:'zog um',     part:'umgezogen',   aux:'sein',  ch:'K8' },
  // strong, haben
  { inf:'essen',      en:'to eat',           pret:'aß',         part:'gegessen',    aux:'haben', ch:'K6' },
  { inf:'trinken',    en:'to drink',         pret:'trank',      part:'getrunken',   aux:'haben', ch:'K6' },
  { inf:'sehen',      en:'to see',           pret:'sah',        part:'gesehen',     aux:'haben', ch:'K6' },
  { inf:'sprechen',   en:'to speak',         pret:'sprach',     part:'gesprochen',  aux:'haben', ch:'K6' },
  { inf:'schreiben',  en:'to write',         pret:'schrieb',    part:'geschrieben', aux:'haben', ch:'K6' },
  { inf:'lesen',      en:'to read',          pret:'las',        part:'gelesen',     aux:'haben', ch:'K6' },
  { inf:'nehmen',     en:'to take',          pret:'nahm',       part:'genommen',    aux:'haben', ch:'K6' },
  { inf:'geben',      en:'to give',          pret:'gab',        part:'gegeben',     aux:'haben', ch:'K6' },
  { inf:'finden',     en:'to find',          pret:'fand',       part:'gefunden',    aux:'haben', ch:'K6' },
  { inf:'schlafen',   en:'to sleep',         pret:'schlief',    part:'geschlafen',  aux:'haben', ch:'K6' },
  { inf:'treffen',    en:'to meet',          pret:'traf',       part:'getroffen',   aux:'haben', ch:'K6' },
  { inf:'helfen',     en:'to help',          pret:'half',       part:'geholfen',    aux:'haben', ch:'K5' },
  { inf:'empfehlen',  en:'to recommend',     pret:'empfahl',    part:'empfohlen',   aux:'haben', ch:'K7' },
  // mixed ("haben" forms like "bringen")
  { inf:'bringen',    en:'to bring',         pret:'brachte',    part:'gebracht',    aux:'haben', ch:'K6' },
  { inf:'denken',     en:'to think',         pret:'dachte',     part:'gedacht',     aux:'haben', ch:'K6' },
  { inf:'wissen',     en:'to know (fact)',   pret:'wusste',     part:'gewusst',     aux:'haben', ch:'K6' },
  { inf:'kennen',     en:'to know (person)', pret:'kannte',     part:'gekannt',     aux:'haben', ch:'K6' },
  { inf:'verbringen', en:'to spend (time)',  pret:'verbrachte', part:'verbracht',   aux:'haben', ch:'K6' },
  // regular weak
  { inf:'kaufen',     en:'to buy',           pret:'kaufte',     part:'gekauft',     aux:'haben', ch:'K6' },
  { inf:'spielen',    en:'to play',          pret:'spielte',    part:'gespielt',    aux:'haben', ch:'K6' },
  { inf:'lernen',     en:'to learn / study', pret:'lernte',     part:'gelernt',     aux:'haben', ch:'K6' },
  { inf:'arbeiten',   en:'to work',          pret:'arbeitete',  part:'gearbeitet',  aux:'haben', ch:'K6' },
  { inf:'machen',     en:'to do / make',     pret:'machte',     part:'gemacht',     aux:'haben', ch:'K6' },
  // separable / inseparable
  { inf:'einkaufen',  en:'to shop',          pret:'kaufte ein', part:'eingekauft',  aux:'haben', ch:'K6' },
  { inf:'aufmachen',  en:'to open',          pret:'machte auf', part:'aufgemacht',  aux:'haben', ch:'K6' },
  { inf:'besuchen',   en:'to visit',         pret:'besuchte',   part:'besucht',     aux:'haben', ch:'K6' },
  { inf:'verstehen',  en:'to understand',    pret:'verstand',   part:'verstanden',  aux:'haben', ch:'K6' },
  { inf:'vergessen',  en:'to forget',        pret:'vergaß',     part:'vergessen',   aux:'haben', ch:'K6' },
  { inf:'bestellen',  en:'to order',         pret:'bestellte',  part:'bestellt',    aux:'haben', ch:'K7' },
  { inf:'telefonieren',en:'to phone',        pret:'telefonierte',part:'telefoniert',aux:'haben', ch:'K6' },
  { inf:'studieren',  en:'to study',         pret:'studierte',  part:'studiert',    aux:'haben', ch:'K6' },
  { inf:'schützen',   en:'to protect',       pret:'schützte',   part:'geschützt',   aux:'haben', ch:'K8' },
  { inf:'sparen',     en:'to save',          pret:'sparte',     part:'gespart',     aux:'haben', ch:'K8' },
  { inf:'wählen',     en:'to vote / choose', pret:'wählte',     part:'gewählt',     aux:'haben', ch:'K8' },
  { inf:'einstellen', en:'to hire',          pret:'stellte ein',part:'eingestellt', aux:'haben', ch:'K8' },
  { inf:'kündigen',   en:'to quit / fire',   pret:'kündigte',   part:'gekündigt',   aux:'haben', ch:'K8' },
];

/* ===================== LUCKEN (fill-in-the-blank drill) =====================
   Each item has:
     sentence  — shown with ___ where the blank goes
     answer    — accepted answer (case-insensitive; umlauts normalized)
     alts      — optional array of other acceptable strings
     hint      — 1-line teacher hint (shown on request)
     explain   — 1-line explanation shown after the answer
     tag       — short label for the badge
     ch        — chapter
   ========================================================================= */
const LUCKEN = [
  // K5 · Prepositions + cases
  { ch:'K5', tag:'prep · Dativ',       sentence:'Ich fahre mit ___ Bus zur Arbeit.',            answer:'dem',       hint:'mit + Dativ; der Bus',                explain:'mit is always Dativ; masc. dat. = dem.' },
  { ch:'K5', tag:'prep · contraction', sentence:'Wir gehen zu ___ Bahnhof.',                     answer:'zum',       alts:['zu dem'], hint:'zu + dem contracts', explain:'zu + dem → zum.' },
  { ch:'K5', tag:'prep · contraction', sentence:'Ich komme gerade von ___ Arzt.',                answer:'vom',       alts:['von dem'], hint:'von + dem contracts',explain:'von + dem → vom.' },
  { ch:'K5', tag:'prep · seit + Dat',  sentence:'Ich lerne Deutsch seit ___ Jahr. (one, neut.)', answer:'einem',     hint:'seit + Dativ; neut. dat. = einem',    explain:'seit is always Dativ; ein (neut. dat.) → einem.' },
  { ch:'K5', tag:'two-way · wo?',      sentence:'Das Buch liegt auf ___ Tisch. (wo?)',           answer:'dem',       hint:'location → Dativ',                    explain:'wo? → Dativ; der Tisch (dat.) → dem.' },
  { ch:'K5', tag:'two-way · wohin?',   sentence:'Ich lege das Buch auf ___ Tisch. (wohin?)',     answer:'den',       hint:'motion → Akkusativ',                  explain:'wohin? → Akk.; der Tisch (acc.) → den.' },
  { ch:'K5', tag:'pronoun · Dativ',    sentence:'Kannst du ___ helfen? (to me)',                 answer:'mir',       hint:'helfen + Dativ',                      explain:'helfen takes Dativ; "to me" = mir.' },

  // K6 · Perfekt auxiliary + conjunctions
  { ch:'K6', tag:'Perfekt · aux',      sentence:'Ich ___ nach Berlin gefahren.',                 answer:'bin',       hint:'motion → sein',                       explain:'fahren = motion → Perfekt with sein; 1.Sg. = bin.' },
  { ch:'K6', tag:'Perfekt · aux',      sentence:'Wir ___ einen Kuchen gegessen.',                answer:'haben',     hint:'no motion → haben',                   explain:'essen → Perfekt with haben; 1.Pl. = haben.' },
  { ch:'K6', tag:'als / wenn / wann',  sentence:'___ ich jung war, lebte ich in München.',       answer:'Als',       alts:['als'], hint:'single past event',      explain:'Als = single completed past event.' },
  { ch:'K6', tag:'als / wenn / wann',  sentence:'Immer ___ es regnet, bleibe ich zu Hause.',     answer:'wenn',      hint:'recurring / if',                      explain:'wenn = recurring (or "if") in present/future.' },
  { ch:'K6', tag:'weil (verb to end)', sentence:'Ich esse, weil ich Hunger ___.',                answer:'habe',      hint:'weil sends verb to end',              explain:'weil is subordinating → conjugated verb goes last.' },
  { ch:'K6', tag:'dass',               sentence:'Ich finde, dass Deutsch schön ___.',            answer:'ist',       hint:'dass → verb to end',                  explain:'dass is subordinating → conjugated verb last.' },

  // K7 · Adjective endings + relative pronouns
  { ch:'K7', tag:'adj · weak · Nom',   sentence:'Der alt___ Mann liest die Zeitung.',            answer:'e',         hint:'after der (masc. nom.): -e',          explain:'Weak ending after der (masc. nom.) = -e.' },
  { ch:'K7', tag:'adj · mixed · Nom',  sentence:'Ein schnell___ Auto steht vor dem Haus.',       answer:'es',        hint:'after ein (neut. nom.): -es',         explain:'Mixed ending after ein (neut. nom.) = -es.' },
  { ch:'K7', tag:'adj · weak · Akk',   sentence:'Ich kenne den klug___ Professor.',              answer:'en',        hint:'after den (masc. acc.): -en',         explain:'Weak ending after den (masc. acc.) = -en.' },
  { ch:'K7', tag:'adj · Dativ',        sentence:'Er hilft der alt___ Frau.',                     answer:'en',        hint:'Dativ = always -en',                  explain:'Every adjective in the dative takes -en.' },
  { ch:'K7', tag:'adj · plural',       sentence:'Die alt___ Leute sitzen im Café.',              answer:'en',        hint:'plural with def. article → -en',      explain:'die + plural → -en.' },
  { ch:'K7', tag:'relpron · masc acc', sentence:'Der Mann, ___ ich gestern gesehen habe, ist mein Lehrer.', answer:'den', hint:'masc., accusative', explain:'Masc. Akk. relative pronoun = den.' },
  { ch:'K7', tag:'relpron · fem dat',  sentence:'Die Frau, ___ ich geholfen habe, ist meine Tante.',       answer:'der', hint:'fem., dative',      explain:'Fem. Dat. relative pronoun = der.' },
  { ch:'K7', tag:'relpron · pl dat',   sentence:'Die Leute, ___ ich vertraue, sind meine Freunde.',        answer:'denen', hint:'plural, dative',  explain:'Plural Dat. relative pronoun = denen (irregular).' },
  { ch:'K7', tag:'Komparativ',         sentence:'Mein Bruder ist ___ als ich. (older)',          answer:'älter',     alts:['aelter'], hint:'comparative of alt — adds umlaut', explain:'alt → älter (umlaut added).' },
  { ch:'K7', tag:'Superlativ',         sentence:'Der ICE ist am ___. (fast)',                    answer:'schnellsten',hint:'am + adj + -sten',                   explain:'Predicate superlative: am schnellsten.' },

  // K8 · Konjunktiv II + Passiv + Infinitivkonstruktionen
  { ch:'K8', tag:'Konj II · würde',    sentence:'Wenn ich Zeit hätte, ___ ich mehr reisen.',     answer:'würde',     alts:['wuerde'], hint:'würde + Infinitiv',  explain:'Main clause in a Konj-II conditional takes würde + infinitive.' },
  { ch:'K8', tag:'Konj II · wäre',    sentence:'Ich ___ glücklich, wenn du kommen würdest.',    answer:'wäre',      alts:['waere'], hint:'sein → wäre',         explain:'Konjunktiv II of sein = wäre.' },
  { ch:'K8', tag:'Konj II · hätte',   sentence:'Sie ___ gern mehr Urlaub.',                      answer:'hätte',     alts:['haette'], hint:'haben → hätte',      explain:'Konjunktiv II of haben = hätte.' },
  { ch:'K8', tag:'Konj II · könnte',  sentence:'___ du mir bitte helfen? (polite)',             answer:'Könntest',  alts:['könntest','koenntest','Koenntest'], hint:'können → könnte; 2.Sg. = könntest', explain:'können → könnte; du-form = könntest (capital at sentence start).' },
  { ch:'K8', tag:'Passiv · Präsens',   sentence:'Das Auto ___ gerade repariert.',                answer:'wird',      hint:'werden + Partizip II',                explain:'Passiv Präsens 3.Sg. = wird.' },
  { ch:'K8', tag:'Passiv · Prät.',     sentence:'Das Buch ___ letzte Woche gelesen.',            answer:'wurde',     hint:'werden (Präteritum) + Partizip II',   explain:'Passiv Präteritum 3.Sg. = wurde.' },
  { ch:'K8', tag:'Passiv · Agent',     sentence:'Der Brief wurde ___ meinem Vater geschrieben.', answer:'von',       hint:'by whom? → von + Dat',                explain:'Passiv agent is expressed with von + Dativ.' },
  { ch:'K8', tag:'um … zu',            sentence:'Ich lerne Deutsch, ___ in Wien zu leben.',      answer:'um',        hint:'um … zu = in order to',               explain:'um + (…) + zu + Infinitiv = in order to.' },
  { ch:'K8', tag:'ohne … zu',          sentence:'Er ging, ___ Tschüss zu sagen.',                 answer:'ohne',      hint:'ohne … zu = without doing',           explain:'ohne + (…) + zu + Infinitiv = without doing.' },
  { ch:'K8', tag:'statt … zu',         sentence:'___ zu lernen, schläft er. (instead of)',       answer:'Statt',     alts:['statt'], hint:'statt … zu = instead of', explain:'statt + (…) + zu + Infinitiv = instead of.' },
];
